export interface EmojiItem {
  emoji: string;
  name: string;
  category: EmojiCategoryId;
  keywords?: string[];
}

export type EmojiCategoryId =
  | 'smileys'
  | 'people'
  | 'nature'
  | 'food'
  | 'activity'
  | 'travel'
  | 'objects'
  | 'symbols'
  | 'flags';

export interface CategoryInfo {
  id: EmojiCategoryId;
  label: string;
}

export const EMOJI_CATEGORIES: readonly CategoryInfo[] = [
  { id: 'smileys', label: 'Smileys & Emotion' },
  { id: 'people', label: 'People & Body' },
  { id: 'nature', label: 'Animals & Nature' },
  { id: 'food', label: 'Food & Drink' },
  { id: 'activity', label: 'Activity' },
  { id: 'travel', label: 'Travel & Places' },
  { id: 'objects', label: 'Objects' },
  { id: 'symbols', label: 'Symbols' },
  { id: 'flags', label: 'Flags' },
] as const;

export const POPULAR_EMOJIS: readonly string[] = [
  '👍', '❤️', '🎉', '🔥', '✨', '🚀', '👀', '✅',
  '👏', '💡', '💯', '😊', '🤔', '🥳', '🙌', '⭐',
];

export const EMOJI_DATA: readonly EmojiItem[] = [
  // --- Smileys & Emotion ---
  { emoji: '😀', name: 'grinning face', category: 'smileys', keywords: ['smile', 'happy', 'grin'] },
  { emoji: '😃', name: 'grinning face with big eyes', category: 'smileys', keywords: ['happy', 'joy', 'haha'] },
  { emoji: '😄', name: 'grinning face with smiling eyes', category: 'smileys', keywords: ['happy', 'laugh', 'pleased'] },
  { emoji: '😁', name: 'beaming face with smiling eyes', category: 'smileys', keywords: ['grin', 'happy', 'smile'] },
  { emoji: '😆', name: 'grinning squinting face', category: 'smileys', keywords: ['laugh', 'lol', 'haha'] },
  { emoji: '😅', name: 'grinning face with sweat', category: 'smileys', keywords: ['hot', 'relief', 'nervous', 'phew'] },
  { emoji: '🤣', name: 'rolling on the floor laughing', category: 'smileys', keywords: ['rofl', 'laugh', 'lol', 'haha'] },
  { emoji: '😂', name: 'face with tears of joy', category: 'smileys', keywords: ['cry', 'joy', 'lol', 'laugh'] },
  { emoji: '🙂', name: 'slightly smiling face', category: 'smileys', keywords: ['smile', 'happy'] },
  { emoji: '🙃', name: 'upside-down face', category: 'smileys', keywords: ['silly', 'sarcasm', 'irony'] },
  { emoji: '😉', name: 'winking face', category: 'smileys', keywords: ['wink', 'flirt', 'joke'] },
  { emoji: '😊', name: 'smiling face with smiling eyes', category: 'smileys', keywords: ['blush', 'proud', 'warm', 'happy'] },
  { emoji: '😇', name: 'smiling face with halo', category: 'smileys', keywords: ['angel', 'innocent', 'good'] },
  { emoji: '🥰', name: 'smiling face with hearts', category: 'smileys', keywords: ['love', 'crush', 'adorable', 'sweet'] },
  { emoji: '😍', name: 'smiling face with heart-eyes', category: 'smileys', keywords: ['love', 'crush', 'heart', 'adore'] },
  { emoji: '🤩', name: 'star-struck', category: 'smileys', keywords: ['stars', 'eyes', 'wow', 'excited'] },
  { emoji: '😘', name: 'face blowing a kiss', category: 'smileys', keywords: ['kiss', 'love', 'flirt'] },
  { emoji: '😗', name: 'kissing face', category: 'smileys', keywords: ['kiss'] },
  { emoji: '😚', name: 'kissing face with closed eyes', category: 'smileys', keywords: ['kiss', 'sweet'] },
  { emoji: '😋', name: 'face savoring food', category: 'smileys', keywords: ['yum', 'delicious', 'tasty', 'silly'] },
  { emoji: '😛', name: 'face with tongue', category: 'smileys', keywords: ['tongue', 'playful', 'silly'] },
  { emoji: '😜', name: 'winking face with tongue', category: 'smileys', keywords: ['wink', 'tongue', 'joke', 'crazy'] },
  { emoji: '🤪', name: 'zany face', category: 'smileys', keywords: ['crazy', 'wild', 'goofy'] },
  { emoji: '😝', name: 'squinting face with tongue', category: 'smileys', keywords: ['playful', 'tongue', 'laugh'] },
  { emoji: '🤑', name: 'money-mouth face', category: 'smileys', keywords: ['rich', 'dollar', 'cash', 'money'] },
  { emoji: '🤗', name: 'smiling face with open hands', category: 'smileys', keywords: ['hug', 'hugging', 'warm'] },
  { emoji: '🤭', name: 'face with hand over mouth', category: 'smileys', keywords: ['oops', 'giggle', 'secret'] },
  { emoji: '🤫', name: 'shushing face', category: 'smileys', keywords: ['quiet', 'shh', 'hush', 'secret'] },
  { emoji: '🤔', name: 'thinking face', category: 'smileys', keywords: ['think', 'ponder', 'hmm', 'curious'] },
  { emoji: '🤐', name: 'zipper-mouth face', category: 'smileys', keywords: ['zip', 'secret', 'silent'] },
  { emoji: '🤨', name: 'face with raised eyebrow', category: 'smileys', keywords: ['skeptical', 'doubt', 'suspicious'] },
  { emoji: '😐', name: 'neutral face', category: 'smileys', keywords: ['neutral', 'meh', 'blank'] },
  { emoji: '😑', name: 'expressionless face', category: 'smileys', keywords: ['unmoved', 'blank', 'flat'] },
  { emoji: '😶', name: 'face without mouth', category: 'smileys', keywords: ['quiet', 'speechless', 'silent'] },
  { emoji: '😏', name: 'smirking face', category: 'smileys', keywords: ['smirk', 'flirt', 'cool'] },
  { emoji: '😒', name: 'unamused face', category: 'smileys', keywords: ['annoyed', 'grumpy', 'meh'] },
  { emoji: '🙄', name: 'face with rolling eyes', category: 'smileys', keywords: ['eyeroll', 'whatever', 'frustrated'] },
  { emoji: '😬', name: 'grimacing face', category: 'smileys', keywords: ['grimace', 'awkward', 'yikes', 'ouch'] },
  { emoji: '🤥', name: 'lying face', category: 'smileys', keywords: ['lie', 'pinocchio', 'fake'] },
  { emoji: '😌', name: 'relieved face', category: 'smileys', keywords: ['relief', 'calm', 'peace'] },
  { emoji: '😔', name: 'pensive face', category: 'smileys', keywords: ['sad', 'down', 'reflective'] },
  { emoji: '😪', name: 'sleepy face', category: 'smileys', keywords: ['tired', 'sleep', 'rest'] },
  { emoji: '🤤', name: 'drooling face', category: 'smileys', keywords: ['drool', 'craving', 'hungry'] },
  { emoji: '😴', name: 'sleeping face', category: 'smileys', keywords: ['sleep', 'zzz', 'night'] },
  { emoji: '😷', name: 'face with medical mask', category: 'smileys', keywords: ['sick', 'mask', 'virus'] },
  { emoji: '🤒', name: 'face with thermometer', category: 'smileys', keywords: ['sick', 'fever', 'ill'] },
  { emoji: '🤕', name: 'face with head-bandage', category: 'smileys', keywords: ['hurt', 'bandage', 'injured'] },
  { emoji: '🤢', name: 'nauseated face', category: 'smileys', keywords: ['sick', 'gross', 'green', 'disgust'] },
  { emoji: '🤮', name: 'face vomiting', category: 'smileys', keywords: ['puke', 'sick', 'throwup'] },
  { emoji: '🤧', name: 'sneezing face', category: 'smileys', keywords: ['sneeze', 'tissue', 'cold'] },
  { emoji: '🥵', name: 'hot face', category: 'smileys', keywords: ['heat', 'sweat', 'summer', 'spicy'] },
  { emoji: '🥶', name: 'cold face', category: 'smileys', keywords: ['freeze', 'ice', 'winter', 'chilly'] },
  { emoji: '🥴', name: 'woozy face', category: 'smileys', keywords: ['dizzy', 'drunk', 'confused'] },
  { emoji: '😵', name: 'face with crossed-out eyes', category: 'smileys', keywords: ['dizzy', 'dead', 'shock'] },
  { emoji: '🤯', name: 'exploding head', category: 'smileys', keywords: ['mind blown', 'shocked', 'boom'] },
  { emoji: '🤠', name: 'cowboy hat face', category: 'smileys', keywords: ['cowboy', 'hat', 'yeehaw'] },
  { emoji: '🥳', name: 'partying face', category: 'smileys', keywords: ['party', 'celebrate', 'tada', 'birthday'] },
  { emoji: '🥸', name: 'disguised face', category: 'smileys', keywords: ['glasses', 'mustache', 'incognito', 'spy'] },
  { emoji: '😎', name: 'smiling face with sunglasses', category: 'smileys', keywords: ['cool', 'shades', 'slick'] },
  { emoji: '🤓', name: 'nerd face', category: 'smileys', keywords: ['nerd', 'geek', 'glasses', 'smart'] },
  { emoji: '🧐', name: 'face with monocle', category: 'smileys', keywords: ['monocle', 'curious', 'inspect'] },
  { emoji: '😕', name: 'confused face', category: 'smileys', keywords: ['confused', 'puzzled', 'doubt'] },
  { emoji: '😟', name: 'worried face', category: 'smileys', keywords: ['worried', 'nervous', 'anxious'] },
  { emoji: '🙁', name: 'slightly frowning face', category: 'smileys', keywords: ['frown', 'sad'] },
  { emoji: '😮', name: 'face with open mouth', category: 'smileys', keywords: ['surprise', 'gasp', 'wow'] },
  { emoji: '😯', name: 'hushed face', category: 'smileys', keywords: ['speechless', 'quiet', 'surprise'] },
  { emoji: '😲', name: 'astonished face', category: 'smileys', keywords: ['shock', 'amazed', 'gasp'] },
  { emoji: '😳', name: 'flushed face', category: 'smileys', keywords: ['blush', 'shy', 'embarrassed', 'shock'] },
  { emoji: '🥺', name: 'pleading face', category: 'smileys', keywords: ['beg', 'puppy eyes', 'please'] },
  { emoji: '😦', name: 'frowning face with open mouth', category: 'smileys', keywords: ['frown', 'sad'] },
  { emoji: '😧', name: 'anguished face', category: 'smileys', keywords: ['shocked', 'worried'] },
  { emoji: '😨', name: 'fearful face', category: 'smileys', keywords: ['scared', 'afraid', 'panic'] },
  { emoji: '😰', name: 'anxious face with sweat', category: 'smileys', keywords: ['nervous', 'worried'] },
  { emoji: '😥', name: 'sad but relieved face', category: 'smileys', keywords: ['sweat', 'phew'] },
  { emoji: '😢', name: 'crying face', category: 'smileys', keywords: ['tear', 'sad', 'cry'] },
  { emoji: '😭', name: 'loudly crying face', category: 'smileys', keywords: ['sob', 'tears', 'crying'] },
  { emoji: '😱', name: 'face screaming in fear', category: 'smileys', keywords: ['scream', 'scared', 'panic', 'munch'] },
  { emoji: '😖', name: 'confounded face', category: 'smileys', keywords: ['frustrated', 'struggle'] },
  { emoji: '😣', name: 'persevering face', category: 'smileys', keywords: ['hard', 'try', 'struggle'] },
  { emoji: '😞', name: 'disappointed face', category: 'smileys', keywords: ['sad', 'down', 'upset'] },
  { emoji: '😓', name: 'downcast face with sweat', category: 'smileys', keywords: ['tired', 'defeated'] },
  { emoji: '😩', name: 'weary face', category: 'smileys', keywords: ['tired', 'whine', 'upset'] },
  { emoji: '😫', name: 'tired face', category: 'smileys', keywords: ['exhausted', 'yawn'] },
  { emoji: '🥱', name: 'yawning face', category: 'smileys', keywords: ['tired', 'sleepy', 'bored'] },
  { emoji: '😤', name: 'face with steam from nose', category: 'smileys', keywords: ['triumph', 'fume', 'proud'] },
  { emoji: '😡', name: 'enraged face', category: 'smileys', keywords: ['angry', 'mad', 'rage'] },
  { emoji: '😠', name: 'angry face', category: 'smileys', keywords: ['mad', 'annoyed', 'grr'] },
  { emoji: '🤬', name: 'face with symbols on mouth', category: 'smileys', keywords: ['swearing', 'curse', 'rage'] },
  { emoji: '💀', name: 'skull', category: 'smileys', keywords: ['dead', 'skeleton', 'death', 'danger'] },
  { emoji: '☠️', name: 'skull and crossbones', category: 'smileys', keywords: ['danger', 'pirate', 'poison'] },
  { emoji: '💩', name: 'pile of poo', category: 'smileys', keywords: ['poop', 'turd', 'shit'] },
  { emoji: '🤡', name: 'clown face', category: 'smileys', keywords: ['clown', 'circus', 'fool'] },
  { emoji: '👹', name: 'ogre', category: 'smileys', keywords: ['monster', 'mask', 'demon'] },
  { emoji: '👺', name: 'goblin', category: 'smileys', keywords: ['monster', 'mask', 'tengu'] },
  { emoji: '👻', name: 'ghost', category: 'smileys', keywords: ['halloween', 'spooky', 'boo'] },
  { emoji: '👽', name: 'alien', category: 'smileys', keywords: ['ufo', 'extraterrestrial', 'space'] },
  { emoji: '👾', name: 'alien monster', category: 'smileys', keywords: ['game', 'arcade', 'retro', 'invader'] },
  { emoji: '🤖', name: 'robot', category: 'smileys', keywords: ['bot', 'ai', 'machine'] },

  // --- People & Body ---
  { emoji: '👋', name: 'waving hand', category: 'people', keywords: ['wave', 'hello', 'goodbye', 'hi'] },
  { emoji: '🤚', name: 'raised back of hand', category: 'people', keywords: ['backhand', 'stop'] },
  { emoji: '🖐️', name: 'hand with fingers splayed', category: 'people', keywords: ['five', 'hand'] },
  { emoji: '✋', name: 'raised hand', category: 'people', keywords: ['high five', 'stop', 'halt'] },
  { emoji: '🖖', name: 'vulcan salute', category: 'people', keywords: ['spock', 'star trek', 'peace'] },
  { emoji: '👌', name: 'OK hand', category: 'people', keywords: ['ok', 'perfect', 'fine', 'good'] },
  { emoji: '🤌', name: 'pinched fingers', category: 'people', keywords: ['italian', 'gesture', 'what'] },
  { emoji: '🤏', name: 'pinching hand', category: 'people', keywords: ['tiny', 'small', 'little'] },
  { emoji: '✌️', name: 'victory hand', category: 'people', keywords: ['peace', 'two', 'v'] },
  { emoji: '🤞', name: 'crossed fingers', category: 'people', keywords: ['luck', 'hope', 'wish'] },
  { emoji: '🫰', name: 'hand with index finger and thumb crossed', category: 'people', keywords: ['k-pop', 'finger heart', 'love'] },
  { emoji: '🤟', name: 'love-you gesture', category: 'people', keywords: ['ily', 'love', 'hand'] },
  { emoji: '🤘', name: 'sign of the horns', category: 'people', keywords: ['rock', 'metal', 'horns'] },
  { emoji: '🤙', name: 'call me hand', category: 'people', keywords: ['shaka', 'hang loose', 'phone'] },
  { emoji: '👈', name: 'backhand index pointing left', category: 'people', keywords: ['left', 'point'] },
  { emoji: '👉', name: 'backhand index pointing right', category: 'people', keywords: ['right', 'point'] },
  { emoji: '👆', name: 'backhand index pointing up', category: 'people', keywords: ['up', 'point'] },
  { emoji: '🖕', name: 'middle finger', category: 'people', keywords: ['rude', 'flip'] },
  { emoji: '👇', name: 'backhand index pointing down', category: 'people', keywords: ['down', 'point'] },
  { emoji: '☝️', name: 'index pointing up', category: 'people', keywords: ['point', 'up', 'first'] },
  { emoji: '🫵', name: 'index pointing at the viewer', category: 'people', keywords: ['you', 'recruit'] },
  { emoji: '👍', name: 'thumbs up', category: 'people', keywords: ['like', 'approve', 'yes', 'ok', '+1', 'good'] },
  { emoji: '👎', name: 'thumbs down', category: 'people', keywords: ['dislike', 'no', 'bad', '-1'] },
  { emoji: '✊', name: 'raised fist', category: 'people', keywords: ['fist', 'power', 'solidarity'] },
  { emoji: '👊', name: 'oncoming fist', category: 'people', keywords: ['punch', 'fist bump'] },
  { emoji: '🤛', name: 'left-facing fist', category: 'people', keywords: ['fist bump'] },
  { emoji: '🤜', name: 'right-facing fist', category: 'people', keywords: ['fist bump'] },
  { emoji: '👏', name: 'clapping hands', category: 'people', keywords: ['clap', 'applause', 'bravo', 'kudos'] },
  { emoji: '🙌', name: 'raising hands', category: 'people', keywords: ['hooray', 'celebrate', 'cheer', 'praise'] },
  { emoji: '👐', name: 'open hands', category: 'people', keywords: ['open', 'hug'] },
  { emoji: '🤲', name: 'palms up together', category: 'people', keywords: ['pray', 'offering'] },
  { emoji: '🤝', name: 'handshake', category: 'people', keywords: ['agreement', 'deal', 'partner', 'meet'] },
  { emoji: '🙏', name: 'folded hands', category: 'people', keywords: ['please', 'thank you', 'pray', 'namaste', 'hope'] },
  { emoji: '✍️', name: 'writing hand', category: 'people', keywords: ['write', 'memo', 'author'] },
  { emoji: '💅', name: 'nail polish', category: 'people', keywords: ['care', 'beauty', 'slay'] },
  { emoji: '🤳', name: 'selfie', category: 'people', keywords: ['camera', 'phone', 'photo'] },
  { emoji: '💪', name: 'flexed biceps', category: 'people', keywords: ['muscle', 'strong', 'flex', 'workout'] },
  { emoji: '🦾', name: 'mechanical arm', category: 'people', keywords: ['prosthetic', 'cyborg', 'robot'] },
  { emoji: '🦿', name: 'mechanical leg', category: 'people', keywords: ['prosthetic', 'cyborg', 'robot'] },
  { emoji: '🦵', name: 'leg', category: 'people', keywords: ['kick', 'limb'] },
  { emoji: '🦶', name: 'foot', category: 'people', keywords: ['kick', 'stomp'] },
  { emoji: '👂', name: 'ear', category: 'people', keywords: ['listen', 'hear', 'sound'] },
  { emoji: '👃', name: 'nose', category: 'people', keywords: ['smell', 'sniff'] },
  { emoji: '🧠', name: 'brain', category: 'people', keywords: ['smart', 'intellect', 'mind', 'idea'] },
  { emoji: '🫀', name: 'anatomical heart', category: 'people', keywords: ['organ', 'cardio'] },
  { emoji: '🫁', name: 'lungs', category: 'people', keywords: ['breathe', 'organ'] },
  { emoji: '🦷', name: 'tooth', category: 'people', keywords: ['dentist', 'teeth'] },
  { emoji: '🦴', name: 'bone', category: 'people', keywords: ['skeleton'] },
  { emoji: '👀', name: 'eyes', category: 'people', keywords: ['look', 'see', 'watch', 'peek', 'look here'] },
  { emoji: '👁️', name: 'eye', category: 'people', keywords: ['look', 'vision'] },
  { emoji: '👅', name: 'tongue', category: 'people', keywords: ['taste', 'mouth'] },
  { emoji: '👄', name: 'mouth', category: 'people', keywords: ['lips', 'kiss', 'speak'] },
  { emoji: '👤', name: 'bust in silhouette', category: 'people', keywords: ['user', 'person', 'profile', 'avatar'] },
  { emoji: '👥', name: 'busts in silhouette', category: 'people', keywords: ['users', 'group', 'team', 'people'] },
  { emoji: '🫂', name: 'people hugging', category: 'people', keywords: ['hug', 'care', 'support'] },

  // --- Animals & Nature ---
  { emoji: '🐶', name: 'dog face', category: 'nature', keywords: ['puppy', 'pet', 'bark'] },
  { emoji: '🐱', name: 'cat face', category: 'nature', keywords: ['kitten', 'pet', 'meow'] },
  { emoji: '🐭', name: 'mouse face', category: 'nature', keywords: ['rodent'] },
  { emoji: '🐹', name: 'hamster', category: 'nature', keywords: ['pet'] },
  { emoji: '🐰', name: 'rabbit face', category: 'nature', keywords: ['bunny', 'pet'] },
  { emoji: '🦊', name: 'fox', category: 'nature', keywords: ['wild', 'clever'] },
  { emoji: '🐻', name: 'bear', category: 'nature', keywords: ['wild', 'grizzly'] },
  { emoji: '🐼', name: 'panda', category: 'nature', keywords: ['bamboo', 'bear'] },
  { emoji: '🐨', name: 'koala', category: 'nature', keywords: ['marsupial', 'australia'] },
  { emoji: '🐯', name: 'tiger face', category: 'nature', keywords: ['wild', 'cat', 'stripes'] },
  { emoji: '🦁', name: 'lion', category: 'nature', keywords: ['king', 'wild', 'safari'] },
  { emoji: '🐮', name: 'cow face', category: 'nature', keywords: ['moo', 'farm', 'milk'] },
  { emoji: '🐷', name: 'pig face', category: 'nature', keywords: ['oink', 'farm'] },
  { emoji: '🐸', name: 'frog', category: 'nature', keywords: ['toad', 'amphibian'] },
  { emoji: '🐵', name: 'monkey face', category: 'nature', keywords: ['ape', 'chimp'] },
  { emoji: '🐔', name: 'chicken', category: 'nature', keywords: ['bird', 'cluck', 'farm'] },
  { emoji: '🐧', name: 'penguin', category: 'nature', keywords: ['bird', 'ice', 'antarctica'] },
  { emoji: '🐦', name: 'bird', category: 'nature', keywords: ['tweet', 'fly'] },
  { emoji: '🐤', name: 'baby chick', category: 'nature', keywords: ['bird', 'yellow'] },
  { emoji: '🦆', name: 'duck', category: 'nature', keywords: ['quack', 'bird'] },
  { emoji: '🦅', name: 'eagle', category: 'nature', keywords: ['bird', 'raptor'] },
  { emoji: '🦉', name: 'owl', category: 'nature', keywords: ['bird', 'wise', 'night'] },
  { emoji: '🦇', name: 'bat', category: 'nature', keywords: ['vampire', 'night'] },
  { emoji: '🐺', name: 'wolf', category: 'nature', keywords: ['wild', 'howl'] },
  { emoji: '🐴', name: 'horse face', category: 'nature', keywords: ['pony', 'farm'] },
  { emoji: '🦄', name: 'unicorn', category: 'nature', keywords: ['magic', 'fantasy'] },
  { emoji: '🐝', name: 'honeybee', category: 'nature', keywords: ['bee', 'bug', 'honey', 'buzz'] },
  { emoji: '🐛', name: 'bug', category: 'nature', keywords: ['caterpillar', 'insect'] },
  { emoji: '🦋', name: 'butterfly', category: 'nature', keywords: ['insect', 'wings', 'pretty'] },
  { emoji: '🐌', name: 'snail', category: 'nature', keywords: ['slow', 'shell'] },
  { emoji: '🐞', name: 'lady beetle', category: 'nature', keywords: ['ladybug', 'bug'] },
  { emoji: '🐜', name: 'ant', category: 'nature', keywords: ['insect', 'bug'] },
  { emoji: '🕷️', name: 'spider', category: 'nature', keywords: ['arachnid', 'web', 'spooky'] },
  { emoji: '🐢', name: 'turtle', category: 'nature', keywords: ['slow', 'shell', 'tortoise'] },
  { emoji: '🐍', name: 'snake', category: 'nature', keywords: ['serpent', 'reptile'] },
  { emoji: '🦎', name: 'lizard', category: 'nature', keywords: ['reptile', 'gecko'] },
  { emoji: '🐙', name: 'octopus', category: 'nature', keywords: ['tentacles', 'sea'] },
  { emoji: '🦑', name: 'squid', category: 'nature', keywords: ['sea', 'calamari'] },
  { emoji: '🦐', name: 'shrimp', category: 'nature', keywords: ['seafood'] },
  { emoji: '🦞', name: 'lobster', category: 'nature', keywords: ['seafood', 'claws'] },
  { emoji: '🦀', name: 'crab', category: 'nature', keywords: ['seafood', 'beach'] },
  { emoji: '🐡', name: 'blowfish', category: 'nature', keywords: ['fish', 'ocean'] },
  { emoji: '🐠', name: 'tropical fish', category: 'nature', keywords: ['fish', 'ocean', 'swim'] },
  { emoji: '🐟', name: 'fish', category: 'nature', keywords: ['swim', 'ocean'] },
  { emoji: '🐬', name: 'dolphin', category: 'nature', keywords: ['ocean', 'swim', 'smart'] },
  { emoji: '🐳', name: 'spouting whale', category: 'nature', keywords: ['whale', 'ocean'] },
  { emoji: '🦈', name: 'shark', category: 'nature', keywords: ['ocean', 'jaw', 'danger'] },
  { emoji: '🐊', name: 'crocodile', category: 'nature', keywords: ['alligator', 'reptile'] },
  { emoji: '🐅', name: 'tiger', category: 'nature', keywords: ['wild', 'safari'] },
  { emoji: '🐆', name: 'leopard', category: 'nature', keywords: ['wild', 'spots'] },
  { emoji: '🦓', name: 'zebra', category: 'nature', keywords: ['stripes', 'safari'] },
  { emoji: '🦍', name: 'gorilla', category: 'nature', keywords: ['ape', 'wild'] },
  { emoji: '🐘', name: 'elephant', category: 'nature', keywords: ['trunk', 'safari', 'big'] },
  { emoji: '🦛', name: 'hippopotamus', category: 'nature', keywords: ['hippo'] },
  { emoji: '🦏', name: 'rhinoceros', category: 'nature', keywords: ['rhino'] },
  { emoji: '🐪', name: 'camel', category: 'nature', keywords: ['desert', 'hump'] },
  { emoji: '🦒', name: 'giraffe', category: 'nature', keywords: ['tall', 'safari'] },
  { emoji: '🦘', name: 'kangaroo', category: 'nature', keywords: ['australia', 'hop'] },
  { emoji: '🌲', name: 'evergreen tree', category: 'nature', keywords: ['pine', 'forest', 'wood'] },
  { emoji: '🌳', name: 'deciduous tree', category: 'nature', keywords: ['tree', 'nature', 'park'] },
  { emoji: '🌴', name: 'palm tree', category: 'nature', keywords: ['beach', 'tropical', 'summer'] },
  { emoji: '🌵', name: 'cactus', category: 'nature', keywords: ['desert', 'plant'] },
  { emoji: '🌾', name: 'sheaf of rice', category: 'nature', keywords: ['grain', 'wheat', 'harvest'] },
  { emoji: '🌿', name: 'herb', category: 'nature', keywords: ['plant', 'leaf', 'green'] },
  { emoji: '☘️', name: 'shamrock', category: 'nature', keywords: ['plant', 'irish', 'luck'] },
  { emoji: '🍀', name: 'four leaf clover', category: 'nature', keywords: ['luck', 'irish', 'lucky'] },
  { emoji: '🍁', name: 'maple leaf', category: 'nature', keywords: ['autumn', 'fall', 'canada'] },
  { emoji: '🍂', name: 'fallen leaf', category: 'nature', keywords: ['autumn', 'fall', 'season'] },
  { emoji: '🍃', name: 'leaf fluttering in wind', category: 'nature', keywords: ['breeze', 'green', 'leaf'] },
  { emoji: '🍄', name: 'mushroom', category: 'nature', keywords: ['fungus', 'toadstool'] },
  { emoji: '🌸', name: 'cherry blossom', category: 'nature', keywords: ['flower', 'pink', 'spring', 'sakura'] },
  { emoji: '🌹', name: 'rose', category: 'nature', keywords: ['flower', 'red', 'love'] },
  { emoji: '🌺', name: 'hibiscus', category: 'nature', keywords: ['flower', 'tropical'] },
  { emoji: '🌻', name: 'sunflower', category: 'nature', keywords: ['flower', 'yellow', 'summer'] },
  { emoji: '🌼', name: 'blossom', category: 'nature', keywords: ['flower', 'yellow'] },
  { emoji: '🌷', name: 'tulip', category: 'nature', keywords: ['flower', 'spring'] },
  { emoji: '🌱', name: 'seedling', category: 'nature', keywords: ['sprout', 'growth', 'young', 'plant'] },
  { emoji: '🪴', name: 'potted plant', category: 'nature', keywords: ['houseplant', 'greenery'] },
  { emoji: '☀️', name: 'sun', category: 'nature', keywords: ['sunny', 'bright', 'weather', 'warm'] },
  { emoji: '🌤️', name: 'sun behind small cloud', category: 'nature', keywords: ['weather', 'partly cloudy'] },
  { emoji: '⛅', name: 'sun behind cloud', category: 'nature', keywords: ['weather', 'cloudy'] },
  { emoji: '☁️', name: 'cloud', category: 'nature', keywords: ['weather', 'overcast'] },
  { emoji: '🌧️', name: 'cloud with rain', category: 'nature', keywords: ['weather', 'rainy', 'shower'] },
  { emoji: '⛈️', name: 'cloud with lightning and rain', category: 'nature', keywords: ['storm', 'thunder'] },
  { emoji: '🌩️', name: 'cloud with lightning', category: 'nature', keywords: ['thunder', 'lightning'] },
  { emoji: '⚡', name: 'high voltage', category: 'nature', keywords: ['lightning', 'zap', 'electric', 'power', 'fast'] },
  { emoji: '🔥', name: 'fire', category: 'nature', keywords: ['flame', 'hot', 'lit', 'burn', 'trending'] },
  { emoji: '✨', name: 'sparkles', category: 'nature', keywords: ['magic', 'shine', 'clean', 'star', 'new', 'ai'] },
  { emoji: '❄️', name: 'snowflake', category: 'nature', keywords: ['cold', 'snow', 'winter', 'freeze'] },
  { emoji: '☃️', name: 'snowman', category: 'nature', keywords: ['winter', 'snow'] },
  { emoji: '💨', name: 'dashing away', category: 'nature', keywords: ['wind', 'fast', 'blow', 'run'] },
  { emoji: '💧', name: 'droplet', category: 'nature', keywords: ['water', 'drop', 'sweat'] },
  { emoji: '💦', name: 'sweat droplets', category: 'nature', keywords: ['water', 'splash', 'sweat'] },
  { emoji: '🌊', name: 'water wave', category: 'nature', keywords: ['ocean', 'sea', 'surf', 'tsunami'] },
  { emoji: '🌈', name: 'rainbow', category: 'nature', keywords: ['color', 'pride', 'weather'] },
  { emoji: '⭐', name: 'star', category: 'nature', keywords: ['favorite', 'rate', 'night', 'gold', 'shine'] },
  { emoji: '🌟', name: 'glowing star', category: 'nature', keywords: ['sparkle', 'shine', 'glow'] },

  // --- Food & Drink ---
  { emoji: '🍏', name: 'green apple', category: 'food', keywords: ['fruit', 'healthy'] },
  { emoji: '🍎', name: 'red apple', category: 'food', keywords: ['fruit', 'healthy'] },
  { emoji: '🍐', name: 'pear', category: 'food', keywords: ['fruit'] },
  { emoji: '🍊', name: 'tangerine', category: 'food', keywords: ['orange', 'citrus', 'fruit'] },
  { emoji: '🍋', name: 'lemon', category: 'food', keywords: ['citrus', 'sour', 'fruit'] },
  { emoji: '🍌', name: 'banana', category: 'food', keywords: ['fruit', 'yellow'] },
  { emoji: '🍉', name: 'watermelon', category: 'food', keywords: ['fruit', 'summer', 'melon'] },
  { emoji: '🍇', name: 'grapes', category: 'food', keywords: ['fruit', 'wine'] },
  { emoji: '🍓', name: 'strawberry', category: 'food', keywords: ['fruit', 'berry'] },
  { emoji: '🫐', name: 'blueberries', category: 'food', keywords: ['fruit', 'berry'] },
  { emoji: '🍒', name: 'cherries', category: 'food', keywords: ['fruit', 'cherry'] },
  { emoji: '🍑', name: 'peach', category: 'food', keywords: ['fruit', 'sweet'] },
  { emoji: '🥭', name: 'mango', category: 'food', keywords: ['fruit', 'tropical'] },
  { emoji: '🍍', name: 'pineapple', category: 'food', keywords: ['fruit', 'tropical'] },
  { emoji: '🥥', name: 'coconut', category: 'food', keywords: ['fruit', 'tropical'] },
  { emoji: '🥝', name: 'kiwi fruit', category: 'food', keywords: ['fruit'] },
  { emoji: '🍅', name: 'tomato', category: 'food', keywords: ['vegetable', 'red'] },
  { emoji: '🥑', name: 'avocado', category: 'food', keywords: ['fruit', 'guacamole'] },
  { emoji: '🥦', name: 'broccoli', category: 'food', keywords: ['vegetable', 'green'] },
  { emoji: '🌶️', name: 'hot pepper', category: 'food', keywords: ['spicy', 'chili', 'hot'] },
  { emoji: '🌽', name: 'ear of corn', category: 'food', keywords: ['vegetable', 'maize'] },
  { emoji: '🥕', name: 'carrot', category: 'food', keywords: ['vegetable', 'orange'] },
  { emoji: '🥐', name: 'croissant', category: 'food', keywords: ['bread', 'pastry', 'breakfast'] },
  { emoji: '🍞', name: 'bread', category: 'food', keywords: ['toast', 'bakery', 'loaf'] },
  { emoji: '🥨', name: 'pretzel', category: 'food', keywords: ['snack', 'bavarian'] },
  { emoji: '🧀', name: 'cheese wedge', category: 'food', keywords: ['cheese', 'dairy'] },
  { emoji: '🍳', name: 'cooking', category: 'food', keywords: ['egg', 'breakfast', 'fry'] },
  { emoji: '🥓', name: 'bacon', category: 'food', keywords: ['meat', 'breakfast', 'pork'] },
  { emoji: '🥩', name: 'cut of meat', category: 'food', keywords: ['steak', 'beef'] },
  { emoji: '🍗', name: 'poultry leg', category: 'food', keywords: ['chicken', 'drumstick'] },
  { emoji: '🍖', name: 'meat on bone', category: 'food', keywords: ['meat'] },
  { emoji: '🌭', name: 'hot dog', category: 'food', keywords: ['frankfurter', 'sausage'] },
  { emoji: '🍔', name: 'hamburger', category: 'food', keywords: ['burger', 'fast food'] },
  { emoji: '🍟', name: 'french fries', category: 'food', keywords: ['chips', 'fast food'] },
  { emoji: '🍕', name: 'pizza', category: 'food', keywords: ['slice', 'cheese', 'pie'] },
  { emoji: '🥪', name: 'sandwich', category: 'food', keywords: ['bread', 'lunch'] },
  { emoji: '🌮', name: 'taco', category: 'food', keywords: ['mexican'] },
  { emoji: '🌯', name: 'burrito', category: 'food', keywords: ['mexican', 'wrap'] },
  { emoji: '🥗', name: 'green salad', category: 'food', keywords: ['healthy', 'veggie'] },
  { emoji: '🍝', name: 'spaghetti', category: 'food', keywords: ['pasta', 'noodle', 'italian'] },
  { emoji: '🍜', name: 'steaming bowl', category: 'food', keywords: ['ramen', 'noodle', 'soup'] },
  { emoji: '🍲', name: 'pot of food', category: 'food', keywords: ['stew', 'soup'] },
  { emoji: '🍛', name: 'curry rice', category: 'food', keywords: ['curry', 'indian'] },
  { emoji: '🍣', name: 'sushi', category: 'food', keywords: ['japanese', 'fish', 'rice'] },
  { emoji: '🍱', name: 'bento box', category: 'food', keywords: ['japanese', 'lunch'] },
  { emoji: '🥟', name: 'dumpling', category: 'food', keywords: ['dim sum', 'gyoza', 'pierogi'] },
  { emoji: '🍤', name: 'fried shrimp', category: 'food', keywords: ['tempura', 'seafood'] },
  { emoji: '🍙', name: 'rice ball', category: 'food', keywords: ['onigiri', 'japanese'] },
  { emoji: '🍚', name: 'cooked rice', category: 'food', keywords: ['bowl', 'grain'] },
  { emoji: '🍦', name: 'soft ice cream', category: 'food', keywords: ['dessert', 'sweet'] },
  { emoji: '🍧', name: 'shaved ice', category: 'food', keywords: ['dessert', 'sweet'] },
  { emoji: '🍨', name: 'ice cream', category: 'food', keywords: ['dessert', 'sweet'] },
  { emoji: '🍩', name: 'doughnut', category: 'food', keywords: ['donut', 'sweet', 'pastry'] },
  { emoji: '🍪', name: 'cookie', category: 'food', keywords: ['biscuit', 'chocolate chip', 'sweet'] },
  { emoji: '🎂', name: 'birthday cake', category: 'food', keywords: ['celebration', 'party', 'sweet'] },
  { emoji: '🍰', name: 'shortcake', category: 'food', keywords: ['cake', 'slice', 'dessert'] },
  { emoji: '🧁', name: 'cupcake', category: 'food', keywords: ['sweet', 'frosting'] },
  { emoji: '🥧', name: 'pie', category: 'food', keywords: ['dessert', 'pastry'] },
  { emoji: '🍫', name: 'chocolate bar', category: 'food', keywords: ['candy', 'sweet'] },
  { emoji: '🍬', name: 'candy', category: 'food', keywords: ['sweet', 'lolly'] },
  { emoji: '🍭', name: 'lollipop', category: 'food', keywords: ['candy', 'sweet'] },
  { emoji: '🍿', name: 'popcorn', category: 'food', keywords: ['movie', 'cinema', 'snack'] },
  { emoji: '🥛', name: 'glass of milk', category: 'food', keywords: ['dairy', 'drink'] },
  { emoji: '☕', name: 'hot beverage', category: 'food', keywords: ['coffee', 'tea', 'cafe', 'espresso'] },
  { emoji: '🫖', name: 'teapot', category: 'food', keywords: ['tea', 'pot'] },
  { emoji: '🍵', name: 'teacup without handle', category: 'food', keywords: ['green tea', 'matcha'] },
  { emoji: '🧃', name: 'beverage box', category: 'food', keywords: ['juice', 'box'] },
  { emoji: '🥤', name: 'cup with straw', category: 'food', keywords: ['soda', 'drink'] },
  { emoji: '🧋', name: 'bubble tea', category: 'food', keywords: ['boba', 'tea'] },
  { emoji: '🍺', name: 'beer mug', category: 'food', keywords: ['drink', 'pub', 'alcohol'] },
  { emoji: '🍻', name: 'clinking beer mugs', category: 'food', keywords: ['cheers', 'drink', 'toast'] },
  { emoji: '🥂', name: 'clinking glasses', category: 'food', keywords: ['champagne', 'celebrate', 'toast'] },
  { emoji: '🍷', name: 'wine glass', category: 'food', keywords: ['wine', 'alcohol', 'red'] },
  { emoji: '🍸', name: 'cocktail glass', category: 'food', keywords: ['martini', 'drink'] },
  { emoji: '🍹', name: 'tropical drink', category: 'food', keywords: ['cocktail', 'vacation'] },
  { emoji: '🍾', name: 'bottle with popping cork', category: 'food', keywords: ['champagne', 'celebrate'] },

  // --- Activity & Sports ---
  { emoji: '⚽', name: 'soccer ball', category: 'activity', keywords: ['football', 'sport'] },
  { emoji: '🏀', name: 'basketball', category: 'activity', keywords: ['ball', 'sport', 'nba'] },
  { emoji: '🏈', name: 'american football', category: 'activity', keywords: ['nfl', 'sport'] },
  { emoji: '⚾', name: 'baseball', category: 'activity', keywords: ['sport', 'mlb'] },
  { emoji: '🥎', name: 'softball', category: 'activity', keywords: ['ball', 'sport'] },
  { emoji: '🎾', name: 'tennis', category: 'activity', keywords: ['ball', 'sport', 'racket'] },
  { emoji: '🏐', name: 'volleyball', category: 'activity', keywords: ['ball', 'sport'] },
  { emoji: '🏉', name: 'rugby football', category: 'activity', keywords: ['ball', 'sport'] },
  { emoji: '🥏', name: 'flying disc', category: 'activity', keywords: ['frisbee', 'ultimate'] },
  { emoji: '🎱', name: 'pool 8 ball', category: 'activity', keywords: ['billiards', 'game'] },
  { emoji: '🏓', name: 'ping pong', category: 'activity', keywords: ['table tennis', 'paddle'] },
  { emoji: '🏸', name: 'badminton', category: 'activity', keywords: ['shuttlecock', 'racket'] },
  { emoji: '🏒', name: 'ice hockey', category: 'activity', keywords: ['puck', 'stick'] },
  { emoji: '🥊', name: 'boxing glove', category: 'activity', keywords: ['fight', 'sport'] },
  { emoji: '🥋', name: 'martial arts uniform', category: 'activity', keywords: ['karate', 'judo', 'taekwondo'] },
  { emoji: '🛹', name: 'skateboard', category: 'activity', keywords: ['skate', 'board'] },
  { emoji: '🛼', name: 'roller skate', category: 'activity', keywords: ['skating'] },
  { emoji: '🎿', name: 'skis', category: 'activity', keywords: ['skiing', 'snow', 'winter'] },
  { emoji: '🏂', name: 'snowboarder', category: 'activity', keywords: ['snow', 'winter', 'sport'] },
  { emoji: '🏋️', name: 'person lifting weights', category: 'activity', keywords: ['gym', 'workout', 'fitness', 'strong'] },
  { emoji: '🧘', name: 'person in lotus position', category: 'activity', keywords: ['yoga', 'meditate', 'zen', 'calm'] },
  { emoji: '🏄', name: 'person surfing', category: 'activity', keywords: ['surf', 'wave', 'ocean'] },
  { emoji: '🏊', name: 'person swimming', category: 'activity', keywords: ['swim', 'pool', 'water'] },
  { emoji: '🧗', name: 'person climbing', category: 'activity', keywords: ['climb', 'rock', 'mountain'] },
  { emoji: '🚴', name: 'person biking', category: 'activity', keywords: ['bicycle', 'cycle', 'cycling'] },
  { emoji: '🏆', name: 'trophy', category: 'activity', keywords: ['award', 'winner', 'first', 'champion', 'prize'] },
  { emoji: '🥇', name: '1st place medal', category: 'activity', keywords: ['gold', 'winner', 'first'] },
  { emoji: '🥈', name: '2nd place medal', category: 'activity', keywords: ['silver', 'second'] },
  { emoji: '🥉', name: '3rd place medal', category: 'activity', keywords: ['bronze', 'third'] },
  { emoji: '🏅', name: 'sports medal', category: 'activity', keywords: ['award', 'medal'] },
  { emoji: '🎖️', name: 'military medal', category: 'activity', keywords: ['honor', 'award'] },
  { emoji: '🎫', name: 'ticket', category: 'activity', keywords: ['admission', 'event', 'pass'] },
  { emoji: '🎟️', name: 'admission tickets', category: 'activity', keywords: ['movie', 'raffle'] },
  { emoji: '🎪', name: 'circus tent', category: 'activity', keywords: ['carnival', 'fair'] },
  { emoji: '🎭', name: 'performing arts', category: 'activity', keywords: ['theater', 'drama', 'masks'] },
  { emoji: '🎨', name: 'artist palette', category: 'activity', keywords: ['art', 'paint', 'draw', 'design', 'color'] },
  { emoji: '🎬', name: 'clapper board', category: 'activity', keywords: ['movie', 'film', 'cinema', 'video'] },
  { emoji: '🎤', name: 'microphone', category: 'activity', keywords: ['sing', 'karaoke', 'voice', 'audio'] },
  { emoji: '🎧', name: 'headphone', category: 'activity', keywords: ['music', 'audio', 'listen', 'sound'] },
  { emoji: '🎼', name: 'musical score', category: 'activity', keywords: ['music', 'clef', 'notes'] },
  { emoji: '🎹', name: 'musical keyboard', category: 'activity', keywords: ['piano', 'music', 'instrument'] },
  { emoji: '🥁', name: 'drum', category: 'activity', keywords: ['music', 'percussion'] },
  { emoji: '🎷', name: 'saxophone', category: 'activity', keywords: ['music', 'jazz'] },
  { emoji: '🎺', name: 'trumpet', category: 'activity', keywords: ['music', 'brass'] },
  { emoji: '🎸', name: 'guitar', category: 'activity', keywords: ['music', 'rock', 'instrument'] },
  { emoji: '🎻', name: 'violin', category: 'activity', keywords: ['music', 'classical'] },
  { emoji: '🎲', name: 'game die', category: 'activity', keywords: ['dice', 'random', 'chance', 'board game'] },
  { emoji: '♟️', name: 'chess pawn', category: 'activity', keywords: ['chess', 'game', 'strategy'] },
  { emoji: '🎯', name: 'bullseye', category: 'activity', keywords: ['target', 'hit', 'goal', 'accurate', 'direct'] },
  { emoji: '🎳', name: 'bowling', category: 'activity', keywords: ['pins', 'strike'] },
  { emoji: '🎮', name: 'video game', category: 'activity', keywords: ['controller', 'gaming', 'play'] },
  { emoji: '🎰', name: 'slot machine', category: 'activity', keywords: ['casino', 'gamble', '777'] },
  { emoji: '🧩', name: 'puzzle piece', category: 'activity', keywords: ['jigsaw', 'match', 'solve', 'problem'] },

  // --- Travel & Places ---
  { emoji: '🚗', name: 'automobile', category: 'travel', keywords: ['car', 'drive', 'vehicle'] },
  { emoji: '🚕', name: 'taxi', category: 'travel', keywords: ['cab', 'uber', 'drive'] },
  { emoji: '🚙', name: 'sport utility vehicle', category: 'travel', keywords: ['suv', 'car'] },
  { emoji: '🚌', name: 'bus', category: 'travel', keywords: ['transit', 'transport'] },
  { emoji: '🏎️', name: 'racing car', category: 'travel', keywords: ['f1', 'fast', 'race'] },
  { emoji: '🚓', name: 'police car', category: 'travel', keywords: ['cop', 'emergency'] },
  { emoji: '🚑', name: 'ambulance', category: 'travel', keywords: ['hospital', 'emergency', 'medic'] },
  { emoji: '🚒', name: 'fire engine', category: 'travel', keywords: ['firefighter', 'truck'] },
  { emoji: '🚚', name: 'delivery truck', category: 'travel', keywords: ['lorry', 'shipping', 'box'] },
  { emoji: '🚜', name: 'tractor', category: 'travel', keywords: ['farm', 'agriculture'] },
  { emoji: '🛴', name: 'kick scooter', category: 'travel', keywords: ['ride'] },
  { emoji: '🚲', name: 'bicycle', category: 'travel', keywords: ['bike', 'cycle'] },
  { emoji: '🛵', name: 'motor scooter', category: 'travel', keywords: ['vespa', 'moped'] },
  { emoji: '🏍️', name: 'motorcycle', category: 'travel', keywords: ['bike', 'speed'] },
  { emoji: '🚨', name: 'police car light', category: 'travel', keywords: ['siren', 'alert', 'emergency', 'warning'] },
  { emoji: '🚡', name: 'aerial tramway', category: 'travel', keywords: ['cable car', 'ski'] },
  { emoji: '🚠', name: 'mountain cableway', category: 'travel', keywords: ['gondola', 'mountain'] },
  { emoji: '🚂', name: 'locomotive', category: 'travel', keywords: ['train', 'rail', 'steam'] },
  { emoji: '🚆', name: 'train', category: 'travel', keywords: ['railway', 'transit'] },
  { emoji: '🚇', name: 'metro', category: 'travel', keywords: ['subway', 'underground', 'tube'] },
  { emoji: '✈️', name: 'airplane', category: 'travel', keywords: ['flight', 'fly', 'travel', 'airport'] },
  { emoji: '🛫', name: 'airplane departure', category: 'travel', keywords: ['takeoff', 'flight'] },
  { emoji: '🛬', name: 'airplane arrival', category: 'travel', keywords: ['landing', 'flight'] },
  { emoji: '🛰️', name: 'satellite', category: 'travel', keywords: ['space', 'orbit', 'tech'] },
  { emoji: '🚀', name: 'rocket', category: 'travel', keywords: ['launch', 'ship', 'space', 'blast', 'fast', 'deploy'] },
  { emoji: '🛸', name: 'flying saucer', category: 'travel', keywords: ['ufo', 'alien', 'space'] },
  { emoji: '🚁', name: 'helicopter', category: 'travel', keywords: ['chopper', 'flight'] },
  { emoji: '🛶', name: 'canoe', category: 'travel', keywords: ['boat', 'kayak', 'paddle'] },
  { emoji: '⛵', name: 'sailboat', category: 'travel', keywords: ['boat', 'sailing', 'sea'] },
  { emoji: '🚤', name: 'speedboat', category: 'travel', keywords: ['boat', 'fast'] },
  { emoji: '🛳️', name: 'passenger ship', category: 'travel', keywords: ['cruise', 'boat'] },
  { emoji: '⚓', name: 'anchor', category: 'travel', keywords: ['ship', 'boat', 'nautical', 'port'] },
  { emoji: '🚧', name: 'construction', category: 'travel', keywords: ['barrier', 'warning', 'work', 'wip'] },
  { emoji: '🚦', name: 'vertical traffic light', category: 'travel', keywords: ['stop', 'go', 'signal'] },
  { emoji: '🗺️', name: 'world map', category: 'travel', keywords: ['location', 'geography', 'travel', 'atlas'] },
  { emoji: '🗿', name: 'moai', category: 'travel', keywords: ['statue', 'easter island', 'stone'] },
  { emoji: '🗽', name: 'Statue of Liberty', category: 'travel', keywords: ['nyc', 'usa', 'landmark'] },
  { emoji: '🗼', name: 'Tokyo tower', category: 'travel', keywords: ['japan', 'tower'] },
  { emoji: '🏰', name: 'castle', category: 'travel', keywords: ['fortress', 'fairy tale'] },
  { emoji: '🏟️', name: 'stadium', category: 'travel', keywords: ['arena', 'sports'] },
  { emoji: '🏖️', name: 'beach with umbrella', category: 'travel', keywords: ['vacation', 'summer', 'sand'] },
  { emoji: '🏝️', name: 'desert island', category: 'travel', keywords: ['island', 'tropical'] },
  { emoji: '🌋', name: 'volcano', category: 'travel', keywords: ['lava', 'eruption'] },
  { emoji: '⛰️', name: 'mountain', category: 'travel', keywords: ['hiking', 'peak', 'nature'] },
  { emoji: '🏔️', name: 'snow-capped mountain', category: 'travel', keywords: ['alps', 'snow', 'peak'] },
  { emoji: '🏕️', name: 'camping', category: 'travel', keywords: ['camp', 'tent', 'outdoors'] },
  { emoji: '⛺', name: 'tent', category: 'travel', keywords: ['camp', 'shelter'] },
  { emoji: '🏠', name: 'house', category: 'travel', keywords: ['home', 'building'] },
  { emoji: '🏡', name: 'house with garden', category: 'travel', keywords: ['home', 'yard'] },
  { emoji: '🏢', name: 'office building', category: 'travel', keywords: ['work', 'business', 'company'] },
  { emoji: '🏛️', name: 'classical building', category: 'travel', keywords: ['museum', 'bank', 'government', 'monument'] },
  { emoji: '🏙️', name: 'cityscape', category: 'travel', keywords: ['city', 'buildings', 'skyline'] },
  { emoji: '🌆', name: 'cityscape at dusk', category: 'travel', keywords: ['sunset', 'city', 'evening'] },
  { emoji: '🌇', name: 'sunset', category: 'travel', keywords: ['evening', 'sun', 'sky'] },

  // --- Objects & Tech ---
  { emoji: '💡', name: 'light bulb', category: 'objects', keywords: ['idea', 'bright', 'tip', 'insight', 'smart'] },
  { emoji: '🔦', name: 'flashlight', category: 'objects', keywords: ['torch', 'light'] },
  { emoji: '📦', name: 'package', category: 'objects', keywords: ['box', 'parcel', 'delivery', 'cargo'] },
  { emoji: '📝', name: 'memo', category: 'objects', keywords: ['write', 'note', 'document', 'paper', 'text'] },
  { emoji: '📄', name: 'page facing up', category: 'objects', keywords: ['document', 'sheet', 'file'] },
  { emoji: '📃', name: 'page with curl', category: 'objects', keywords: ['document', 'scroll'] },
  { emoji: '📑', name: 'bookmark tabs', category: 'objects', keywords: ['markers', 'index', 'tabs'] },
  { emoji: '📊', name: 'bar chart', category: 'objects', keywords: ['graph', 'analytics', 'data', 'metrics', 'stats'] },
  { emoji: '📈', name: 'chart increasing', category: 'objects', keywords: ['graph', 'growth', 'trending up', 'success', 'kpi'] },
  { emoji: '📉', name: 'chart decreasing', category: 'objects', keywords: ['graph', 'down', 'loss', 'decline'] },
  { emoji: '📜', name: 'scroll', category: 'objects', keywords: ['ancient', 'parchment', 'paper'] },
  { emoji: '📋', name: 'clipboard', category: 'objects', keywords: ['tasks', 'checklist', 'board', 'paste'] },
  { emoji: '📁', name: 'file folder', category: 'objects', keywords: ['directory', 'files', 'storage'] },
  { emoji: '📂', name: 'open file folder', category: 'objects', keywords: ['directory', 'load'] },
  { emoji: '🗂️', name: 'card index dividers', category: 'objects', keywords: ['organization', 'sort'] },
  { emoji: '📅', name: 'calendar', category: 'objects', keywords: ['date', 'schedule', 'planner', 'month'] },
  { emoji: '📆', name: 'tear-off calendar', category: 'objects', keywords: ['date', 'day'] },
  { emoji: '🏷️', name: 'label', category: 'objects', keywords: ['tag', 'price', 'category'] },
  { emoji: '📌', name: 'pushpin', category: 'objects', keywords: ['pin', 'note', 'board', 'sticky', 'point'] },
  { emoji: '📍', name: 'round pushpin', category: 'objects', keywords: ['location', 'map', 'pin', 'marker'] },
  { emoji: '📎', name: 'paperclip', category: 'objects', keywords: ['attachment', 'attach', 'file', 'clip'] },
  { emoji: '🖇️', name: 'linked paperclips', category: 'objects', keywords: ['links', 'attachments'] },
  { emoji: '📏', name: 'straight ruler', category: 'objects', keywords: ['measure', 'length'] },
  { emoji: '📐', name: 'triangular ruler', category: 'objects', keywords: ['math', 'architect', 'geometry'] },
  { emoji: '✂️', name: 'scissors', category: 'objects', keywords: ['cut', 'snip', 'tool'] },
  { emoji: '🗑️', name: 'wastebasket', category: 'objects', keywords: ['trash', 'delete', 'remove', 'bin', 'garbage'] },
  { emoji: '🔒', name: 'locked', category: 'objects', keywords: ['lock', 'security', 'secure', 'private', 'safe'] },
  { emoji: '🔓', name: 'unlocked', category: 'objects', keywords: ['unlock', 'open', 'access'] },
  { emoji: '🔏', name: 'locked with pen', category: 'objects', keywords: ['security', 'signature', 'sign'] },
  { emoji: '🔐', name: 'locked with key', category: 'objects', keywords: ['secure', 'privacy'] },
  { emoji: '🔑', name: 'key', category: 'objects', keywords: ['password', 'auth', 'access', 'secret'] },
  { emoji: '🗝️', name: 'old key', category: 'objects', keywords: ['vintage', 'clue'] },
  { emoji: '🔨', name: 'hammer', category: 'objects', keywords: ['tool', 'build', 'fix'] },
  { emoji: '🪓', name: 'axe', category: 'objects', keywords: ['wood', 'chop', 'tool'] },
  { emoji: '⛏️', name: 'pick', category: 'objects', keywords: ['mine', 'dig', 'tool'] },
  { emoji: '🔧', name: 'wrench', category: 'objects', keywords: ['tool', 'settings', 'fix', 'configure', 'repair'] },
  { emoji: '🪛', name: 'screwdriver', category: 'objects', keywords: ['tool', 'fix'] },
  { emoji: '🔩', name: 'nut and bolt', category: 'objects', keywords: ['hardware', 'screw'] },
  { emoji: '⚙️', name: 'gear', category: 'objects', keywords: ['settings', 'config', 'preferences', 'cog', 'system'] },
  { emoji: '⚖️', name: 'balance scale', category: 'objects', keywords: ['justice', 'law', 'legal', 'balance'] },
  { emoji: '🔗', name: 'link', category: 'objects', keywords: ['url', 'href', 'chain', 'connect', 'hyperlink'] },
  { emoji: '⛓️', name: 'chains', category: 'objects', keywords: ['linked', 'lock'] },
  { emoji: '🧰', name: 'toolbox', category: 'objects', keywords: ['tools', 'kit', 'repair'] },
  { emoji: '🧲', name: 'magnet', category: 'objects', keywords: ['attract', 'magnetic'] },
  { emoji: '📱', name: 'mobile phone', category: 'objects', keywords: ['iphone', 'android', 'cell', 'smartphone'] },
  { emoji: '📲', name: 'mobile phone with arrow', category: 'objects', keywords: ['call', 'message', 'receive'] },
  { emoji: '☎️', name: 'telephone', category: 'objects', keywords: ['phone', 'contact'] },
  { emoji: '🔋', name: 'battery', category: 'objects', keywords: ['power', 'energy', 'charge'] },
  { emoji: '🔌', name: 'electric plug', category: 'objects', keywords: ['power', 'connect', 'cable'] },
  { emoji: '💻', name: 'laptop', category: 'objects', keywords: ['computer', 'pc', 'macbook', 'work', 'code'] },
  { emoji: '🖥️', name: 'desktop computer', category: 'objects', keywords: ['screen', 'monitor', 'pc'] },
  { emoji: '🖨️', name: 'printer', category: 'objects', keywords: ['paper', 'print'] },
  { emoji: '⌨️', name: 'keyboard', category: 'objects', keywords: ['type', 'input', 'computer'] },
  { emoji: '🖱️', name: 'computer mouse', category: 'objects', keywords: ['click', 'pointer'] },
  { emoji: '💽', name: 'minidisc', category: 'objects', keywords: ['disk', 'storage'] },
  { emoji: '💾', name: 'floppy disk', category: 'objects', keywords: ['save', 'storage', 'vintage'] },
  { emoji: '💿', name: 'optical disk', category: 'objects', keywords: ['cd', 'dvd'] },
  { emoji: '📀', name: 'dvd', category: 'objects', keywords: ['movie', 'disk'] },
  { emoji: '📷', name: 'camera', category: 'objects', keywords: ['photo', 'picture', 'snapshot'] },
  { emoji: '📸', name: 'camera with flash', category: 'objects', keywords: ['photo', 'flash'] },
  { emoji: '📹', name: 'video camera', category: 'objects', keywords: ['film', 'movie', 'record'] },
  { emoji: '🎥', name: 'movie camera', category: 'objects', keywords: ['cinema', 'film'] },
  { emoji: '📽️', name: 'film projector', category: 'objects', keywords: ['cinema', 'movie'] },
  { emoji: '🔭', name: 'telescope', category: 'objects', keywords: ['space', 'stars', 'astronomy', 'observe'] },
  { emoji: '🔬', name: 'microscope', category: 'objects', keywords: ['science', 'research', 'lab', 'biology'] },
  { emoji: '🔍', name: 'magnifying glass tilted left', category: 'objects', keywords: ['search', 'find', 'explore', 'lookup'] },
  { emoji: '🔎', name: 'magnifying glass tilted right', category: 'objects', keywords: ['search', 'inspect'] },
  { emoji: '🕯️', name: 'candle', category: 'objects', keywords: ['light', 'flame', 'wax'] },
  { emoji: '🧭', name: 'compass', category: 'objects', keywords: ['navigation', 'direction', 'explore'] },
  { emoji: '⏱️', name: 'stopwatch', category: 'objects', keywords: ['timer', 'time', 'fast', 'speed'] },
  { emoji: '⏲️', name: 'timer clock', category: 'objects', keywords: ['kitchen', 'time'] },
  { emoji: '⏰', name: 'alarm clock', category: 'objects', keywords: ['morning', 'wake', 'time', 'alert'] },
  { emoji: '🕰️', name: 'mantelpiece clock', category: 'objects', keywords: ['time', 'vintage'] },
  { emoji: '⌛', name: 'hourglass done', category: 'objects', keywords: ['time', 'sand', 'wait'] },
  { emoji: '⏳', name: 'hourglass not done', category: 'objects', keywords: ['time', 'loading', 'wait', 'progress'] },
  { emoji: '📡', name: 'satellite antenna', category: 'objects', keywords: ['dish', 'signal', 'radar'] },

  // --- Symbols & Signs ---
  { emoji: '❤️', name: 'red heart', category: 'symbols', keywords: ['love', 'like', 'favorite', 'heart'] },
  { emoji: '🧡', name: 'orange heart', category: 'symbols', keywords: ['love', 'like'] },
  { emoji: '💛', name: 'yellow heart', category: 'symbols', keywords: ['love', 'friendship'] },
  { emoji: '💚', name: 'green heart', category: 'symbols', keywords: ['love', 'nature', 'healthy'] },
  { emoji: '💙', name: 'blue heart', category: 'symbols', keywords: ['love', 'trust'] },
  { emoji: '💜', name: 'purple heart', category: 'symbols', keywords: ['love', 'honor'] },
  { emoji: '🖤', name: 'black heart', category: 'symbols', keywords: ['love', 'dark'] },
  { emoji: '🤍', name: 'white heart', category: 'symbols', keywords: ['love', 'pure'] },
  { emoji: '🤎', name: 'brown heart', category: 'symbols', keywords: ['love'] },
  { emoji: '💔', name: 'broken heart', category: 'symbols', keywords: ['sad', 'breakup', 'heartbreak'] },
  { emoji: '❣️', name: 'heart exclamation', category: 'symbols', keywords: ['love', 'attention'] },
  { emoji: '💕', name: 'two hearts', category: 'symbols', keywords: ['love', 'sweet'] },
  { emoji: '💞', name: 'revolving hearts', category: 'symbols', keywords: ['love'] },
  { emoji: '💓', name: 'beating heart', category: 'symbols', keywords: ['heartbeat', 'pulse'] },
  { emoji: '💗', name: 'growing heart', category: 'symbols', keywords: ['love', 'flair'] },
  { emoji: '💖', name: 'sparkling heart', category: 'symbols', keywords: ['love', 'sparkle', 'magic'] },
  { emoji: '💘', name: 'heart with arrow', category: 'symbols', keywords: ['cupid', 'love'] },
  { emoji: '💝', name: 'heart with ribbon', category: 'symbols', keywords: ['gift', 'love'] },
  { emoji: '☮️', name: 'peace symbol', category: 'symbols', keywords: ['peace'] },
  { emoji: '✝️', name: 'latin cross', category: 'symbols', keywords: ['christian', 'religion'] },
  { emoji: '☯️', name: 'yin yang', category: 'symbols', keywords: ['balance', 'taoism'] },
  { emoji: '🆔', name: 'ID button', category: 'symbols', keywords: ['identity', 'identifier'] },
  { emoji: '☢️', name: 'radioactive', category: 'symbols', keywords: ['hazard', 'nuclear'] },
  { emoji: '☣️', name: 'biohazard', category: 'symbols', keywords: ['hazard', 'danger'] },
  { emoji: '❌', name: 'cross mark', category: 'symbols', keywords: ['x', 'no', 'cancel', 'wrong', 'reject', 'delete'] },
  { emoji: '⭕', name: 'hollow red circle', category: 'symbols', keywords: ['circle', 'ring', 'ok'] },
  { emoji: '🛑', name: 'stop sign', category: 'symbols', keywords: ['stop', 'halt', 'octagonal'] },
  { emoji: '⛔', name: 'no entry', category: 'symbols', keywords: ['forbidden', 'denied', 'blocked'] },
  { emoji: '🚫', name: 'prohibited', category: 'symbols', keywords: ['ban', 'no', 'forbidden'] },
  { emoji: '💯', name: 'hundred points', category: 'symbols', keywords: ['100', 'perfect', 'score', 'excellent'] },
  { emoji: '💢', name: 'anger symbol', category: 'symbols', keywords: ['mad', 'anime', 'vein'] },
  { emoji: '❗️', name: 'red exclamation mark', category: 'symbols', keywords: ['attention', 'warning', 'important', 'alert', '!'] },
  { emoji: '❕', name: 'white exclamation mark', category: 'symbols', keywords: ['attention', 'alert'] },
  { emoji: '❓', name: 'red question mark', category: 'symbols', keywords: ['question', 'help', 'what', 'confused', '?'] },
  { emoji: '❔', name: 'white question mark', category: 'symbols', keywords: ['question', 'help'] },
  { emoji: '‼️', name: 'double exclamation mark', category: 'symbols', keywords: ['alert', 'bang', 'warning', '!!'] },
  { emoji: '⁉️', name: 'exclamation question mark', category: 'symbols', keywords: ['interrobang', 'surprise', '!?'] },
  { emoji: '⚠️', name: 'warning', category: 'symbols', keywords: ['alert', 'caution', 'danger', 'risk', 'warn'] },
  { emoji: '🔰', name: 'Japanese symbol for beginner', category: 'symbols', keywords: ['beginner', 'starter', 'greenhorn'] },
  { emoji: '♻️', name: 'recycling symbol', category: 'symbols', keywords: ['recycle', 'green', 'eco'] },
  { emoji: '✅', name: 'check mark button', category: 'symbols', keywords: ['done', 'complete', 'ok', 'yes', 'verified', 'approved', 'pass'] },
  { emoji: '❇️', name: 'sparkle', category: 'symbols', keywords: ['star', 'green'] },
  { emoji: '🌐', name: 'globe with meridians', category: 'symbols', keywords: ['world', 'web', 'internet', 'global', 'i18n'] },
  { emoji: '💤', name: 'zzz', category: 'symbols', keywords: ['sleep', 'tired', 'rest', 'boring'] },
  { emoji: '🏧', name: 'ATM sign', category: 'symbols', keywords: ['bank', 'cash', 'money'] },
  { emoji: '♿', name: 'wheelchair symbol', category: 'symbols', keywords: ['accessibility', 'a11y', 'handicap'] },
  { emoji: '🅿️', name: 'P button', category: 'symbols', keywords: ['parking', 'car'] },
  { emoji: '📶', name: 'antenna bars', category: 'symbols', keywords: ['signal', 'wifi', 'connection'] },
  { emoji: '🆗', name: 'OK button', category: 'symbols', keywords: ['ok', 'agree', 'yes'] },
  { emoji: '🆒', name: 'COOL button', category: 'symbols', keywords: ['cool', 'nice'] },
  { emoji: '🆕', name: 'NEW button', category: 'symbols', keywords: ['new', 'fresh', 'recent'] },
  { emoji: '🆓', name: 'FREE button', category: 'symbols', keywords: ['free', 'zero'] },
  { emoji: '0️⃣', name: 'keycap: 0', category: 'symbols', keywords: ['zero', 'number'] },
  { emoji: '1️⃣', name: 'keycap: 1', category: 'symbols', keywords: ['one', 'number'] },
  { emoji: '2️⃣', name: 'keycap: 2', category: 'symbols', keywords: ['two', 'number'] },
  { emoji: '3️⃣', name: 'keycap: 3', category: 'symbols', keywords: ['three', 'number'] },
  { emoji: '4️⃣', name: 'keycap: 4', category: 'symbols', keywords: ['four', 'number'] },
  { emoji: '5️⃣', name: 'keycap: 5', category: 'symbols', keywords: ['five', 'number'] },
  { emoji: '6️⃣', name: 'keycap: 6', category: 'symbols', keywords: ['six', 'number'] },
  { emoji: '7️⃣', name: 'keycap: 7', category: 'symbols', keywords: ['seven', 'number'] },
  { emoji: '8️⃣', name: 'keycap: 8', category: 'symbols', keywords: ['eight', 'number'] },
  { emoji: '9️⃣', name: 'keycap: 9', category: 'symbols', keywords: ['nine', 'number'] },
  { emoji: '🔟', name: 'keycap: 10', category: 'symbols', keywords: ['ten', 'number'] },
  { emoji: '🔢', name: 'input numbers', category: 'symbols', keywords: ['1234', 'numbers', 'digits'] },
  { emoji: '#️⃣', name: 'keycap: #', category: 'symbols', keywords: ['hash', 'number', 'pound'] },
  { emoji: '*️⃣', name: 'keycap: *', category: 'symbols', keywords: ['asterisk', 'star'] },
  { emoji: '▶️', name: 'play button', category: 'symbols', keywords: ['play', 'start', 'run'] },
  { emoji: '⏸️', name: 'pause button', category: 'symbols', keywords: ['pause', 'stop', 'wait'] },
  { emoji: '⏹️', name: 'stop button', category: 'symbols', keywords: ['stop', 'end'] },
  { emoji: '⏺️', name: 'record button', category: 'symbols', keywords: ['record', 'circle'] },
  { emoji: '⏭️', name: 'next track button', category: 'symbols', keywords: ['next', 'forward'] },
  { emoji: '⏮️', name: 'previous track button', category: 'symbols', keywords: ['back', 'previous'] },
  { emoji: '⏩', name: 'fast-forward button', category: 'symbols', keywords: ['fast', 'speed'] },
  { emoji: '⏪', name: 'fast reverse button', category: 'symbols', keywords: ['rewind'] },
  { emoji: '🔼', name: 'upwards button', category: 'symbols', keywords: ['up', 'triangle'] },
  { emoji: '🔽', name: 'downwards button', category: 'symbols', keywords: ['down', 'triangle'] },
  { emoji: '➡️', name: 'right arrow', category: 'symbols', keywords: ['arrow', 'next', 'direction', 'forward'] },
  { emoji: '⬅️', name: 'left arrow', category: 'symbols', keywords: ['arrow', 'back', 'previous'] },
  { emoji: '⬆️', name: 'up arrow', category: 'symbols', keywords: ['arrow', 'top', 'increase'] },
  { emoji: '⬇️', name: 'down arrow', category: 'symbols', keywords: ['arrow', 'bottom', 'decrease'] },
  { emoji: '↗️', name: 'up-right arrow', category: 'symbols', keywords: ['arrow', 'growth'] },
  { emoji: '↘️', name: 'down-right arrow', category: 'symbols', keywords: ['arrow'] },
  { emoji: '↙️', name: 'down-left arrow', category: 'symbols', keywords: ['arrow'] },
  { emoji: '↖️', name: 'up-left arrow', category: 'symbols', keywords: ['arrow'] },
  { emoji: '↕️', name: 'up-down arrow', category: 'symbols', keywords: ['arrow', 'vertical'] },
  { emoji: '↔️', name: 'left-right arrow', category: 'symbols', keywords: ['arrow', 'horizontal'] },
  { emoji: '🔄', name: 'counterclockwise arrows button', category: 'symbols', keywords: ['reload', 'refresh', 'sync', 'rotate'] },
  { emoji: '🔃', name: 'clockwise vertical arrows', category: 'symbols', keywords: ['reload', 'refresh'] },
  { emoji: '🎵', name: 'musical note', category: 'symbols', keywords: ['music', 'song'] },
  { emoji: '🎶', name: 'musical notes', category: 'symbols', keywords: ['music', 'sing'] },
  { emoji: '➕', name: 'plus', category: 'symbols', keywords: ['add', 'new', 'math', '+'] },
  { emoji: '➖', name: 'minus', category: 'symbols', keywords: ['subtract', 'remove', 'math', '-'] },
  { emoji: '➗', name: 'division', category: 'symbols', keywords: ['divide', 'math'] },
  { emoji: '✖️', name: 'multiplication', category: 'symbols', keywords: ['multiply', 'math', 'times'] },
  { emoji: '🟰', name: 'heavy equals sign', category: 'symbols', keywords: ['equals', 'math', '='] },
  { emoji: '♾️', name: 'infinity', category: 'symbols', keywords: ['forever', 'loop', 'limitless'] },
  { emoji: '💲', name: 'heavy dollar sign', category: 'symbols', keywords: ['money', 'cash', 'usd', '$'] },
  { emoji: '™️', name: 'trade mark', category: 'symbols', keywords: ['trademark', 'brand', 'tm'] },
  { emoji: '©️', name: 'copyright', category: 'symbols', keywords: ['legal', 'rights', 'c'] },
  { emoji: '®️', name: 'registered', category: 'symbols', keywords: ['legal', 'brand', 'r'] },
  { emoji: '✔️', name: 'check mark', category: 'symbols', keywords: ['check', 'done', 'yes', 'ok'] },
  { emoji: '🔘', name: 'radio button', category: 'symbols', keywords: ['select', 'choice'] },
  { emoji: '🔴', name: 'red circle', category: 'symbols', keywords: ['circle', 'red', 'dot', 'status'] },
  { emoji: '🟠', name: 'orange circle', category: 'symbols', keywords: ['circle', 'orange', 'dot'] },
  { emoji: '🟡', name: 'yellow circle', category: 'symbols', keywords: ['circle', 'yellow', 'dot', 'warning'] },
  { emoji: '🟢', name: 'green circle', category: 'symbols', keywords: ['circle', 'green', 'dot', 'online', 'active'] },
  { emoji: '🔵', name: 'blue circle', category: 'symbols', keywords: ['circle', 'blue', 'dot'] },
  { emoji: '🟣', name: 'purple circle', category: 'symbols', keywords: ['circle', 'purple', 'dot'] },
  { emoji: '⚫', name: 'black circle', category: 'symbols', keywords: ['circle', 'black', 'dot'] },
  { emoji: '⚪', name: 'white circle', category: 'symbols', keywords: ['circle', 'white', 'dot'] },
  { emoji: '🟥', name: 'red square', category: 'symbols', keywords: ['square', 'red'] },
  { emoji: '🟧', name: 'orange square', category: 'symbols', keywords: ['square', 'orange'] },
  { emoji: '🟨', name: 'yellow square', category: 'symbols', keywords: ['square', 'yellow'] },
  { emoji: '🟩', name: 'green square', category: 'symbols', keywords: ['square', 'green'] },
  { emoji: '🟦', name: 'blue square', category: 'symbols', keywords: ['square', 'blue'] },
  { emoji: '🟪', name: 'purple square', category: 'symbols', keywords: ['square', 'purple'] },
  { emoji: '⬛', name: 'black large square', category: 'symbols', keywords: ['square', 'black'] },
  { emoji: '⬜', name: 'white large square', category: 'symbols', keywords: ['square', 'white'] },

  // --- Flags ---
  { emoji: '🏁', name: 'chequered flag', category: 'flags', keywords: ['finish', 'race', 'done'] },
  { emoji: '🚩', name: 'triangular flag', category: 'flags', keywords: ['red flag', 'milestone', 'mark', 'location'] },
  { emoji: '🎌', name: 'crossed flags', category: 'flags', keywords: ['japan', 'celebration'] },
  { emoji: '🏴', name: 'black flag', category: 'flags', keywords: ['pirate'] },
  { emoji: '🏳️', name: 'white flag', category: 'flags', keywords: ['peace', 'surrender'] },
  { emoji: '🏳️‍🌈', name: 'rainbow flag', category: 'flags', keywords: ['pride', 'lgbtq'] },
  { emoji: '🏳️‍⚧️', name: 'transgender flag', category: 'flags', keywords: ['pride', 'trans'] },
  { emoji: '🏴‍☠️', name: 'pirate flag', category: 'flags', keywords: ['jolly roger', 'skull'] },
  { emoji: '🇺🇸', name: 'flag: United States', category: 'flags', keywords: ['usa', 'america'] },
  { emoji: '🇬🇧', name: 'flag: United Kingdom', category: 'flags', keywords: ['uk', 'britain', 'england'] },
  { emoji: '🇨🇦', name: 'flag: Canada', category: 'flags', keywords: ['canada'] },
  { emoji: '🇦🇺', name: 'flag: Australia', category: 'flags', keywords: ['australia'] },
  { emoji: '🇩🇪', name: 'flag: Germany', category: 'flags', keywords: ['germany', 'deutschland'] },
  { emoji: '🇫🇷', name: 'flag: France', category: 'flags', keywords: ['france'] },
  { emoji: '🇯🇵', name: 'flag: Japan', category: 'flags', keywords: ['japan', 'nippon'] },
  { emoji: '🇰🇷', name: 'flag: South Korea', category: 'flags', keywords: ['korea'] },
  { emoji: '🇨🇳', name: 'flag: China', category: 'flags', keywords: ['china'] },
  { emoji: '🇮🇳', name: 'flag: India', category: 'flags', keywords: ['india'] },
  { emoji: '🇧🇷', name: 'flag: Brazil', category: 'flags', keywords: ['brazil'] },
  { emoji: '🇪🇸', name: 'flag: Spain', category: 'flags', keywords: ['spain', 'espana'] },
  { emoji: '🇮🇹', name: 'flag: Italy', category: 'flags', keywords: ['italy', 'italia'] },
];

export function filterEmojis(query: string): EmojiItem[] {
  const cleanQuery = query.toLowerCase().trim();
  if (!cleanQuery) return [...EMOJI_DATA];

  return EMOJI_DATA.filter((item) => {
    const nameMatch = item.name.toLowerCase().includes(cleanQuery);
    const keywordMatch = item.keywords?.some((kw) => kw.toLowerCase().includes(cleanQuery));
    return nameMatch || keywordMatch;
  });
}
