import { createHash, randomUUID } from 'node:crypto';
import type { RedisClientType } from 'redis';
import { logger } from '../../../core/utils/logger.js';

const LLM_CACHE_TTL = parseInt(process.env.LLM_CACHE_TTL ?? '3600', 10); // 1 hour default
const KEY_PREFIX = 'kb:llm:';
const LOCK_PREFIX = 'llm:lock:';
const LOCK_TTL = 120; // seconds — safety net if holder crashes
const LOCK_POLL_INTERVAL_MS = 1_000; // 1 second between polls
const LOCK_POLL_TIMEOUT_MS = 60_000; // give up waiting after 60 seconds
const RELEASE_LOCK_SCRIPT = `if redis.call("get", KEYS[1]) == ARGV[1] then return redis.call("del", KEYS[1]) else return 0 end`;

export interface CachedLlmResponse {
  content: string;
  cachedAt: number;
}

/**
 * Create a deterministic SHA-256 hash from LLM input parameters.
 * Used as the cache key for non-streaming LLM calls.
 */
export function hashLlmInputs(...parts: string[]): string {
  const hash = createHash('sha256');
  for (const part of parts) {
    hash.update(part);
    hash.update('\x00'); // null byte separator to avoid collisions
  }
  return hash.digest('hex');
}

/**
 * Build a cache key for a standard LLM call (improve, generate, summarize).
 * Based on: model + system_prompt + user_content (+ optional provider).
 *
 * When `provider` is supplied (issue #217), it is folded into the hash so
 * that admin flips of the `chat` use-case provider do not serve a stale
 * response generated by a different provider.
 */
export function buildLlmCacheKey(
  model: string,
  systemPrompt: string,
  userContent: string,
  provider?: string,
  options?: { thinking?: boolean; imageHash?: string },
): string {
  const providerSuffix = provider ? `provider:${provider}` : '';
  const thinkingSuffix = options?.thinking ? 'think:1' : '';
  // #1154: without this, two different images sharing a prompt collide and
  // the second caller is served the first image's answer.
  const imageSuffix = options?.imageHash ? `img:${options.imageHash}` : '';
  return KEY_PREFIX + hashLlmInputs(
    model, systemPrompt, userContent, providerSuffix, thinkingSuffix, imageSuffix,
  );
}

/**
 * Build a cache key for a RAG Q&A call.
 *
 * The hash of `prompt` — the system and user text exactly as sent — is what
 * guarantees a hit never widens the current caller's grounding. It is
 * REQUIRED because the answer cache is shared across users while the prompt
 * is assembled per caller: the page tree behind `pageId`, the caller's custom
 * system prompt, fetched external docs and web results all depend on who asks
 * and what they may read. A key that names those inputs (a page id, a URL
 * list) instead of carrying what they produced served one caller's answer,
 * grounded in a private or restricted page tree, to a caller whose own
 * assembly had excluded it. Two callers share an entry only when the text
 * sent to the model is identical, and an edit or a permission change that
 * alters the assembled text moves the key.
 *
 * Every other component is retained namespacing: it can only cause misses,
 * never let two different prompts share an entry. The model, provider,
 * thinking flag and image digests name inputs the text does not carry; the
 * question, doc IDs, external URLs, reference text, deep-search flag and
 * assembly counts are already reflected in the text.
 *
 * When `provider` is supplied (issue #217), it is folded into the hash so
 * that admin flips of the `chat` use-case provider do not serve a stale
 * response generated by a different provider.
 */
export function buildRagCacheKey(
  model: string,
  question: string,
  docIds: string[],
  options: {
    /** The system and user message text exactly as sent to the model. */
    prompt: { system: string; user: string };
    externalUrls?: string[];
    searchWeb?: boolean;
    provider?: string;
    thinking?: boolean;
    /** #1270 review m6: the assembly budget shapes the prompt, so answers
     * are budget-specific — killing assembly must not replay 30 KB-context
     * answers for the cache TTL. */
    contextChars?: number;
    /** #1270 review F9: the realized outcome — a soft-failed (chunk-level)
     * answer must not occupy the fully-assembled key for the TTL. */
    assembledPages?: number;
    /** #1273 review M5: pins change the prompt's head; a soft-failed pin
     * must not serve (or be served) the pinned answer for the TTL — and
     * sorted docIds alone cannot see a MOVED pin. */
    pinnedCount?: number;
    /**
     * #1112: deep search retrieves three phrasings and fuses them, so the
     * same question yields a different ORDER of sources and — once the
     * paraphrases reach pages the original never did — a different SET. The
     * doc-id component sees the second and not the first, and it sees
     * neither when expansion soft-fails and later recovers: a deep ask served
     * from a normal ask's key (or the reverse) is the two modes serving each
     * other's answer for the whole TTL. The flag separates the namespaces
     * outright.
     */
    deepSearch?: boolean;
    imageHash?: string;
    /**
     * #1115 P4: the RETRIEVED images the request actually carried, as
     * `retrievedImagesCacheComponent` renders them (count + a hash of the
     * page/store/key/content-digest tuples), or `undefined` when none were sent.
     *
     * The doc-id component above says which pages ground the answer and
     * nothing about whether the model could SEE them, so without this a
     * vision-capable model's image-augmented answer and a text-only model's
     * answer to the same question over the same pages would share a key and
     * serve each other for the TTL — as would the same model's answers either
     * side of an admin moving `rag_answer_max_images`, or of a picture being
     * deleted from one of those pages.
     *
     * `undefined` is the no-images spelling because the absence of images is
     * not a zero-length set of them — it keeps "no pictures were attached"
     * unable to collide with some future "0 pictures, deliberately", and
     * keeps the suffix out of the derivation's own reading below. It does
     * NOT preserve existing keys, and review r1 corrected the claim that it
     * did: `hashLlmInputs` writes a `\x00` separator per component, so
     * passing a 15th component at all moves every pre-P4 digest whether or
     * not it is empty. Every deployment cold-starts its answer cache once,
     * for one `LLM_CACHE_TTL`.
     *
     * Distinct from `imageHash`, which is the USER's own attachment. The two
     * are different inputs and both belong in the key.
     */
    retrievedImages?: string;
    /** Sanitized/truncated attached document text; folded into the final hash. */
    referenceText?: string;
  },
): string {
  const sortedIds = [...docIds].sort().join(',');
  const promptSuffix = `prompt:${createHash('sha256')
    .update(JSON.stringify([options.prompt.system, options.prompt.user]))
    .digest('hex')}`;
  const externalSuffix = options.externalUrls?.length
    ? `ext:${[...options.externalUrls].sort().join(',')}`
    : '';
  const webSuffix = options.searchWeb ? 'web:1' : '';
  const providerSuffix = options.provider ? `provider:${options.provider}` : '';
  // Thinking-on responses are slower and reason differently — they must live
  // in a separate cache namespace so a prior thinking-off answer can't be
  // replayed when the user toggles Think on (and vice versa).
  const thinkingSuffix = options.thinking ? 'think:1' : '';
  const contextSuffix = options.contextChars !== undefined ? `ctx:${options.contextChars}` : '';
  const assembledSuffix = options.assembledPages !== undefined ? `asm:${options.assembledPages}` : '';
  const pinnedSuffix = options.pinnedCount !== undefined ? `pin:${options.pinnedCount}` : '';
  const deepSuffix = options.deepSearch ? 'deep:1' : '';
  const imageSuffix = options.imageHash ? `img:${options.imageHash}` : '';
  const retrievedImagesSuffix = options.retrievedImages ? `rimg:${options.retrievedImages}` : '';
  const referenceSuffix = options.referenceText ? `ref:${options.referenceText}` : '';
  return KEY_PREFIX + hashLlmInputs(model, question, sortedIds, promptSuffix, externalSuffix, webSuffix, providerSuffix, thinkingSuffix, contextSuffix, assembledSuffix, pinnedSuffix, deepSuffix, imageSuffix, retrievedImagesSuffix, referenceSuffix);
}

export class LlmCache {
  constructor(private redis: RedisClientType) {}

  /**
   * Get a cached LLM response by cache key.
   */
  async getCachedResponse(cacheKey: string): Promise<CachedLlmResponse | null> {
    try {
      const data = await this.redis.get(cacheKey);
      if (!data) return null;
      return JSON.parse(data) as CachedLlmResponse;
    } catch (err) {
      logger.error({ err, cacheKey }, 'LLM cache get error');
      return null;
    }
  }

  /**
   * Store an LLM response in the cache.
   */
  async setCachedResponse(
    cacheKey: string,
    content: string,
    ttl: number = LLM_CACHE_TTL,
  ): Promise<void> {
    try {
      const cached: CachedLlmResponse = {
        content,
        cachedAt: Date.now(),
      };
      await this.redis.setEx(cacheKey, ttl, JSON.stringify(cached));
    } catch (err) {
      logger.error({ err, cacheKey }, 'LLM cache set error');
    }
  }

  /**
   * Acquire a Redis-based lock for a cache key using SET NX EX.
   * Returns a unique ownership token if acquired, or null if another holder
   * owns the lock. The token must be passed to releaseLock so an expired
   * holder cannot delete a successor's live lock.
   */
  async acquireLock(cacheKey: string, ttl: number = LOCK_TTL): Promise<string | null> {
    const token = randomUUID();
    try {
      const lockKey = LOCK_PREFIX + cacheKey;
      // SET key token NX EX ttl — atomic "set if not exists" with expiry
      const result = await this.redis.set(lockKey, token, { NX: true, EX: ttl });
      return result !== null ? token : null;
    } catch (err) {
      logger.error({ err, cacheKey }, 'LLM lock acquire error');
      // On Redis failure, allow the caller to proceed (degrade gracefully).
      // A later release is still ownership-checked in case Redis recovers.
      return token;
    }
  }

  /**
   * Release the Redis lock only when token still identifies its current owner.
   * The compare-and-delete Lua script is atomic, so a holder whose TTL expired
   * cannot delete a successor's lock. Redis failures remain a no-op.
   */
  async releaseLock(cacheKey: string, token: string): Promise<void> {
    try {
      await this.redis.eval(RELEASE_LOCK_SCRIPT, {
        keys: [LOCK_PREFIX + cacheKey],
        arguments: [token],
      });
    } catch (err) {
      logger.error({ err, cacheKey }, 'LLM lock release error');
    }
  }

  /**
   * Poll for a cached response to appear (written by the lock holder).
   * Returns the cached response if it appears within the timeout, or null
   * if the timeout expires (caller should then generate its own response).
   */
  async waitForCachedResponse(
    cacheKey: string,
    pollIntervalMs: number = LOCK_POLL_INTERVAL_MS,
    timeoutMs: number = LOCK_POLL_TIMEOUT_MS,
  ): Promise<CachedLlmResponse | null> {
    const deadline = Date.now() + timeoutMs;
    while (Date.now() < deadline) {
      const cached = await this.getCachedResponse(cacheKey);
      if (cached) return cached;

      // Check if the lock is still held — if not, the holder may have failed
      try {
        const lockKey = LOCK_PREFIX + cacheKey;
        const lockExists = await this.redis.exists(lockKey);
        if (!lockExists) {
          logger.debug({ cacheKey }, 'Lock released but no cached response — proceeding with generation');
          return null;
        }
      } catch {
        // Redis error during exists check — keep polling
      }

      await sleep(pollIntervalMs);
    }

    logger.warn({ cacheKey }, 'Timed out waiting for locked LLM cache — proceeding with generation');
    return null;
  }

  /**
   * Clear all LLM cache entries using SCAN (O(1) per call).
   */
  async clearAll(): Promise<number> {
    let cursor = '0';
    let deleted = 0;
    try {
      do {
        const result = await this.redis.scan(cursor, {
          MATCH: `${KEY_PREFIX}*`,
          COUNT: 100,
        });
        cursor = String(result.cursor);
        if (result.keys.length > 0) {
          await this.redis.del(result.keys);
          deleted += result.keys.length;
        }
      } while (cursor !== '0');
    } catch (err) {
      logger.error({ err }, 'LLM cache clear error');
    }
    return deleted;
  }
}

/** Promise-based sleep helper. */
function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
