-- One rendered Connections impression per authenticated article visit.
-- The visit UUID is generated by the mounted article panel. Source page and
-- user remain in the key so the same UUID cannot suppress another user's or
-- another article's denominator event.
CREATE UNIQUE INDEX IF NOT EXISTS idx_audit_log_connection_impression_visit
  ON audit_log (user_id, resource_id, ((metadata ->> 'visitId')))
  WHERE action = 'CONNECTION_IMPRESSION';
