import {
  Activity,
  AlarmClock,
  AlertTriangle,
  Ampersand,
  Anchor,
  Apple,
  AppWindow,
  Archive,
  Asterisk,
  Atom,
  AtSign,
  Award,
  BadgeCheck,
  Ban,
  Banknote,
  Beer,
  Bell,
  Bike,
  Binary,
  Blocks,
  Binoculars,
  Bird,
  Bluetooth,
  Book,
  Bookmark,
  BookCopy,
  BookMarked,
  BookOpen,
  Bot,
  BotMessageSquare,
  BrainCircuit,
  Boxes,
  Braces,
  Brackets,
  Brain,
  Briefcase,
  Bug,
  Building2,
  Bus,
  Cable,
  Cake,
  Calculator,
  Calendar,
  CalendarCheck,
  CalendarDays,
  Camera,
  Car,
  Castle,
  Cat,
  ChartArea,
  ChartColumn,
  ChartLine,
  ChartPie,
  Check,
  CheckCircle,
  Cherry,
  CircleAlert,
  CircleCheck,
  CircleDot,
  CirclePlus,
  CircleX,
  CircuitBoard,
  Clapperboard,
  Clipboard,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Cloud,
  CloudDownload,
  CloudUpload,
  Code,
  Coffee,
  Cog,
  Coins,
  Component,
  Compass,
  Construction,
  Contrast,
  Cuboid,
  Contact,
  Container,
  Cookie,
  Cpu,
  CreditCard,
  Crown,
  Database,
  Dice5,
  Diamond,
  Dna,
  Dog,
  Download,
  Earth,
  Eclipse,
  Equal,
  EthernetPort,
  Droplet,
  Dumbbell,
  Eye,
  EyeOff,
  Factory,
  File,
  FileArchive,
  FilePen,
  FileSearch,
  FileCode,
  FileJson,
  Files,
  FileSpreadsheet,
  FileStack,
  FileText,
  Film,
  Filter,
  Fingerprint,
  Fish,
  Flag,
  Flame,
  Flashlight,
  FlaskConical,
  Flower2,
  Focus,
  Folder,
  FolderGit2,
  FolderKanban,
  FolderOpen,
  FolderPlus,
  FolderTree,
  Fuel,
  FunctionSquare,
  Gamepad2,
  GanttChart,
  Gift,
  GitBranch,
  GitCompare,
  GitCommitHorizontal,
  GitMerge,
  GitPullRequest,
  Goal,
  GraduationCap,
  Hammer,
  Hand,
  Handshake,
  HardHat,
  Hash,
  Headphones,
  Heart,
  HeartPulse,
  HelpCircle,
  Hexagon,
  Highlighter,
  History,
  Hospital,
  Hourglass,
  House,
  IceCreamCone,
  IdCard,
  Image,
  Inbox,
  Infinity,
  Info,
  Kanban,
  Key,
  Keyboard,
  Landmark,
  Laptop,
  Layers,
  LayoutGrid,
  Leaf,
  Library,
  Lightbulb,
  Link,
  List,
  ListChecks,
  ListTodo,
  Lock,
  Magnet,
  Mail,
  Map,
  MapPin,
  Medal,
  Megaphone,
  MessageCircle,
  MessagesSquare,
  Mic,
  Minus,
  Microscope,
  Milestone,
  Monitor,
  Moon,
  MousePointer2,
  Mountain,
  Music,
  Navigation,
  Network,
  Newspaper,
  Notebook,
  NotepadText,
  Orbit,
  Package,
  Paintbrush,
  Palette,
  Palmtree,
  Paperclip,
  ParkingCircle,
  PartyPopper,
  PawPrint,
  PenLine,
  Pentagon,
  Percent,
  Phone,
  Plus,
  Pointer,
  PiggyBank,
  Pill,
  Pin,
  Pipette,
  Pizza,
  Plane,
  Play,
  Plug,
  Presentation,
  Printer,
  Puzzle,
  QrCode,
  Quote,
  Rabbit,
  RadioTower,
  Rainbow,
  Receipt,
  Regex,
  RefreshCw,
  Repeat,
  Rocket,
  Route,
  Rss,
  Ruler,
  Satellite,
  Scale,
  Scan,
  ScanSearch,
  School,
  Scissors,
  Scroll,
  Search,
  Send,
  Server,
  Settings,
  Share2,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Ship,
  Sigma,
  ShoppingBag,
  ShoppingCart,
  Signpost,
  SlidersHorizontal,
  Smartphone,
  Smile,
  Snowflake,
  Sparkle,
  Sparkles,
  Speech,
  Sprout,
  SquareTerminal,
  Star,
  Stethoscope,
  StickyNote,
  Store,
  Sun,
  SunMoon,
  Sunrise,
  Table,
  Table2,
  Tablet,
  Tag,
  Target,
  Telescope,
  Tent,
  Terminal,
  TestTube,
  ThumbsDown,
  ThumbsUp,
  Ticket,
  Timer,
  TrafficCone,
  TrainFront,
  TramFront,
  TreePine,
  Triangle,
  TrendingDown,
  TrendingUp,
  Trophy,
  Truck,
  Type,
  Umbrella,
  Unlock,
  Upload,
  User,
  UserCheck,
  UserPlus,
  Users,
  Utensils,
  Variable,
  Vault,
  Video,
  Voicemail,
  Volume2,
  Wallet,
  Warehouse,
  Watch,
  WandSparkles,
  Waves,
  Wifi,
  Wind,
  Wine,
  Workflow,
  Wrench,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-react';
import { PAGE_LUCIDE_ICONS, type PageLucideIconId } from '@compendiq/contracts';

const ICONS: Record<PageLucideIconId, LucideIcon> = {
  'book': Book,
  'bookmark': Bookmark,
  'file-text': FileText,
  'files': Files,
  'folder': Folder,
  'folder-open': FolderOpen,
  'clipboard-list': ClipboardList,
  'notebook': Notebook,
  'newspaper': Newspaper,
  'library': Library,
  'rocket': Rocket,
  'lightbulb': Lightbulb,
  'zap': Zap,
  'star': Star,
  'heart': Heart,
  'flag': Flag,
  'target': Target,
  'compass': Compass,
  'map': Map,
  'milestone': Milestone,
  'code': Code,
  'terminal': Terminal,
  'bug': Bug,
  'git-branch': GitBranch,
  'database': Database,
  'server': Server,
  'cpu': Cpu,
  'wifi': Wifi,
  'lock': Lock,
  'shield': Shield,
  'key': Key,
  'users': Users,
  'user': User,
  'briefcase': Briefcase,
  'building-2': Building2,
  'calendar': Calendar,
  'clock': Clock,
  'mail': Mail,
  'message-circle': MessageCircle,
  'bell': Bell,
  'settings': Settings,
  'wrench': Wrench,
  'search': Search,
  'filter': Filter,
  'list': List,
  'layout-grid': LayoutGrid,
  'layers': Layers,
  'puzzle': Puzzle,
  'boxes': Boxes,
  'package': Package,
  'check-circle': CheckCircle,
  'alert-triangle': AlertTriangle,
  'info': Info,
  'help-circle': HelpCircle,
  'circle-dot': CircleDot,
  'pen-line': PenLine,
  'image': Image,
  'camera': Camera,
  'video': Video,
  'music': Music,
  'mic': Mic,
  'play': Play,
  'film': Film,
  'leaf': Leaf,
  'sun': Sun,
  'moon': Moon,
  'cloud': Cloud,
  'droplet': Droplet,
  'flame': Flame,
  'mountain': Mountain,
  'tree-pine': TreePine,
  'flower-2': Flower2,
  'car': Car,
  'plane': Plane,
  'ship': Ship,
  'bike': Bike,
  'house': House,
  'coffee': Coffee,
  'utensils': Utensils,
  'gift': Gift,
  'trophy': Trophy,
  'medal': Medal,
  'link': Link,
  'paperclip': Paperclip,
  'pin': Pin,
  'tag': Tag,
  'hash': Hash,
  'chart-column': ChartColumn,
  'graduation-cap': GraduationCap,
  'stethoscope': Stethoscope,
  'scale': Scale,
  'wallet': Wallet,
  'megaphone': Megaphone,
  'sparkles': Sparkles,
  'bot': Bot,
  'archive': Archive,
  'inbox': Inbox,
  'book-open': BookOpen,
  'book-marked': BookMarked,
  'sticky-note': StickyNote,
  'notepad-text': NotepadText,
  'file': File,
  'file-stack': FileStack,
  'file-code': FileCode,
  'file-spreadsheet': FileSpreadsheet,
  'file-json': FileJson,
  'file-archive': FileArchive,
  'folder-tree': FolderTree,
  'folder-kanban': FolderKanban,
  'folder-plus': FolderPlus,
  'scroll': Scroll,
  'quote': Quote,
  'type': Type,
  'highlighter': Highlighter,
  'kanban': Kanban,
  'list-todo': ListTodo,
  'list-checks': ListChecks,
  'clipboard': Clipboard,
  'clipboard-check': ClipboardCheck,
  'route': Route,
  'signpost': Signpost,
  'gantt-chart': GanttChart,
  'goal': Goal,
  'focus': Focus,
  'binoculars': Binoculars,
  'circle-check': CircleCheck,
  'circle-x': CircleX,
  'circle-alert': CircleAlert,
  'ban': Ban,
  'circle-plus': CirclePlus,
  'binary': Binary,
  'brackets': Brackets,
  'braces': Braces,
  'square-terminal': SquareTerminal,
  'container': Container,
  'circuit-board': CircuitBoard,
  'monitor': Monitor,
  'laptop': Laptop,
  'smartphone': Smartphone,
  'tablet': Tablet,
  'keyboard': Keyboard,
  'printer': Printer,
  'plug': Plug,
  'cable': Cable,
  'bluetooth': Bluetooth,
  'radio-tower': RadioTower,
  'satellite': Satellite,
  'cloud-upload': CloudUpload,
  'cloud-download': CloudDownload,
  'upload': Upload,
  'download': Download,
  'refresh-cw': RefreshCw,
  'repeat': Repeat,
  'git-commit-horizontal': GitCommitHorizontal,
  'git-merge': GitMerge,
  'git-pull-request': GitPullRequest,
  'workflow': Workflow,
  'contact': Contact,
  'handshake': Handshake,
  'presentation': Presentation,
  'crown': Crown,
  'award': Award,
  'badge-check': BadgeCheck,
  'id-card': IdCard,
  'smile': Smile,
  'speech': Speech,
  'headphones': Headphones,
  'phone': Phone,
  'send': Send,
  'share-2': Share2,
  'at-sign': AtSign,
  'rss': Rss,
  'atom': Atom,
  'flask-conical': FlaskConical,
  'microscope': Microscope,
  'telescope': Telescope,
  'dna': Dna,
  'pill': Pill,
  'brain': Brain,
  'heart-pulse': HeartPulse,
  'activity': Activity,
  'test-tube': TestTube,
  'map-pin': MapPin,
  'navigation': Navigation,
  'tent': Tent,
  'palmtree': Palmtree,
  'waves': Waves,
  'wind': Wind,
  'snowflake': Snowflake,
  'umbrella': Umbrella,
  'sunrise': Sunrise,
  'sprout': Sprout,
  'bird': Bird,
  'fish': Fish,
  'cat': Cat,
  'dog': Dog,
  'rabbit': Rabbit,
  'paw-print': PawPrint,
  'store': Store,
  'factory': Factory,
  'warehouse': Warehouse,
  'hospital': Hospital,
  'school': School,
  'landmark': Landmark,
  'castle': Castle,
  'truck': Truck,
  'bus': Bus,
  'train-front': TrainFront,
  'tram-front': TramFront,
  'fuel': Fuel,
  'parking-circle': ParkingCircle,
  'traffic-cone': TrafficCone,
  'construction': Construction,
  'anchor': Anchor,
  'calculator': Calculator,
  'receipt': Receipt,
  'credit-card': CreditCard,
  'banknote': Banknote,
  'piggy-bank': PiggyBank,
  'percent': Percent,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  'coins': Coins,
  'timer': Timer,
  'hourglass': Hourglass,
  'calendar-days': CalendarDays,
  'calendar-check': CalendarCheck,
  'alarm-clock': AlarmClock,
  'history': History,
  'watch': Watch,
  'fingerprint': Fingerprint,
  'unlock': Unlock,
  'vault': Vault,
  'scan': Scan,
  'qr-code': QrCode,
  'eye': Eye,
  'eye-off': EyeOff,
  'scan-search': ScanSearch,
  'hammer': Hammer,
  'cog': Cog,
  'sliders-horizontal': SlidersHorizontal,
  'paintbrush': Paintbrush,
  'palette': Palette,
  'pipette': Pipette,
  'ruler': Ruler,
  'scissors': Scissors,
  'magnet': Magnet,
  'flashlight': Flashlight,
  'apple': Apple,
  'cherry': Cherry,
  'pizza': Pizza,
  'wine': Wine,
  'beer': Beer,
  'cookie': Cookie,
  'cake': Cake,
  'ice-cream-cone': IceCreamCone,
  'shopping-cart': ShoppingCart,
  'shopping-bag': ShoppingBag,
  'dumbbell': Dumbbell,
  'gamepad-2': Gamepad2,
  'dice-5': Dice5,
  'party-popper': PartyPopper,
  'ticket': Ticket,
  'clapperboard': Clapperboard,
  'chart-line': ChartLine,
  'chart-pie': ChartPie,
  'chart-area': ChartArea,
  'table': Table,
  'table-2': Table2,
  'sigma': Sigma,
  'function-square': FunctionSquare,
  'variable': Variable,
  'regex': Regex,
  'component': Component,
  'blocks': Blocks,
  'app-window': AppWindow,
  'network': Network,
  'ethernet-port': EthernetPort,
  'hard-hat': HardHat,
  'rainbow': Rainbow,
  'pentagon': Pentagon,
  'hexagon': Hexagon,
  'triangle': Triangle,
  'diamond': Diamond,
  'asterisk': Asterisk,
  'infinity': Infinity,
  'equal': Equal,
  'plus': Plus,
  'minus': Minus,
  'x': X,
  'check': Check,
  'thumbs-up': ThumbsUp,
  'thumbs-down': ThumbsDown,
  'hand': Hand,
  'pointer': Pointer,
  'mouse-pointer-2': MousePointer2,
  'volume-2': Volume2,
  'contrast': Contrast,
  'sun-moon': SunMoon,
  'eclipse': Eclipse,
  'orbit': Orbit,
  'earth': Earth,
  'cuboid': Cuboid,
  'file-pen': FilePen,
  'file-search': FileSearch,
  'book-copy': BookCopy,
  'wand-sparkles': WandSparkles,
  'sparkle': Sparkle,
  'shield-check': ShieldCheck,
  'shield-alert': ShieldAlert,
  'user-check': UserCheck,
  'user-plus': UserPlus,
  'voicemail': Voicemail,
  'brain-circuit': BrainCircuit,
  'bot-message-square': BotMessageSquare,
  'messages-square': MessagesSquare,
  'folder-git-2': FolderGit2,
  'git-compare': GitCompare,
  'ampersand': Ampersand,
};

export function getPageLucideIcon(id: string): LucideIcon | null {
  return ICONS[id as PageLucideIconId] ?? null;
}

export { PAGE_LUCIDE_ICONS };
