import {
  Accessibility,
  Activity,
  AlarmClock,
  AlarmClockCheck,
  AlarmClockMinus,
  AlarmClockOff,
  AlarmClockPlus,
  AlertTriangle,
  Ambulance,
  Ampersand,
  Anchor,
  Antenna,
  AppWindow,
  Apple,
  Archive,
  ArchiveRestore,
  ArrowDown,
  ArrowDownLeft,
  ArrowDownRight,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpLeft,
  ArrowUpRight,
  Asterisk,
  AtSign,
  Atom,
  Award,
  Baby,
  Badge,
  BadgeAlert,
  BadgeCent,
  BadgeCheck,
  BadgeDollarSign,
  BadgeInfo,
  BadgePercent,
  BadgeX,
  Ban,
  Banknote,
  Beaker,
  Beer,
  Bell,
  BellDot,
  BellMinus,
  BellOff,
  BellPlus,
  BellRing,
  Bike,
  Binary,
  Binoculars,
  Biohazard,
  Bird,
  Blocks,
  Bluetooth,
  Book,
  BookCheck,
  BookCopy,
  BookMarked,
  BookOpen,
  BookOpenCheck,
  Bookmark,
  BookmarkCheck,
  BookmarkMinus,
  BookmarkPlus,
  BookmarkX,
  Bot,
  BotMessageSquare,
  Boxes,
  Braces,
  Brackets,
  Brain,
  BrainCircuit,
  Briefcase,
  BriefcaseBusiness,
  BriefcaseMedical,
  Brush,
  Bug,
  Building2,
  Bus,
  Cable,
  Cake,
  Calculator,
  Calendar,
  CalendarCheck,
  CalendarCheck2,
  CalendarClock,
  CalendarDays,
  CalendarHeart,
  CalendarMinus,
  CalendarOff,
  CalendarPlus,
  CalendarRange,
  CalendarSearch,
  CalendarSync,
  CalendarX,
  CalendarX2,
  Camera,
  CandlestickChart,
  Candy,
  Car,
  CarFront,
  CarTaxiFront,
  Castle,
  Cat,
  ChartArea,
  ChartColumn,
  ChartColumnBig,
  ChartColumnDecreasing,
  ChartColumnIncreasing,
  ChartColumnStacked,
  ChartLine,
  ChartPie,
  ChartScatter,
  ChartSpline,
  Check,
  CheckCheck,
  CheckCircle,
  CheckCircle2,
  Cherry,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsDown,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUp,
  CircleAlert,
  CircleCheck,
  CircleCheckBig,
  CircleDollarSign,
  CircleDot,
  CircleEllipsis,
  CircleHelp,
  CircleMinus,
  CirclePause,
  CirclePlay,
  CirclePlus,
  CircleSlash,
  CircleSlash2,
  CircleStop,
  CircleX,
  CircuitBoard,
  Clapperboard,
  Clipboard,
  ClipboardCheck,
  ClipboardCopy,
  ClipboardList,
  ClipboardPaste,
  ClipboardX,
  Clock,
  Clock1,
  Clock10,
  Clock11,
  Clock12,
  Clock2,
  Clock3,
  Clock4,
  Clock5,
  Clock6,
  Clock7,
  Clock8,
  Clock9,
  ClockAlert,
  Cloud,
  CloudAlert,
  CloudCheck,
  CloudDownload,
  CloudDrizzle,
  CloudFog,
  CloudHail,
  CloudMoon,
  CloudMoonRain,
  CloudRainWind,
  CloudSunRain,
  CloudUpload,
  Clover,
  Code,
  CodeXml,
  Coffee,
  Cog,
  Coins,
  Compass,
  Component,
  Construction,
  Contact,
  ContactRound,
  Container,
  Contrast,
  Cookie,
  Copy,
  CornerDownLeft,
  CornerDownRight,
  CornerUpLeft,
  CornerUpRight,
  Cpu,
  CreditCard,
  Croissant,
  Cross,
  Crosshair,
  Crown,
  Cuboid,
  CupSoda,
  Database,
  Diamond,
  Dice5,
  Dices,
  Disc,
  Disc2,
  Disc3,
  Dna,
  Dog,
  Download,
  Drill,
  Droplet,
  Dumbbell,
  Earth,
  Eclipse,
  Ellipsis,
  EllipsisVertical,
  Equal,
  Eraser,
  EthernetPort,
  Eye,
  EyeOff,
  Factory,
  FastForward,
  Feather,
  File,
  FileArchive,
  FileAudio,
  FileAudio2,
  FileAxis3d,
  FileBadge,
  FileBadge2,
  FileBox,
  FileChartColumn,
  FileChartColumnIncreasing,
  FileChartLine,
  FileChartPie,
  FileCheck2,
  FileClock,
  FileCode,
  FileDiff,
  FileDigit,
  FileDown,
  FileHeart,
  FileImage,
  FileJson,
  FileJson2,
  FileKey,
  FileKey2,
  FileLock,
  FileLock2,
  FileMinus2,
  FileMusic,
  FileOutput,
  FilePen,
  FilePenLine,
  FilePlus2,
  FileQuestion,
  FileScan,
  FileSearch,
  FileSliders,
  FileSpreadsheet,
  FileStack,
  FileSymlink,
  FileTerminal,
  FileText,
  FileType,
  FileType2,
  FileUp,
  FileUser,
  FileVideo,
  FileVideo2,
  FileVolume,
  FileVolume2,
  FileWarning,
  FileX2,
  Files,
  Film,
  Filter,
  Fingerprint,
  Fish,
  Flag,
  Flame,
  Footprints,
  FlameKindling,
  Flashlight,
  FlaskConical,
  FlaskRound,
  Flower2,
  Focus,
  Folder,
  FolderArchive,
  FolderCheck,
  FolderClock,
  FolderClosed,
  FolderCode,
  FolderCog,
  FolderDot,
  FolderDown,
  FolderGit2,
  FolderHeart,
  FolderInput,
  FolderKanban,
  FolderKey,
  FolderMinus,
  FolderOpen,
  FolderOpenDot,
  FolderOutput,
  FolderPen,
  FolderPlus,
  FolderRoot,
  FolderSearch,
  FolderSearch2,
  FolderSymlink,
  FolderSync,
  FolderTree,
  FolderUp,
  FolderX,
  Fuel,
  FunctionSquare,
  Gamepad,
  Gamepad2,
  GanttChart,
  Gem,
  Gift,
  GitBranch,
  GitCommitHorizontal,
  GitCommitVertical,
  GitCompare,
  GitMerge,
  GitPullRequest,
  GlassWater,
  Goal,
  GraduationCap,
  Grip,
  GripHorizontal,
  GripVertical,
  Hammer,
  Hand,
  HandCoins,
  Handshake,
  HardHat,
  Hash,
  Headphones,
  Headset,
  Heart,
  HeartCrack,
  HeartHandshake,
  HeartPulse,
  HelpCircle,
  Hexagon,
  Highlighter,
  History,
  Hospital,
  Hourglass,
  House,
  IceCreamCone,
  IdCard,
  Image,
  Inbox,
  Infinity as InfinityIcon,
  Info,
  Inspect,
  Joystick,
  Kanban,
  Key,
  KeySquare,
  Keyboard,
  Landmark,
  Laptop,
  LaptopMinimal,
  Layers,
  LayoutGrid,
  Leaf,
  Library,
  LifeBuoy,
  Lightbulb,
  Link,
  List,
  ListChecks,
  ListTodo,
  Locate,
  LocateFixed,
  Lock,
  LockKeyhole,
  LockKeyholeOpen,
  Luggage,
  Magnet,
  Mail,
  Map,
  MapPin,
  MapPinOff,
  Medal,
  Megaphone,
  MegaphoneOff,
  MessageCircle,
  MessageCirclePlus,
  MessageCircleQuestion,
  MessageSquare,
  MessageSquareCode,
  MessageSquareDashed,
  MessageSquarePlus,
  MessagesSquare,
  Mic,
  MicOff,
  MicVocal,
  Microscope,
  Milestone,
  Minus,
  Monitor,
  MonitorCheck,
  MonitorSmartphone,
  MonitorSpeaker,
  MonitorX,
  Moon,
  Mountain,
  MountainSnow,
  MousePointer2,
  Move,
  Music,
  Music2,
  Music3,
  Music4,
  Navigation,
  Navigation2,
  Network,
  Newspaper,
  Notebook,
  NotepadText,
  Nut,
  Octagon,
  Orbit,
  Package,
  Paintbrush,
  Paintbrush2,
  Palette,
  Palmtree,
  Paperclip,
  ParkingCircle,
  PartyPopper,
  Pause,
  PauseCircle,
  PawPrint,
  Pen,
  PenLine,
  PenTool,
  Pencil,
  Pentagon,
  Percent,
  PersonStanding,
  Phone,
  PhoneCall,
  PhoneForwarded,
  PhoneIncoming,
  PhoneMissed,
  PhoneOff,
  PhoneOutgoing,
  Pi,
  PiggyBank,
  Pill,
  Pin,
  PinOff,
  Pipette,
  Pizza,
  Plane,
  PlaneLanding,
  PlaneTakeoff,
  Play,
  PlayCircle,
  Plug,
  Plus,
  Podcast,
  Pointer,
  Popcorn,
  Presentation,
  Printer,
  Projector,
  Puzzle,
  QrCode,
  Quote,
  Rabbit,
  Radiation,
  RadioReceiver,
  RadioTower,
  Radius,
  Rainbow,
  Ratio,
  Receipt,
  ReceiptCent,
  ReceiptEuro,
  ReceiptJapaneseYen,
  ReceiptPoundSterling,
  ReceiptText,
  RefreshCw,
  Regex,
  Repeat,
  Rewind,
  Rocket,
  Route,
  Rss,
  Ruler,
  Sailboat,
  Salad,
  Sandwich,
  Satellite,
  SatelliteDish,
  Scale,
  Scale3d,
  Scan,
  ScanEye,
  ScanFace,
  ScanLine,
  ScanSearch,
  School,
  Scissors,
  Scroll,
  ScrollText,
  Search,
  Send,
  Server,
  Settings,
  Shapes,
  Share,
  Share2,
  Shield,
  ShieldAlert,
  ShieldBan,
  ShieldCheck,
  ShieldEllipsis,
  ShieldHalf,
  ShieldMinus,
  ShieldPlus,
  ShieldQuestion,
  ShieldX,
  Ship,
  ShoppingBag,
  ShoppingCart,
  Sigma,
  Signpost,
  SignpostBig,
  Siren,
  SlidersHorizontal,
  Smartphone,
  SmartphoneCharging,
  SmartphoneNfc,
  Smile,
  Snowflake,
  Soup,
  Sparkle,
  Sparkles,
  Speaker,
  Speech,
  Spline,
  SprayCan,
  Sprout,
  SquareTerminal,
  Squirrel,
  Stamp,
  Star,
  StarHalf,
  StarOff,
  Stars,
  StepBack,
  StepForward,
  Stethoscope,
  StickyNote,
  StopCircle,
  Store,
  Sun,
  SunDim,
  SunMedium,
  SunMoon,
  Sunrise,
  Sunset,
  Sword,
  Swords,
  Syringe,
  Table,
  Table2,
  TableProperties,
  Tablet,
  TabletSmartphone,
  Tag,
  Target,
  Telescope,
  Tent,
  Terminal,
  TestTube,
  TestTubes,
  ThumbsDown,
  ThumbsUp,
  Ticket,
  TicketCheck,
  TicketSlash,
  Tickets,
  Timer,
  TimerOff,
  TimerReset,
  Tornado,
  TrafficCone,
  TrainFront,
  TramFront,
  Trash,
  Trash2,
  TreeDeciduous,
  TreePine,
  TrendingDown,
  TrendingUp,
  Triangle,
  Trophy,
  Truck,
  Type,
  Umbrella,
  Unlock,
  Upload,
  User,
  UserCheck,
  UserCog,
  UserMinus,
  UserPlus,
  UserRound,
  UserRoundCheck,
  UserRoundCog,
  UserRoundPlus,
  UserRoundX,
  UserX,
  Users,
  UsersRound,
  Utensils,
  Variable,
  Vault,
  Video,
  VideoOff,
  Voicemail,
  Volleyball,
  Volume,
  Volume1,
  Volume2,
  VolumeX,
  Wallet,
  Wand,
  WandSparkles,
  Warehouse,
  Watch,
  Waves,
  Webcam,
  Wifi,
  Wind,
  Wine,
  Workflow,
  Worm,
  Wrench,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-react';
import { PAGE_LUCIDE_ICONS, type PageLucideIconId } from '@compendiq/contracts';

const ICONS: Record<PageLucideIconId, LucideIcon> = {
  'book': Book,
  'bookmark': Bookmark,
  'file-text': FileText,
  'files': Files,
  'folder': Folder,
  'folder-open': FolderOpen,
  'clipboard-list': ClipboardList,
  'notebook': Notebook,
  'newspaper': Newspaper,
  'library': Library,
  'rocket': Rocket,
  'lightbulb': Lightbulb,
  'zap': Zap,
  'star': Star,
  'heart': Heart,
  'flag': Flag,
  'target': Target,
  'compass': Compass,
  'map': Map,
  'milestone': Milestone,
  'code': Code,
  'terminal': Terminal,
  'bug': Bug,
  'git-branch': GitBranch,
  'database': Database,
  'server': Server,
  'cpu': Cpu,
  'wifi': Wifi,
  'lock': Lock,
  'shield': Shield,
  'key': Key,
  'users': Users,
  'user': User,
  'briefcase': Briefcase,
  'building-2': Building2,
  'calendar': Calendar,
  'clock': Clock,
  'mail': Mail,
  'message-circle': MessageCircle,
  'bell': Bell,
  'settings': Settings,
  'wrench': Wrench,
  'search': Search,
  'filter': Filter,
  'list': List,
  'layout-grid': LayoutGrid,
  'layers': Layers,
  'puzzle': Puzzle,
  'boxes': Boxes,
  'package': Package,
  'check-circle': CheckCircle,
  'alert-triangle': AlertTriangle,
  'info': Info,
  'help-circle': HelpCircle,
  'circle-dot': CircleDot,
  'pen-line': PenLine,
  'image': Image,
  'camera': Camera,
  'video': Video,
  'music': Music,
  'mic': Mic,
  'play': Play,
  'film': Film,
  'leaf': Leaf,
  'sun': Sun,
  'moon': Moon,
  'cloud': Cloud,
  'droplet': Droplet,
  'flame': Flame,
  'mountain': Mountain,
  'tree-pine': TreePine,
  'flower-2': Flower2,
  'car': Car,
  'plane': Plane,
  'ship': Ship,
  'bike': Bike,
  'house': House,
  'coffee': Coffee,
  'utensils': Utensils,
  'gift': Gift,
  'trophy': Trophy,
  'medal': Medal,
  'link': Link,
  'paperclip': Paperclip,
  'pin': Pin,
  'tag': Tag,
  'hash': Hash,
  'chart-column': ChartColumn,
  'graduation-cap': GraduationCap,
  'stethoscope': Stethoscope,
  'scale': Scale,
  'wallet': Wallet,
  'megaphone': Megaphone,
  'sparkles': Sparkles,
  'bot': Bot,
  'archive': Archive,
  'inbox': Inbox,
  'book-open': BookOpen,
  'book-marked': BookMarked,
  'sticky-note': StickyNote,
  'notepad-text': NotepadText,
  'file': File,
  'file-stack': FileStack,
  'file-code': FileCode,
  'file-spreadsheet': FileSpreadsheet,
  'file-json': FileJson,
  'file-archive': FileArchive,
  'folder-tree': FolderTree,
  'folder-kanban': FolderKanban,
  'folder-plus': FolderPlus,
  'scroll': Scroll,
  'quote': Quote,
  'type': Type,
  'highlighter': Highlighter,
  'kanban': Kanban,
  'list-todo': ListTodo,
  'list-checks': ListChecks,
  'clipboard': Clipboard,
  'clipboard-check': ClipboardCheck,
  'route': Route,
  'signpost': Signpost,
  'gantt-chart': GanttChart,
  'goal': Goal,
  'focus': Focus,
  'binoculars': Binoculars,
  'circle-check': CircleCheck,
  'circle-x': CircleX,
  'circle-alert': CircleAlert,
  'ban': Ban,
  'circle-plus': CirclePlus,
  'binary': Binary,
  'brackets': Brackets,
  'braces': Braces,
  'square-terminal': SquareTerminal,
  'container': Container,
  'circuit-board': CircuitBoard,
  'monitor': Monitor,
  'laptop': Laptop,
  'smartphone': Smartphone,
  'tablet': Tablet,
  'keyboard': Keyboard,
  'printer': Printer,
  'plug': Plug,
  'cable': Cable,
  'bluetooth': Bluetooth,
  'radio-tower': RadioTower,
  'satellite': Satellite,
  'cloud-upload': CloudUpload,
  'cloud-download': CloudDownload,
  'upload': Upload,
  'download': Download,
  'refresh-cw': RefreshCw,
  'repeat': Repeat,
  'git-commit-horizontal': GitCommitHorizontal,
  'git-merge': GitMerge,
  'git-pull-request': GitPullRequest,
  'workflow': Workflow,
  'contact': Contact,
  'handshake': Handshake,
  'presentation': Presentation,
  'crown': Crown,
  'award': Award,
  'badge-check': BadgeCheck,
  'id-card': IdCard,
  'smile': Smile,
  'speech': Speech,
  'headphones': Headphones,
  'phone': Phone,
  'send': Send,
  'share-2': Share2,
  'at-sign': AtSign,
  'rss': Rss,
  'atom': Atom,
  'flask-conical': FlaskConical,
  'microscope': Microscope,
  'telescope': Telescope,
  'dna': Dna,
  'pill': Pill,
  'brain': Brain,
  'heart-pulse': HeartPulse,
  'activity': Activity,
  'test-tube': TestTube,
  'map-pin': MapPin,
  'navigation': Navigation,
  'tent': Tent,
  'palmtree': Palmtree,
  'waves': Waves,
  'wind': Wind,
  'snowflake': Snowflake,
  'umbrella': Umbrella,
  'sunrise': Sunrise,
  'sprout': Sprout,
  'bird': Bird,
  'fish': Fish,
  'cat': Cat,
  'dog': Dog,
  'rabbit': Rabbit,
  'paw-print': PawPrint,
  'store': Store,
  'factory': Factory,
  'warehouse': Warehouse,
  'hospital': Hospital,
  'school': School,
  'landmark': Landmark,
  'castle': Castle,
  'truck': Truck,
  'bus': Bus,
  'train-front': TrainFront,
  'tram-front': TramFront,
  'fuel': Fuel,
  'parking-circle': ParkingCircle,
  'traffic-cone': TrafficCone,
  'construction': Construction,
  'anchor': Anchor,
  'calculator': Calculator,
  'receipt': Receipt,
  'credit-card': CreditCard,
  'banknote': Banknote,
  'piggy-bank': PiggyBank,
  'percent': Percent,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  'coins': Coins,
  'timer': Timer,
  'hourglass': Hourglass,
  'calendar-days': CalendarDays,
  'calendar-check': CalendarCheck,
  'alarm-clock': AlarmClock,
  'history': History,
  'watch': Watch,
  'fingerprint': Fingerprint,
  'unlock': Unlock,
  'vault': Vault,
  'scan': Scan,
  'qr-code': QrCode,
  'eye': Eye,
  'eye-off': EyeOff,
  'scan-search': ScanSearch,
  'hammer': Hammer,
  'cog': Cog,
  'sliders-horizontal': SlidersHorizontal,
  'paintbrush': Paintbrush,
  'palette': Palette,
  'pipette': Pipette,
  'ruler': Ruler,
  'scissors': Scissors,
  'magnet': Magnet,
  'flashlight': Flashlight,
  'apple': Apple,
  'cherry': Cherry,
  'pizza': Pizza,
  'wine': Wine,
  'beer': Beer,
  'cookie': Cookie,
  'cake': Cake,
  'ice-cream-cone': IceCreamCone,
  'shopping-cart': ShoppingCart,
  'shopping-bag': ShoppingBag,
  'dumbbell': Dumbbell,
  'gamepad-2': Gamepad2,
  'dice-5': Dice5,
  'party-popper': PartyPopper,
  'ticket': Ticket,
  'clapperboard': Clapperboard,
  'chart-line': ChartLine,
  'chart-pie': ChartPie,
  'chart-area': ChartArea,
  'table': Table,
  'table-2': Table2,
  'sigma': Sigma,
  'function-square': FunctionSquare,
  'variable': Variable,
  'regex': Regex,
  'component': Component,
  'blocks': Blocks,
  'app-window': AppWindow,
  'network': Network,
  'ethernet-port': EthernetPort,
  'hard-hat': HardHat,
  'rainbow': Rainbow,
  'pentagon': Pentagon,
  'hexagon': Hexagon,
  'triangle': Triangle,
  'diamond': Diamond,
  'asterisk': Asterisk,
  'infinity': InfinityIcon,
  'equal': Equal,
  'plus': Plus,
  'minus': Minus,
  'x': X,
  'check': Check,
  'thumbs-up': ThumbsUp,
  'thumbs-down': ThumbsDown,
  'hand': Hand,
  'pointer': Pointer,
  'mouse-pointer-2': MousePointer2,
  'volume-2': Volume2,
  'contrast': Contrast,
  'sun-moon': SunMoon,
  'eclipse': Eclipse,
  'orbit': Orbit,
  'earth': Earth,
  'cuboid': Cuboid,
  'file-pen': FilePen,
  'file-search': FileSearch,
  'book-copy': BookCopy,
  'wand-sparkles': WandSparkles,
  'sparkle': Sparkle,
  'shield-check': ShieldCheck,
  'shield-alert': ShieldAlert,
  'user-check': UserCheck,
  'user-plus': UserPlus,
  'voicemail': Voicemail,
  'brain-circuit': BrainCircuit,
  'bot-message-square': BotMessageSquare,
  'messages-square': MessagesSquare,
  'folder-git-2': FolderGit2,
  'git-compare': GitCompare,
  'ampersand': Ampersand,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up-right': ArrowUpRight,
  'arrow-up-left': ArrowUpLeft,
  'arrow-down-right': ArrowDownRight,
  'arrow-down-left': ArrowDownLeft,
  'chevron-up': ChevronUp,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevrons-up': ChevronsUp,
  'chevrons-down': ChevronsDown,
  'chevrons-left': ChevronsLeft,
  'chevrons-right': ChevronsRight,
  'corner-down-right': CornerDownRight,
  'corner-down-left': CornerDownLeft,
  'corner-up-right': CornerUpRight,
  'corner-up-left': CornerUpLeft,
  'move': Move,
  'navigation-2': Navigation2,
  'crosshair': Crosshair,
  'locate': Locate,
  'locate-fixed': LocateFixed,
  'map-pin-off': MapPinOff,
  'signpost-big': SignpostBig,
  'user-minus': UserMinus,
  'user-x': UserX,
  'user-cog': UserCog,
  'users-round': UsersRound,
  'user-round': UserRound,
  'user-round-check': UserRoundCheck,
  'user-round-plus': UserRoundPlus,
  'user-round-x': UserRoundX,
  'user-round-cog': UserRoundCog,
  'contact-round': ContactRound,
  'badge': Badge,
  'badge-alert': BadgeAlert,
  'badge-info': BadgeInfo,
  'badge-x': BadgeX,
  'badge-percent': BadgePercent,
  'badge-dollar-sign': BadgeDollarSign,
  'baby': Baby,
  'person-standing': PersonStanding,
  'message-square': MessageSquare,
  'message-square-plus': MessageSquarePlus,
  'message-square-dashed': MessageSquareDashed,
  'message-square-code': MessageSquareCode,
  'message-circle-plus': MessageCirclePlus,
  'message-circle-question': MessageCircleQuestion,
  'megaphone-off': MegaphoneOff,
  'podcast': Podcast,
  'share': Share,
  'phone-call': PhoneCall,
  'phone-forwarded': PhoneForwarded,
  'phone-incoming': PhoneIncoming,
  'phone-outgoing': PhoneOutgoing,
  'phone-missed': PhoneMissed,
  'phone-off': PhoneOff,
  'pencil': Pencil,
  'pen': Pen,
  'pen-tool': PenTool,
  'feather': Feather,
  'eraser': Eraser,
  'paintbrush-2': Paintbrush2,
  'brush': Brush,
  'stamp': Stamp,
  'spray-can': SprayCan,
  'pin-off': PinOff,
  'copy': Copy,
  'clipboard-copy': ClipboardCopy,
  'clipboard-paste': ClipboardPaste,
  'clipboard-x': ClipboardX,
  'trash': Trash,
  'trash-2': Trash2,
  'archive-restore': ArchiveRestore,
  'pause': Pause,
  'play-circle': PlayCircle,
  'pause-circle': PauseCircle,
  'stop-circle': StopCircle,
  'step-forward': StepForward,
  'step-back': StepBack,
  'fast-forward': FastForward,
  'rewind': Rewind,
  'volume': Volume,
  'volume-1': Volume1,
  'volume-x': VolumeX,
  'mic-off': MicOff,
  'video-off': VideoOff,
  'disc': Disc,
  'disc-2': Disc2,
  'disc-3': Disc3,
  'music-2': Music2,
  'music-3': Music3,
  'music-4': Music4,
  'shield-x': ShieldX,
  'shield-minus': ShieldMinus,
  'shield-plus': ShieldPlus,
  'shield-question': ShieldQuestion,
  'shield-ban': ShieldBan,
  'lock-keyhole': LockKeyhole,
  'lock-keyhole-open': LockKeyholeOpen,
  'key-square': KeySquare,
  'scan-face': ScanFace,
  'scan-eye': ScanEye,
  'scan-line': ScanLine,
  'shield-ellipsis': ShieldEllipsis,
  'siren': Siren,
  'chart-column-increasing': ChartColumnIncreasing,
  'chart-column-decreasing': ChartColumnDecreasing,
  'chart-column-stacked': ChartColumnStacked,
  'chart-column-big': ChartColumnBig,
  'chart-spline': ChartSpline,
  'chart-scatter': ChartScatter,
  'candlestick-chart': CandlestickChart,
  'table-properties': TableProperties,
  'pi': Pi,
  'radius': Radius,
  'ratio': Ratio,
  'flask-round': FlaskRound,
  'test-tubes': TestTubes,
  'beaker': Beaker,
  'radiation': Radiation,
  'biohazard': Biohazard,
  'flame-kindling': FlameKindling,
  'laptop-minimal': LaptopMinimal,
  'monitor-smartphone': MonitorSmartphone,
  'monitor-speaker': MonitorSpeaker,
  'monitor-check': MonitorCheck,
  'monitor-x': MonitorX,
  'tablet-smartphone': TabletSmartphone,
  'smartphone-charging': SmartphoneCharging,
  'smartphone-nfc': SmartphoneNfc,
  'speaker': Speaker,
  'projector': Projector,
  'webcam': Webcam,
  'headset': Headset,
  'drill': Drill,
  'nut': Nut,
  'gem': Gem,
  'receipt-text': ReceiptText,
  'receipt-cent': ReceiptCent,
  'receipt-euro': ReceiptEuro,
  'receipt-japanese-yen': ReceiptJapaneseYen,
  'receipt-pound-sterling': ReceiptPoundSterling,
  'circle-dollar-sign': CircleDollarSign,
  'hand-coins': HandCoins,
  'badge-cent': BadgeCent,
  'briefcase-business': BriefcaseBusiness,
  'briefcase-medical': BriefcaseMedical,
  'scale-3d': Scale3d,
  'sun-dim': SunDim,
  'sun-medium': SunMedium,
  'sunset': Sunset,
  'cloud-fog': CloudFog,
  'cloud-hail': CloudHail,
  'cloud-drizzle': CloudDrizzle,
  'tornado': Tornado,
  'tree-deciduous': TreeDeciduous,
  'clover': Clover,
  'mountain-snow': MountainSnow,
  'satellite-dish': SatelliteDish,
  'heart-crack': HeartCrack,
  'heart-handshake': HeartHandshake,
  'syringe': Syringe,
  'cross': Cross,
  'ambulance': Ambulance,
  'accessibility': Accessibility,
  'cup-soda': CupSoda,
  'glass-water': GlassWater,
  'soup': Soup,
  'salad': Salad,
  'croissant': Croissant,
  'sandwich': Sandwich,
  'candy': Candy,
  'popcorn': Popcorn,
  'check-check': CheckCheck,
  'check-circle-2': CheckCircle2,
  'circle-minus': CircleMinus,
  'circle-help': CircleHelp,
  'circle-ellipsis': CircleEllipsis,
  'ellipsis': Ellipsis,
  'ellipsis-vertical': EllipsisVertical,
  'grip': Grip,
  'grip-horizontal': GripHorizontal,
  'grip-vertical': GripVertical,
  'star-half': StarHalf,
  'star-off': StarOff,
  'shapes': Shapes,
  'spline': Spline,
  'octagon': Octagon,
  'scroll-text': ScrollText,
  'book-check': BookCheck,
  'book-open-check': BookOpenCheck,
  'file-question': FileQuestion,
  'gamepad': Gamepad,
  'joystick': Joystick,
  'swords': Swords,
  'sword': Sword,
  'dices': Dices,
  'ticket-check': TicketCheck,
  'ticket-slash': TicketSlash,
  'tickets': Tickets,
  'plane-takeoff': PlaneTakeoff,
  'plane-landing': PlaneLanding,
  'car-front': CarFront,
  'car-taxi-front': CarTaxiFront,
  'luggage': Luggage,
  'code-xml': CodeXml,
  'file-json-2': FileJson2,
  'file-type': FileType,
  'file-type-2': FileType2,
  'git-commit-vertical': GitCommitVertical,
  'inspect': Inspect,
  'squirrel': Squirrel,
  'worm': Worm,
  'stars': Stars,
  'wand': Wand,
  'bell-dot': BellDot,
  'bell-minus': BellMinus,
  'bell-off': BellOff,
  'bell-plus': BellPlus,
  'bell-ring': BellRing,
  'bookmark-check': BookmarkCheck,
  'bookmark-minus': BookmarkMinus,
  'bookmark-plus': BookmarkPlus,
  'bookmark-x': BookmarkX,
  'calendar-check-2': CalendarCheck2,
  'calendar-clock': CalendarClock,
  'calendar-heart': CalendarHeart,
  'calendar-minus': CalendarMinus,
  'calendar-off': CalendarOff,
  'calendar-plus': CalendarPlus,
  'calendar-range': CalendarRange,
  'calendar-search': CalendarSearch,
  'calendar-sync': CalendarSync,
  'calendar-x': CalendarX,
  'calendar-x-2': CalendarX2,
  'circle-check-big': CircleCheckBig,
  'circle-slash': CircleSlash,
  'circle-slash-2': CircleSlash2,
  'circle-stop': CircleStop,
  'circle-pause': CirclePause,
  'circle-play': CirclePlay,
  'clock-1': Clock1,
  'clock-10': Clock10,
  'clock-11': Clock11,
  'clock-12': Clock12,
  'clock-2': Clock2,
  'clock-3': Clock3,
  'clock-4': Clock4,
  'clock-5': Clock5,
  'clock-6': Clock6,
  'clock-7': Clock7,
  'clock-8': Clock8,
  'clock-9': Clock9,
  'clock-alert': ClockAlert,
  'cloud-alert': CloudAlert,
  'cloud-check': CloudCheck,
  'cloud-moon': CloudMoon,
  'cloud-moon-rain': CloudMoonRain,
  'cloud-rain-wind': CloudRainWind,
  'cloud-sun-rain': CloudSunRain,
  'file-audio': FileAudio,
  'file-audio-2': FileAudio2,
  'file-axis-3d': FileAxis3d,
  'file-badge': FileBadge,
  'file-badge-2': FileBadge2,
  'file-box': FileBox,
  'file-chart-column': FileChartColumn,
  'file-chart-column-increasing': FileChartColumnIncreasing,
  'file-chart-line': FileChartLine,
  'file-chart-pie': FileChartPie,
  'file-check-2': FileCheck2,
  'file-clock': FileClock,
  'file-diff': FileDiff,
  'file-digit': FileDigit,
  'file-down': FileDown,
  'file-heart': FileHeart,
  'file-image': FileImage,
  'file-key': FileKey,
  'file-key-2': FileKey2,
  'file-lock': FileLock,
  'file-lock-2': FileLock2,
  'file-minus-2': FileMinus2,
  'file-music': FileMusic,
  'file-output': FileOutput,
  'file-pen-line': FilePenLine,
  'file-plus-2': FilePlus2,
  'file-scan': FileScan,
  'file-sliders': FileSliders,
  'file-symlink': FileSymlink,
  'file-terminal': FileTerminal,
  'file-up': FileUp,
  'file-user': FileUser,
  'file-video': FileVideo,
  'file-video-2': FileVideo2,
  'file-volume': FileVolume,
  'file-volume-2': FileVolume2,
  'file-warning': FileWarning,
  'file-x-2': FileX2,
  'folder-archive': FolderArchive,
  'folder-check': FolderCheck,
  'folder-clock': FolderClock,
  'folder-closed': FolderClosed,
  'folder-code': FolderCode,
  'folder-cog': FolderCog,
  'folder-dot': FolderDot,
  'folder-down': FolderDown,
  'folder-heart': FolderHeart,
  'folder-input': FolderInput,
  'folder-key': FolderKey,
  'folder-minus': FolderMinus,
  'folder-open-dot': FolderOpenDot,
  'folder-output': FolderOutput,
  'folder-pen': FolderPen,
  'folder-root': FolderRoot,
  'folder-search': FolderSearch,
  'folder-search-2': FolderSearch2,
  'folder-symlink': FolderSymlink,
  'folder-sync': FolderSync,
  'folder-up': FolderUp,
  'folder-x': FolderX,
  'mic-vocal': MicVocal,
  'radio-receiver': RadioReceiver,
  'antenna': Antenna,
  'shield-half': ShieldHalf,
  'timer-off': TimerOff,
  'timer-reset': TimerReset,
  'alarm-clock-check': AlarmClockCheck,
  'alarm-clock-minus': AlarmClockMinus,
  'alarm-clock-off': AlarmClockOff,
  'alarm-clock-plus': AlarmClockPlus,
  'footprints': Footprints,
  'life-buoy': LifeBuoy,
  'sailboat': Sailboat,
  'volleyball': Volleyball,
};

export function getPageLucideIcon(id: string): LucideIcon | null {
  return (ICONS as Record<string, LucideIcon>)[id] ?? null;
}

export { PAGE_LUCIDE_ICONS };
