import { z } from 'zod';
import { isPageBrandIconId } from './page-brand-icons.js';

export { PAGE_BRAND_ICONS, PAGE_BRAND_ICON_IDS, getPageBrandIcon, isPageBrandIconId } from './page-brand-icons.js';
export type { PageBrandIconId } from './page-brand-icons.js';

export const PageIconKindEnum = z.enum(['emoji', 'lucide', 'image', 'brand']);
export type PageIconKind = z.infer<typeof PageIconKindEnum>;

/**
 * Closed Lucide catalogue a page mark may carry. Kept here so the PATCH
 * validator and the picker cannot disagree about which ids are legal.
 * HardDrive / Globe stay out — those are sidebar chrome for local / Confluence
 * spaces, and a page wearing either would be indistinguishable from that state.
 */
export const PAGE_LUCIDE_ICONS = [
  { value: 'book', label: 'Book' },
  { value: 'bookmark', label: 'Bookmark' },
  { value: 'file-text', label: 'Document' },
  { value: 'files', label: 'Files' },
  { value: 'folder', label: 'Folder' },
  { value: 'folder-open', label: 'Open folder' },
  { value: 'clipboard-list', label: 'Checklist' },
  { value: 'notebook', label: 'Notebook' },
  { value: 'newspaper', label: 'Newspaper' },
  { value: 'library', label: 'Library' },
  { value: 'rocket', label: 'Rocket' },
  { value: 'lightbulb', label: 'Idea' },
  { value: 'zap', label: 'Zap' },
  { value: 'star', label: 'Star' },
  { value: 'heart', label: 'Heart' },
  { value: 'flag', label: 'Flag' },
  { value: 'target', label: 'Target' },
  { value: 'compass', label: 'Compass' },
  { value: 'map', label: 'Map' },
  { value: 'milestone', label: 'Milestone' },
  { value: 'code', label: 'Code' },
  { value: 'terminal', label: 'Terminal' },
  { value: 'bug', label: 'Bug' },
  { value: 'git-branch', label: 'Branch' },
  { value: 'database', label: 'Database' },
  { value: 'server', label: 'Server' },
  { value: 'cpu', label: 'CPU' },
  { value: 'wifi', label: 'Network' },
  { value: 'lock', label: 'Lock' },
  { value: 'shield', label: 'Shield' },
  { value: 'key', label: 'Key' },
  { value: 'users', label: 'Team' },
  { value: 'user', label: 'Person' },
  { value: 'briefcase', label: 'Work' },
  { value: 'building-2', label: 'Building' },
  { value: 'calendar', label: 'Calendar' },
  { value: 'clock', label: 'Clock' },
  { value: 'mail', label: 'Mail' },
  { value: 'message-circle', label: 'Chat' },
  { value: 'bell', label: 'Bell' },
  { value: 'settings', label: 'Settings' },
  { value: 'wrench', label: 'Wrench' },
  { value: 'search', label: 'Search' },
  { value: 'filter', label: 'Filter' },
  { value: 'list', label: 'List' },
  { value: 'layout-grid', label: 'Grid' },
  { value: 'layers', label: 'Layers' },
  { value: 'puzzle', label: 'Puzzle' },
  { value: 'boxes', label: 'Boxes' },
  { value: 'package', label: 'Package' },
  { value: 'check-circle', label: 'Done' },
  { value: 'alert-triangle', label: 'Warning' },
  { value: 'info', label: 'Info' },
  { value: 'help-circle', label: 'Help' },
  { value: 'circle-dot', label: 'Point' },
  { value: 'pen-line', label: 'Edit' },
  { value: 'image', label: 'Image' },
  { value: 'camera', label: 'Camera' },
  { value: 'video', label: 'Video' },
  { value: 'music', label: 'Music' },
  { value: 'mic', label: 'Mic' },
  { value: 'play', label: 'Play' },
  { value: 'film', label: 'Film' },
  { value: 'leaf', label: 'Leaf' },
  { value: 'sun', label: 'Sun' },
  { value: 'moon', label: 'Moon' },
  { value: 'cloud', label: 'Cloud' },
  { value: 'droplet', label: 'Drop' },
  { value: 'flame', label: 'Flame' },
  { value: 'mountain', label: 'Mountain' },
  { value: 'tree-pine', label: 'Tree' },
  { value: 'flower-2', label: 'Flower' },
  { value: 'car', label: 'Car' },
  { value: 'plane', label: 'Plane' },
  { value: 'ship', label: 'Ship' },
  { value: 'bike', label: 'Bike' },
  { value: 'house', label: 'Home' },
  { value: 'coffee', label: 'Coffee' },
  { value: 'utensils', label: 'Food' },
  { value: 'gift', label: 'Gift' },
  { value: 'trophy', label: 'Trophy' },
  { value: 'medal', label: 'Medal' },
  { value: 'link', label: 'Link' },
  { value: 'paperclip', label: 'Attachment' },
  { value: 'pin', label: 'Pin' },
  { value: 'tag', label: 'Tag' },
  { value: 'hash', label: 'Hash' },
  { value: 'chart-column', label: 'Chart' },
  { value: 'graduation-cap', label: 'Learning' },
  { value: 'stethoscope', label: 'Health' },
  { value: 'scale', label: 'Legal' },
  { value: 'wallet', label: 'Finance' },
  { value: 'megaphone', label: 'Announce' },
  { value: 'sparkles', label: 'Sparkles' },
  { value: 'bot', label: 'Bot' },
  { value: 'archive', label: 'Archive' },
  { value: 'inbox', label: 'Inbox' },
  { value: 'book-open', label: 'Open book' },
  { value: 'book-marked', label: 'Marked book' },
  { value: 'sticky-note', label: 'Sticky note' },
  { value: 'notepad-text', label: 'Notes' },
  { value: 'file', label: 'File' },
  { value: 'file-stack', label: 'File stack' },
  { value: 'file-code', label: 'Code file' },
  { value: 'file-spreadsheet', label: 'Spreadsheet' },
  { value: 'file-json', label: 'JSON' },
  { value: 'file-archive', label: 'Zip file' },
  { value: 'folder-tree', label: 'Folder tree' },
  { value: 'folder-kanban', label: 'Board folder' },
  { value: 'folder-plus', label: 'New folder' },
  { value: 'scroll', label: 'Scroll' },
  { value: 'quote', label: 'Quote' },
  { value: 'type', label: 'Text' },
  { value: 'highlighter', label: 'Highlight' },
  { value: 'kanban', label: 'Board' },
  { value: 'list-todo', label: 'To-do' },
  { value: 'list-checks', label: 'Checks' },
  { value: 'clipboard', label: 'Clipboard' },
  { value: 'clipboard-check', label: 'Checked list' },
  { value: 'route', label: 'Route' },
  { value: 'signpost', label: 'Signpost' },
  { value: 'gantt-chart', label: 'Timeline' },
  { value: 'goal', label: 'Goal' },
  { value: 'focus', label: 'Focus' },
  { value: 'binoculars', label: 'Look' },
  { value: 'circle-check', label: 'Complete' },
  { value: 'circle-x', label: 'Cancel' },
  { value: 'circle-alert', label: 'Alert' },
  { value: 'ban', label: 'Blocked' },
  { value: 'circle-plus', label: 'Add' },
  { value: 'binary', label: 'Binary' },
  { value: 'brackets', label: 'Brackets' },
  { value: 'braces', label: 'Braces' },
  { value: 'square-terminal', label: 'Shell' },
  { value: 'container', label: 'Container' },
  { value: 'circuit-board', label: 'Circuit' },
  { value: 'monitor', label: 'Monitor' },
  { value: 'laptop', label: 'Laptop' },
  { value: 'smartphone', label: 'Phone' },
  { value: 'tablet', label: 'Tablet' },
  { value: 'keyboard', label: 'Keyboard' },
  { value: 'printer', label: 'Printer' },
  { value: 'plug', label: 'Power' },
  { value: 'cable', label: 'Cable' },
  { value: 'bluetooth', label: 'Bluetooth' },
  { value: 'radio-tower', label: 'Antenna' },
  { value: 'satellite', label: 'Satellite' },
  { value: 'cloud-upload', label: 'Upload cloud' },
  { value: 'cloud-download', label: 'Download cloud' },
  { value: 'upload', label: 'Upload' },
  { value: 'download', label: 'Download' },
  { value: 'refresh-cw', label: 'Refresh' },
  { value: 'repeat', label: 'Repeat' },
  { value: 'git-commit-horizontal', label: 'Commit' },
  { value: 'git-merge', label: 'Merge' },
  { value: 'git-pull-request', label: 'Pull request' },
  { value: 'workflow', label: 'Workflow' },
  { value: 'contact', label: 'Contact' },
  { value: 'handshake', label: 'Handshake' },
  { value: 'presentation', label: 'Present' },
  { value: 'crown', label: 'Crown' },
  { value: 'award', label: 'Award' },
  { value: 'badge-check', label: 'Verified' },
  { value: 'id-card', label: 'ID' },
  { value: 'smile', label: 'Smile' },
  { value: 'speech', label: 'Speak' },
  { value: 'headphones', label: 'Headset' },
  { value: 'phone', label: 'Call' },
  { value: 'send', label: 'Send' },
  { value: 'share-2', label: 'Share' },
  { value: 'at-sign', label: 'Mention' },
  { value: 'rss', label: 'Feed' },
  { value: 'atom', label: 'Atom' },
  { value: 'flask-conical', label: 'Lab' },
  { value: 'microscope', label: 'Microscope' },
  { value: 'telescope', label: 'Telescope' },
  { value: 'dna', label: 'DNA' },
  { value: 'pill', label: 'Medicine' },
  { value: 'brain', label: 'Brain' },
  { value: 'heart-pulse', label: 'Pulse' },
  { value: 'activity', label: 'Activity' },
  { value: 'test-tube', label: 'Test' },
  { value: 'map-pin', label: 'Location' },
  { value: 'navigation', label: 'Navigate' },
  { value: 'tent', label: 'Camp' },
  { value: 'palmtree', label: 'Palm' },
  { value: 'waves', label: 'Waves' },
  { value: 'wind', label: 'Wind' },
  { value: 'snowflake', label: 'Snow' },
  { value: 'umbrella', label: 'Rain' },
  { value: 'sunrise', label: 'Sunrise' },
  { value: 'sprout', label: 'Sprout' },
  { value: 'bird', label: 'Bird' },
  { value: 'fish', label: 'Fish' },
  { value: 'cat', label: 'Cat' },
  { value: 'dog', label: 'Dog' },
  { value: 'rabbit', label: 'Rabbit' },
  { value: 'paw-print', label: 'Paw' },
  { value: 'store', label: 'Shop' },
  { value: 'factory', label: 'Factory' },
  { value: 'warehouse', label: 'Warehouse' },
  { value: 'hospital', label: 'Hospital' },
  { value: 'school', label: 'School' },
  { value: 'landmark', label: 'Landmark' },
  { value: 'castle', label: 'Castle' },
  { value: 'truck', label: 'Truck' },
  { value: 'bus', label: 'Bus' },
  { value: 'train-front', label: 'Train' },
  { value: 'tram-front', label: 'Tram' },
  { value: 'fuel', label: 'Fuel' },
  { value: 'parking-circle', label: 'Parking' },
  { value: 'traffic-cone', label: 'Cone' },
  { value: 'construction', label: 'Build' },
  { value: 'anchor', label: 'Anchor' },
  { value: 'calculator', label: 'Calculator' },
  { value: 'receipt', label: 'Receipt' },
  { value: 'credit-card', label: 'Card' },
  { value: 'banknote', label: 'Cash' },
  { value: 'piggy-bank', label: 'Savings' },
  { value: 'percent', label: 'Percent' },
  { value: 'trending-up', label: 'Trending up' },
  { value: 'trending-down', label: 'Trending down' },
  { value: 'coins', label: 'Coins' },
  { value: 'timer', label: 'Timer' },
  { value: 'hourglass', label: 'Hourglass' },
  { value: 'calendar-days', label: 'Dates' },
  { value: 'calendar-check', label: 'Event' },
  { value: 'alarm-clock', label: 'Alarm' },
  { value: 'history', label: 'History' },
  { value: 'watch', label: 'Watch' },
  { value: 'fingerprint', label: 'Fingerprint' },
  { value: 'unlock', label: 'Unlock' },
  { value: 'vault', label: 'Vault' },
  { value: 'scan', label: 'Scan' },
  { value: 'qr-code', label: 'QR' },
  { value: 'eye', label: 'View' },
  { value: 'eye-off', label: 'Hidden' },
  { value: 'scan-search', label: 'Inspect' },
  { value: 'hammer', label: 'Hammer' },
  { value: 'cog', label: 'Gear' },
  { value: 'sliders-horizontal', label: 'Sliders' },
  { value: 'paintbrush', label: 'Brush' },
  { value: 'palette', label: 'Palette' },
  { value: 'pipette', label: 'Sample' },
  { value: 'ruler', label: 'Ruler' },
  { value: 'scissors', label: 'Cut' },
  { value: 'magnet', label: 'Magnet' },
  { value: 'flashlight', label: 'Light' },
  { value: 'apple', label: 'Apple' },
  { value: 'cherry', label: 'Cherry' },
  { value: 'pizza', label: 'Pizza' },
  { value: 'wine', label: 'Wine' },
  { value: 'beer', label: 'Beer' },
  { value: 'cookie', label: 'Cookie' },
  { value: 'cake', label: 'Cake' },
  { value: 'ice-cream-cone', label: 'Ice cream' },
  { value: 'shopping-cart', label: 'Cart' },
  { value: 'shopping-bag', label: 'Bag' },
  { value: 'dumbbell', label: 'Fitness' },
  { value: 'gamepad-2', label: 'Games' },
  { value: 'dice-5', label: 'Dice' },
  { value: 'party-popper', label: 'Celebrate' },
  { value: 'ticket', label: 'Ticket' },
  { value: 'clapperboard', label: 'Scene' },
  { value: 'chart-line', label: 'Line chart' },
  { value: 'chart-pie', label: 'Pie chart' },
  { value: 'chart-area', label: 'Area chart' },
  { value: 'table', label: 'Table' },
  { value: 'table-2', label: 'Spreadsheet table' },
  { value: 'sigma', label: 'Sigma' },
  { value: 'function-square', label: 'Function' },
  { value: 'variable', label: 'Variable' },
  { value: 'regex', label: 'Regex' },
  { value: 'component', label: 'Component' },
  { value: 'blocks', label: 'Blocks' },
  { value: 'app-window', label: 'Window' },
  { value: 'network', label: 'Graph' },
  { value: 'ethernet-port', label: 'Ethernet' },
  { value: 'hard-hat', label: 'Hard hat' },
  { value: 'rainbow', label: 'Rainbow' },
  { value: 'pentagon', label: 'Pentagon' },
  { value: 'hexagon', label: 'Hexagon' },
  { value: 'triangle', label: 'Triangle' },
  { value: 'diamond', label: 'Diamond' },
  { value: 'asterisk', label: 'Asterisk' },
  { value: 'infinity', label: 'Infinity' },
  { value: 'equal', label: 'Equal' },
  { value: 'plus', label: 'Plus' },
  { value: 'minus', label: 'Minus' },
  { value: 'x', label: 'Close' },
  { value: 'check', label: 'Check' },
  { value: 'thumbs-up', label: 'Thumbs up' },
  { value: 'thumbs-down', label: 'Thumbs down' },
  { value: 'hand', label: 'Hand' },
  { value: 'pointer', label: 'Pointer' },
  { value: 'mouse-pointer-2', label: 'Cursor' },
  { value: 'volume-2', label: 'Volume' },
  { value: 'contrast', label: 'Contrast' },
  { value: 'sun-moon', label: 'Day night' },
  { value: 'eclipse', label: 'Eclipse' },
  { value: 'orbit', label: 'Orbit' },
  { value: 'earth', label: 'Earth' },
  { value: 'cuboid', label: 'Cube' },
  { value: 'file-pen', label: 'Edit file' },
  { value: 'file-search', label: 'Search file' },
  { value: 'book-copy', label: 'Copy book' },
  { value: 'wand-sparkles', label: 'Wand' },
  { value: 'sparkle', label: 'Sparkle' },
  { value: 'shield-check', label: 'Shield check' },
  { value: 'shield-alert', label: 'Shield alert' },
  { value: 'user-check', label: 'User check' },
  { value: 'user-plus', label: 'Add user' },
  { value: 'voicemail', label: 'Voicemail' },
  { value: 'brain-circuit', label: 'Neural' },
  { value: 'bot-message-square', label: 'Chat bot' },
  { value: 'messages-square', label: 'Threads' },
  { value: 'folder-git-2', label: 'Git folder' },
  { value: 'git-compare', label: 'Compare' },
  { value: 'ampersand', label: 'And' },
  { value: 'arrow-up', label: 'Arrow Up' },
  { value: 'arrow-down', label: 'Arrow Down' },
  { value: 'arrow-left', label: 'Arrow Left' },
  { value: 'arrow-right', label: 'Arrow Right' },
  { value: 'arrow-up-right', label: 'Arrow Up Right' },
  { value: 'arrow-up-left', label: 'Arrow Up Left' },
  { value: 'arrow-down-right', label: 'Arrow Down Right' },
  { value: 'arrow-down-left', label: 'Arrow Down Left' },
  { value: 'chevron-up', label: 'Chevron Up' },
  { value: 'chevron-down', label: 'Chevron Down' },
  { value: 'chevron-left', label: 'Chevron Left' },
  { value: 'chevron-right', label: 'Chevron Right' },
  { value: 'chevrons-up', label: 'Chevrons Up' },
  { value: 'chevrons-down', label: 'Chevrons Down' },
  { value: 'chevrons-left', label: 'Chevrons Left' },
  { value: 'chevrons-right', label: 'Chevrons Right' },
  { value: 'corner-down-right', label: 'Corner Down Right' },
  { value: 'corner-down-left', label: 'Corner Down Left' },
  { value: 'corner-up-right', label: 'Corner Up Right' },
  { value: 'corner-up-left', label: 'Corner Up Left' },
  { value: 'move', label: 'Move' },
  { value: 'navigation-2', label: 'Navigation 2' },
  { value: 'crosshair', label: 'Crosshair' },
  { value: 'locate', label: 'Locate' },
  { value: 'locate-fixed', label: 'Locate Fixed' },
  { value: 'map-pin-off', label: 'Map Pin Off' },
  { value: 'signpost-big', label: 'Signpost Big' },
  { value: 'user-minus', label: 'User Minus' },
  { value: 'user-x', label: 'User X' },
  { value: 'user-cog', label: 'User Cog' },
  { value: 'users-round', label: 'Users Round' },
  { value: 'user-round', label: 'User Round' },
  { value: 'user-round-check', label: 'User Round Check' },
  { value: 'user-round-plus', label: 'User Round Plus' },
  { value: 'user-round-x', label: 'User Round X' },
  { value: 'user-round-cog', label: 'User Round Cog' },
  { value: 'contact-round', label: 'Contact Round' },
  { value: 'badge', label: 'Badge' },
  { value: 'badge-alert', label: 'Badge Alert' },
  { value: 'badge-info', label: 'Badge Info' },
  { value: 'badge-x', label: 'Badge X' },
  { value: 'badge-percent', label: 'Badge Percent' },
  { value: 'badge-dollar-sign', label: 'Badge Dollar Sign' },
  { value: 'baby', label: 'Baby' },
  { value: 'person-standing', label: 'Person Standing' },
  { value: 'message-square', label: 'Message Square' },
  { value: 'message-square-plus', label: 'Message Square Plus' },
  { value: 'message-square-dashed', label: 'Message Square Dashed' },
  { value: 'message-square-code', label: 'Message Square Code' },
  { value: 'message-circle-plus', label: 'Message Circle Plus' },
  { value: 'message-circle-question', label: 'Message Circle Question' },
  { value: 'megaphone-off', label: 'Megaphone Off' },
  { value: 'podcast', label: 'Podcast' },
  { value: 'share', label: 'Share' },
  { value: 'phone-call', label: 'Phone Call' },
  { value: 'phone-forwarded', label: 'Phone Forwarded' },
  { value: 'phone-incoming', label: 'Phone Incoming' },
  { value: 'phone-outgoing', label: 'Phone Outgoing' },
  { value: 'phone-missed', label: 'Phone Missed' },
  { value: 'phone-off', label: 'Phone Off' },
  { value: 'pencil', label: 'Pencil' },
  { value: 'pen', label: 'Pen' },
  { value: 'pen-tool', label: 'Pen Tool' },
  { value: 'feather', label: 'Feather' },
  { value: 'eraser', label: 'Eraser' },
  { value: 'paintbrush-2', label: 'Paintbrush 2' },
  { value: 'brush', label: 'Brush' },
  { value: 'stamp', label: 'Stamp' },
  { value: 'spray-can', label: 'Spray Can' },
  { value: 'pin-off', label: 'Pin Off' },
  { value: 'copy', label: 'Copy' },
  { value: 'clipboard-copy', label: 'Clipboard Copy' },
  { value: 'clipboard-paste', label: 'Clipboard Paste' },
  { value: 'clipboard-x', label: 'Clipboard X' },
  { value: 'trash', label: 'Trash' },
  { value: 'trash-2', label: 'Trash 2' },
  { value: 'archive-restore', label: 'Archive Restore' },
  { value: 'pause', label: 'Pause' },
  { value: 'play-circle', label: 'Play Circle' },
  { value: 'pause-circle', label: 'Pause Circle' },
  { value: 'stop-circle', label: 'Stop Circle' },
  { value: 'step-forward', label: 'Step Forward' },
  { value: 'step-back', label: 'Step Back' },
  { value: 'fast-forward', label: 'Fast Forward' },
  { value: 'rewind', label: 'Rewind' },
  { value: 'volume', label: 'Volume' },
  { value: 'volume-1', label: 'Volume 1' },
  { value: 'volume-x', label: 'Volume X' },
  { value: 'mic-off', label: 'Mic Off' },
  { value: 'video-off', label: 'Video Off' },
  { value: 'disc', label: 'Disc' },
  { value: 'disc-2', label: 'Disc 2' },
  { value: 'disc-3', label: 'Disc 3' },
  { value: 'music-2', label: 'Music 2' },
  { value: 'music-3', label: 'Music 3' },
  { value: 'music-4', label: 'Music 4' },
  { value: 'shield-x', label: 'Shield X' },
  { value: 'shield-minus', label: 'Shield Minus' },
  { value: 'shield-plus', label: 'Shield Plus' },
  { value: 'shield-question', label: 'Shield Question' },
  { value: 'shield-ban', label: 'Shield Ban' },
  { value: 'lock-keyhole', label: 'Lock Keyhole' },
  { value: 'lock-keyhole-open', label: 'Lock Keyhole Open' },
  { value: 'key-square', label: 'Key Square' },
  { value: 'scan-face', label: 'Scan Face' },
  { value: 'scan-eye', label: 'Scan Eye' },
  { value: 'scan-line', label: 'Scan Line' },
  { value: 'shield-ellipsis', label: 'Shield Ellipsis' },
  { value: 'siren', label: 'Siren' },
  { value: 'chart-column-increasing', label: 'Chart Column Increasing' },
  { value: 'chart-column-decreasing', label: 'Chart Column Decreasing' },
  { value: 'chart-column-stacked', label: 'Chart Column Stacked' },
  { value: 'chart-column-big', label: 'Chart Column Big' },
  { value: 'chart-spline', label: 'Chart Spline' },
  { value: 'chart-scatter', label: 'Chart Scatter' },
  { value: 'candlestick-chart', label: 'Candlestick Chart' },
  { value: 'table-properties', label: 'Table Properties' },
  { value: 'pi', label: 'Pi' },
  { value: 'radius', label: 'Radius' },
  { value: 'ratio', label: 'Ratio' },
  { value: 'flask-round', label: 'Flask Round' },
  { value: 'test-tubes', label: 'Test Tubes' },
  { value: 'beaker', label: 'Beaker' },
  { value: 'radiation', label: 'Radiation' },
  { value: 'biohazard', label: 'Biohazard' },
  { value: 'flame-kindling', label: 'Flame Kindling' },
  { value: 'laptop-minimal', label: 'Laptop Minimal' },
  { value: 'monitor-smartphone', label: 'Monitor Smartphone' },
  { value: 'monitor-speaker', label: 'Monitor Speaker' },
  { value: 'monitor-check', label: 'Monitor Check' },
  { value: 'monitor-x', label: 'Monitor X' },
  { value: 'tablet-smartphone', label: 'Tablet Smartphone' },
  { value: 'smartphone-charging', label: 'Smartphone Charging' },
  { value: 'smartphone-nfc', label: 'Smartphone Nfc' },
  { value: 'speaker', label: 'Speaker' },
  { value: 'projector', label: 'Projector' },
  { value: 'webcam', label: 'Webcam' },
  { value: 'headset', label: 'Headset' },
  { value: 'drill', label: 'Drill' },
  { value: 'nut', label: 'Nut' },
  { value: 'gem', label: 'Gem' },
  { value: 'receipt-text', label: 'Receipt Text' },
  { value: 'receipt-cent', label: 'Receipt Cent' },
  { value: 'receipt-euro', label: 'Receipt Euro' },
  { value: 'receipt-japanese-yen', label: 'Receipt Japanese Yen' },
  { value: 'receipt-pound-sterling', label: 'Receipt Pound Sterling' },
  { value: 'circle-dollar-sign', label: 'Circle Dollar Sign' },
  { value: 'hand-coins', label: 'Hand Coins' },
  { value: 'badge-cent', label: 'Badge Cent' },
  { value: 'briefcase-business', label: 'Briefcase Business' },
  { value: 'briefcase-medical', label: 'Briefcase Medical' },
  { value: 'scale-3d', label: 'Scale 3d' },
  { value: 'sun-dim', label: 'Sun Dim' },
  { value: 'sun-medium', label: 'Sun Medium' },
  { value: 'sunset', label: 'Sunset' },
  { value: 'cloud-fog', label: 'Cloud Fog' },
  { value: 'cloud-hail', label: 'Cloud Hail' },
  { value: 'cloud-drizzle', label: 'Cloud Drizzle' },
  { value: 'tornado', label: 'Tornado' },
  { value: 'tree-deciduous', label: 'Tree Deciduous' },
  { value: 'clover', label: 'Clover' },
  { value: 'mountain-snow', label: 'Mountain Snow' },
  { value: 'satellite-dish', label: 'Satellite Dish' },
  { value: 'heart-crack', label: 'Heart Crack' },
  { value: 'heart-handshake', label: 'Heart Handshake' },
  { value: 'syringe', label: 'Syringe' },
  { value: 'cross', label: 'Cross' },
  { value: 'ambulance', label: 'Ambulance' },
  { value: 'accessibility', label: 'Accessibility' },
  { value: 'cup-soda', label: 'Cup Soda' },
  { value: 'glass-water', label: 'Glass Water' },
  { value: 'soup', label: 'Soup' },
  { value: 'salad', label: 'Salad' },
  { value: 'croissant', label: 'Croissant' },
  { value: 'sandwich', label: 'Sandwich' },
  { value: 'candy', label: 'Candy' },
  { value: 'popcorn', label: 'Popcorn' },
  { value: 'check-check', label: 'Check Check' },
  { value: 'check-circle-2', label: 'Check Circle 2' },
  { value: 'circle-minus', label: 'Circle Minus' },
  { value: 'circle-help', label: 'Circle Help' },
  { value: 'circle-ellipsis', label: 'Circle Ellipsis' },
  { value: 'ellipsis', label: 'Ellipsis' },
  { value: 'ellipsis-vertical', label: 'Ellipsis Vertical' },
  { value: 'grip', label: 'Grip' },
  { value: 'grip-horizontal', label: 'Grip Horizontal' },
  { value: 'grip-vertical', label: 'Grip Vertical' },
  { value: 'star-half', label: 'Star Half' },
  { value: 'star-off', label: 'Star Off' },
  { value: 'shapes', label: 'Shapes' },
  { value: 'spline', label: 'Spline' },
  { value: 'octagon', label: 'Octagon' },
  { value: 'scroll-text', label: 'Scroll Text' },
  { value: 'book-check', label: 'Book Check' },
  { value: 'book-open-check', label: 'Book Open Check' },
  { value: 'file-question', label: 'File Question' },
  { value: 'gamepad', label: 'Gamepad' },
  { value: 'joystick', label: 'Joystick' },
  { value: 'swords', label: 'Swords' },
  { value: 'sword', label: 'Sword' },
  { value: 'dices', label: 'Dices' },
  { value: 'ticket-check', label: 'Ticket Check' },
  { value: 'ticket-slash', label: 'Ticket Slash' },
  { value: 'tickets', label: 'Tickets' },
  { value: 'plane-takeoff', label: 'Plane Takeoff' },
  { value: 'plane-landing', label: 'Plane Landing' },
  { value: 'car-front', label: 'Car Front' },
  { value: 'car-taxi-front', label: 'Car Taxi Front' },
  { value: 'luggage', label: 'Luggage' },
  { value: 'code-xml', label: 'Code Xml' },
  { value: 'file-json-2', label: 'File Json 2' },
  { value: 'file-type', label: 'File Type' },
  { value: 'file-type-2', label: 'File Type 2' },
  { value: 'git-commit-vertical', label: 'Git Commit Vertical' },
  { value: 'inspect', label: 'Inspect' },
  { value: 'squirrel', label: 'Squirrel' },
  { value: 'worm', label: 'Worm' },
  { value: 'stars', label: 'Stars' },
  { value: 'wand', label: 'Wand' },
  { value: 'bell-dot', label: 'Bell Dot' },
  { value: 'bell-minus', label: 'Bell Minus' },
  { value: 'bell-off', label: 'Bell Off' },
  { value: 'bell-plus', label: 'Bell Plus' },
  { value: 'bell-ring', label: 'Bell Ring' },
  { value: 'bookmark-check', label: 'Bookmark Check' },
  { value: 'bookmark-minus', label: 'Bookmark Minus' },
  { value: 'bookmark-plus', label: 'Bookmark Plus' },
  { value: 'bookmark-x', label: 'Bookmark X' },
  { value: 'calendar-check-2', label: 'Calendar Check 2' },
  { value: 'calendar-clock', label: 'Calendar Clock' },
  { value: 'calendar-heart', label: 'Calendar Heart' },
  { value: 'calendar-minus', label: 'Calendar Minus' },
  { value: 'calendar-off', label: 'Calendar Off' },
  { value: 'calendar-plus', label: 'Calendar Plus' },
  { value: 'calendar-range', label: 'Calendar Range' },
  { value: 'calendar-search', label: 'Calendar Search' },
  { value: 'calendar-sync', label: 'Calendar Sync' },
  { value: 'calendar-x', label: 'Calendar X' },
  { value: 'calendar-x-2', label: 'Calendar X 2' },
  { value: 'circle-check-big', label: 'Circle Check Big' },
  { value: 'circle-slash', label: 'Circle Slash' },
  { value: 'circle-slash-2', label: 'Circle Slash 2' },
  { value: 'circle-stop', label: 'Circle Stop' },
  { value: 'circle-pause', label: 'Circle Pause' },
  { value: 'circle-play', label: 'Circle Play' },
  { value: 'clock-1', label: 'Clock 1' },
  { value: 'clock-10', label: 'Clock 10' },
  { value: 'clock-11', label: 'Clock 11' },
  { value: 'clock-12', label: 'Clock 12' },
  { value: 'clock-2', label: 'Clock 2' },
  { value: 'clock-3', label: 'Clock 3' },
  { value: 'clock-4', label: 'Clock 4' },
  { value: 'clock-5', label: 'Clock 5' },
  { value: 'clock-6', label: 'Clock 6' },
  { value: 'clock-7', label: 'Clock 7' },
  { value: 'clock-8', label: 'Clock 8' },
  { value: 'clock-9', label: 'Clock 9' },
  { value: 'clock-alert', label: 'Clock Alert' },
  { value: 'cloud-alert', label: 'Cloud Alert' },
  { value: 'cloud-check', label: 'Cloud Check' },
  { value: 'cloud-moon', label: 'Cloud Moon' },
  { value: 'cloud-moon-rain', label: 'Cloud Moon Rain' },
  { value: 'cloud-rain-wind', label: 'Cloud Rain Wind' },
  { value: 'cloud-sun-rain', label: 'Cloud Sun Rain' },
  { value: 'file-audio', label: 'File Audio' },
  { value: 'file-audio-2', label: 'File Audio 2' },
  { value: 'file-axis-3d', label: 'File Axis 3d' },
  { value: 'file-badge', label: 'File Badge' },
  { value: 'file-badge-2', label: 'File Badge 2' },
  { value: 'file-box', label: 'File Box' },
  { value: 'file-chart-column', label: 'File Chart Column' },
  { value: 'file-chart-column-increasing', label: 'File Chart Column Increasing' },
  { value: 'file-chart-line', label: 'File Chart Line' },
  { value: 'file-chart-pie', label: 'File Chart Pie' },
  { value: 'file-check-2', label: 'File Check 2' },
  { value: 'file-clock', label: 'File Clock' },
  { value: 'file-diff', label: 'File Diff' },
  { value: 'file-digit', label: 'File Digit' },
  { value: 'file-down', label: 'File Down' },
  { value: 'file-heart', label: 'File Heart' },
  { value: 'file-image', label: 'File Image' },
  { value: 'file-key', label: 'File Key' },
  { value: 'file-key-2', label: 'File Key 2' },
  { value: 'file-lock', label: 'File Lock' },
  { value: 'file-lock-2', label: 'File Lock 2' },
  { value: 'file-minus-2', label: 'File Minus 2' },
  { value: 'file-music', label: 'File Music' },
  { value: 'file-output', label: 'File Output' },
  { value: 'file-pen-line', label: 'File Pen Line' },
  { value: 'file-plus-2', label: 'File Plus 2' },
  { value: 'file-scan', label: 'File Scan' },
  { value: 'file-sliders', label: 'File Sliders' },
  { value: 'file-symlink', label: 'File Symlink' },
  { value: 'file-terminal', label: 'File Terminal' },
  { value: 'file-up', label: 'File Up' },
  { value: 'file-user', label: 'File User' },
  { value: 'file-video', label: 'File Video' },
  { value: 'file-video-2', label: 'File Video 2' },
  { value: 'file-volume', label: 'File Volume' },
  { value: 'file-volume-2', label: 'File Volume 2' },
  { value: 'file-warning', label: 'File Warning' },
  { value: 'file-x-2', label: 'File X 2' },
  { value: 'folder-archive', label: 'Folder Archive' },
  { value: 'folder-check', label: 'Folder Check' },
  { value: 'folder-clock', label: 'Folder Clock' },
  { value: 'folder-closed', label: 'Folder Closed' },
  { value: 'folder-code', label: 'Folder Code' },
  { value: 'folder-cog', label: 'Folder Cog' },
  { value: 'folder-dot', label: 'Folder Dot' },
  { value: 'folder-down', label: 'Folder Down' },
  { value: 'folder-heart', label: 'Folder Heart' },
  { value: 'folder-input', label: 'Folder Input' },
  { value: 'folder-key', label: 'Folder Key' },
  { value: 'folder-minus', label: 'Folder Minus' },
  { value: 'folder-open-dot', label: 'Folder Open Dot' },
  { value: 'folder-output', label: 'Folder Output' },
  { value: 'folder-pen', label: 'Folder Pen' },
  { value: 'folder-root', label: 'Folder Root' },
  { value: 'folder-search', label: 'Folder Search' },
  { value: 'folder-search-2', label: 'Folder Search 2' },
  { value: 'folder-symlink', label: 'Folder Symlink' },
  { value: 'folder-sync', label: 'Folder Sync' },
  { value: 'folder-up', label: 'Folder Up' },
  { value: 'folder-x', label: 'Folder X' },
  { value: 'mic-vocal', label: 'Mic Vocal' },
  { value: 'radio-receiver', label: 'Radio Receiver' },
  { value: 'antenna', label: 'Antenna' },
  { value: 'shield-half', label: 'Shield Half' },
  { value: 'timer-off', label: 'Timer Off' },
  { value: 'timer-reset', label: 'Timer Reset' },
  { value: 'alarm-clock-check', label: 'Alarm Clock Check' },
  { value: 'alarm-clock-minus', label: 'Alarm Clock Minus' },
  { value: 'alarm-clock-off', label: 'Alarm Clock Off' },
  { value: 'alarm-clock-plus', label: 'Alarm Clock Plus' },
] as const;

export type PageLucideIconId = (typeof PAGE_LUCIDE_ICONS)[number]['value'];

export const PAGE_LUCIDE_ICON_IDS: readonly PageLucideIconId[] = PAGE_LUCIDE_ICONS.map(
  (icon) => icon.value,
);

const LUCIDE_ID_SET = new Set<string>(PAGE_LUCIDE_ICON_IDS);

export function isPageLucideIconId(value: string): value is PageLucideIconId {
  return LUCIDE_ID_SET.has(value);
}

/** One persisted page mark. `value` is the emoji, Lucide id, brand slug, or image sha. */
export const PageIconSchema = z.object({
  kind: PageIconKindEnum,
  value: z.string().min(1).max(128),
});
export type PageIcon = z.infer<typeof PageIconSchema>;
export type SettablePageIcon = { kind: 'emoji' | 'lucide' | 'brand'; value: string };

/** PATCH /pages/:id/icon — image marks go through POST /pages/:id/icon-image. */
export const UpdatePageIconSchema = z.object({
  icon: z
    .union([
      z.object({
        kind: z.literal('emoji'),
        value: z
          .string()
          .min(1)
          .max(32)
          .refine((value) => !/[\u0000-\u001f<>\\]/.test(value), 'Invalid emoji'),
      }),
      z.object({
        kind: z.literal('lucide'),
        value: z.string().refine(isPageLucideIconId, 'Unknown icon'),
      }),
      z.object({
        kind: z.literal('brand'),
        value: z.string().refine(isPageBrandIconId, 'Unknown logo'),
      }),
    ])
    .nullable(),
});
export type UpdatePageIconInput = z.infer<typeof UpdatePageIconSchema>;

export const PageIconResponseSchema = z.object({
  icon: PageIconSchema.nullable(),
});
export type PageIconResponse = z.infer<typeof PageIconResponseSchema>;
