import { z } from 'zod';
import { isPageBrandIconId } from './page-brand-icons.js';

export { PAGE_BRAND_ICONS, PAGE_BRAND_ICON_IDS, getPageBrandIcon, isPageBrandIconId } from './page-brand-icons.js';
export type { PageBrandIconId } from './page-brand-icons.js';

export const PageIconKindEnum = z.enum(['emoji', 'lucide', 'image', 'brand']);
export type PageIconKind = z.infer<typeof PageIconKindEnum>;

/**
 * Closed Lucide catalogue a page mark may carry. Kept here so the PATCH
 * validator and the picker cannot disagree about which ids are legal.
 * HardDrive / Globe stay out — those are sidebar chrome for local / Confluence
 * spaces, and a page wearing either would be indistinguishable from that state.
 */
export const PAGE_LUCIDE_ICONS = [
  { value: 'book', label: 'Book' },
  { value: 'bookmark', label: 'Bookmark' },
  { value: 'file-text', label: 'Document' },
  { value: 'files', label: 'Files' },
  { value: 'folder', label: 'Folder' },
  { value: 'folder-open', label: 'Open folder' },
  { value: 'clipboard-list', label: 'Checklist' },
  { value: 'notebook', label: 'Notebook' },
  { value: 'newspaper', label: 'Newspaper' },
  { value: 'library', label: 'Library' },
  { value: 'rocket', label: 'Rocket' },
  { value: 'lightbulb', label: 'Idea' },
  { value: 'zap', label: 'Zap' },
  { value: 'star', label: 'Star' },
  { value: 'heart', label: 'Heart' },
  { value: 'flag', label: 'Flag' },
  { value: 'target', label: 'Target' },
  { value: 'compass', label: 'Compass' },
  { value: 'map', label: 'Map' },
  { value: 'milestone', label: 'Milestone' },
  { value: 'code', label: 'Code' },
  { value: 'terminal', label: 'Terminal' },
  { value: 'bug', label: 'Bug' },
  { value: 'git-branch', label: 'Branch' },
  { value: 'database', label: 'Database' },
  { value: 'server', label: 'Server' },
  { value: 'cpu', label: 'CPU' },
  { value: 'wifi', label: 'Network' },
  { value: 'lock', label: 'Lock' },
  { value: 'shield', label: 'Shield' },
  { value: 'key', label: 'Key' },
  { value: 'users', label: 'Team' },
  { value: 'user', label: 'Person' },
  { value: 'briefcase', label: 'Work' },
  { value: 'building-2', label: 'Building' },
  { value: 'calendar', label: 'Calendar' },
  { value: 'clock', label: 'Clock' },
  { value: 'mail', label: 'Mail' },
  { value: 'message-circle', label: 'Chat' },
  { value: 'bell', label: 'Bell' },
  { value: 'settings', label: 'Settings' },
  { value: 'wrench', label: 'Wrench' },
  { value: 'search', label: 'Search' },
  { value: 'filter', label: 'Filter' },
  { value: 'list', label: 'List' },
  { value: 'layout-grid', label: 'Grid' },
  { value: 'layers', label: 'Layers' },
  { value: 'puzzle', label: 'Puzzle' },
  { value: 'boxes', label: 'Boxes' },
  { value: 'package', label: 'Package' },
  { value: 'check-circle', label: 'Done' },
  { value: 'alert-triangle', label: 'Warning' },
  { value: 'info', label: 'Info' },
  { value: 'help-circle', label: 'Help' },
  { value: 'circle-dot', label: 'Point' },
  { value: 'pen-line', label: 'Edit' },
  { value: 'image', label: 'Image' },
  { value: 'camera', label: 'Camera' },
  { value: 'video', label: 'Video' },
  { value: 'music', label: 'Music' },
  { value: 'mic', label: 'Mic' },
  { value: 'play', label: 'Play' },
  { value: 'film', label: 'Film' },
  { value: 'leaf', label: 'Leaf' },
  { value: 'sun', label: 'Sun' },
  { value: 'moon', label: 'Moon' },
  { value: 'cloud', label: 'Cloud' },
  { value: 'droplet', label: 'Drop' },
  { value: 'flame', label: 'Flame' },
  { value: 'mountain', label: 'Mountain' },
  { value: 'tree-pine', label: 'Tree' },
  { value: 'flower-2', label: 'Flower' },
  { value: 'car', label: 'Car' },
  { value: 'plane', label: 'Plane' },
  { value: 'ship', label: 'Ship' },
  { value: 'bike', label: 'Bike' },
  { value: 'house', label: 'Home' },
  { value: 'coffee', label: 'Coffee' },
  { value: 'utensils', label: 'Food' },
  { value: 'gift', label: 'Gift' },
  { value: 'trophy', label: 'Trophy' },
  { value: 'medal', label: 'Medal' },
  { value: 'link', label: 'Link' },
  { value: 'paperclip', label: 'Attachment' },
  { value: 'pin', label: 'Pin' },
  { value: 'tag', label: 'Tag' },
  { value: 'hash', label: 'Hash' },
  { value: 'chart-column', label: 'Chart' },
  { value: 'graduation-cap', label: 'Learning' },
  { value: 'stethoscope', label: 'Health' },
  { value: 'scale', label: 'Legal' },
  { value: 'wallet', label: 'Finance' },
  { value: 'megaphone', label: 'Announce' },
  { value: 'sparkles', label: 'Sparkles' },
  { value: 'bot', label: 'Bot' },
  { value: 'archive', label: 'Archive' },
  { value: 'inbox', label: 'Inbox' },
  { value: 'book-open', label: 'Open book' },
  { value: 'book-marked', label: 'Marked book' },
  { value: 'sticky-note', label: 'Sticky note' },
  { value: 'notepad-text', label: 'Notes' },
  { value: 'file', label: 'File' },
  { value: 'file-stack', label: 'File stack' },
  { value: 'file-code', label: 'Code file' },
  { value: 'file-spreadsheet', label: 'Spreadsheet' },
  { value: 'file-json', label: 'JSON' },
  { value: 'file-archive', label: 'Zip file' },
  { value: 'folder-tree', label: 'Folder tree' },
  { value: 'folder-kanban', label: 'Board folder' },
  { value: 'folder-plus', label: 'New folder' },
  { value: 'scroll', label: 'Scroll' },
  { value: 'quote', label: 'Quote' },
  { value: 'type', label: 'Text' },
  { value: 'highlighter', label: 'Highlight' },
  { value: 'kanban', label: 'Board' },
  { value: 'list-todo', label: 'To-do' },
  { value: 'list-checks', label: 'Checks' },
  { value: 'clipboard', label: 'Clipboard' },
  { value: 'clipboard-check', label: 'Checked list' },
  { value: 'route', label: 'Route' },
  { value: 'signpost', label: 'Signpost' },
  { value: 'gantt-chart', label: 'Timeline' },
  { value: 'goal', label: 'Goal' },
  { value: 'focus', label: 'Focus' },
  { value: 'binoculars', label: 'Look' },
  { value: 'circle-check', label: 'Complete' },
  { value: 'circle-x', label: 'Cancel' },
  { value: 'circle-alert', label: 'Alert' },
  { value: 'ban', label: 'Blocked' },
  { value: 'circle-plus', label: 'Add' },
  { value: 'binary', label: 'Binary' },
  { value: 'brackets', label: 'Brackets' },
  { value: 'braces', label: 'Braces' },
  { value: 'square-terminal', label: 'Shell' },
  { value: 'container', label: 'Container' },
  { value: 'circuit-board', label: 'Circuit' },
  { value: 'monitor', label: 'Monitor' },
  { value: 'laptop', label: 'Laptop' },
  { value: 'smartphone', label: 'Phone' },
  { value: 'tablet', label: 'Tablet' },
  { value: 'keyboard', label: 'Keyboard' },
  { value: 'printer', label: 'Printer' },
  { value: 'plug', label: 'Power' },
  { value: 'cable', label: 'Cable' },
  { value: 'bluetooth', label: 'Bluetooth' },
  { value: 'radio-tower', label: 'Antenna' },
  { value: 'satellite', label: 'Satellite' },
  { value: 'cloud-upload', label: 'Upload cloud' },
  { value: 'cloud-download', label: 'Download cloud' },
  { value: 'upload', label: 'Upload' },
  { value: 'download', label: 'Download' },
  { value: 'refresh-cw', label: 'Refresh' },
  { value: 'repeat', label: 'Repeat' },
  { value: 'git-commit-horizontal', label: 'Commit' },
  { value: 'git-merge', label: 'Merge' },
  { value: 'git-pull-request', label: 'Pull request' },
  { value: 'workflow', label: 'Workflow' },
  { value: 'contact', label: 'Contact' },
  { value: 'handshake', label: 'Handshake' },
  { value: 'presentation', label: 'Present' },
  { value: 'crown', label: 'Crown' },
  { value: 'award', label: 'Award' },
  { value: 'badge-check', label: 'Verified' },
  { value: 'id-card', label: 'ID' },
  { value: 'smile', label: 'Smile' },
  { value: 'speech', label: 'Speak' },
  { value: 'headphones', label: 'Headset' },
  { value: 'phone', label: 'Call' },
  { value: 'send', label: 'Send' },
  { value: 'share-2', label: 'Share' },
  { value: 'at-sign', label: 'Mention' },
  { value: 'rss', label: 'Feed' },
  { value: 'atom', label: 'Atom' },
  { value: 'flask-conical', label: 'Lab' },
  { value: 'microscope', label: 'Microscope' },
  { value: 'telescope', label: 'Telescope' },
  { value: 'dna', label: 'DNA' },
  { value: 'pill', label: 'Medicine' },
  { value: 'brain', label: 'Brain' },
  { value: 'heart-pulse', label: 'Pulse' },
  { value: 'activity', label: 'Activity' },
  { value: 'test-tube', label: 'Test' },
  { value: 'map-pin', label: 'Location' },
  { value: 'navigation', label: 'Navigate' },
  { value: 'tent', label: 'Camp' },
  { value: 'palmtree', label: 'Palm' },
  { value: 'waves', label: 'Waves' },
  { value: 'wind', label: 'Wind' },
  { value: 'snowflake', label: 'Snow' },
  { value: 'umbrella', label: 'Rain' },
  { value: 'sunrise', label: 'Sunrise' },
  { value: 'sprout', label: 'Sprout' },
  { value: 'bird', label: 'Bird' },
  { value: 'fish', label: 'Fish' },
  { value: 'cat', label: 'Cat' },
  { value: 'dog', label: 'Dog' },
  { value: 'rabbit', label: 'Rabbit' },
  { value: 'paw-print', label: 'Paw' },
  { value: 'store', label: 'Shop' },
  { value: 'factory', label: 'Factory' },
  { value: 'warehouse', label: 'Warehouse' },
  { value: 'hospital', label: 'Hospital' },
  { value: 'school', label: 'School' },
  { value: 'landmark', label: 'Landmark' },
  { value: 'castle', label: 'Castle' },
  { value: 'truck', label: 'Truck' },
  { value: 'bus', label: 'Bus' },
  { value: 'train-front', label: 'Train' },
  { value: 'tram-front', label: 'Tram' },
  { value: 'fuel', label: 'Fuel' },
  { value: 'parking-circle', label: 'Parking' },
  { value: 'traffic-cone', label: 'Cone' },
  { value: 'construction', label: 'Build' },
  { value: 'anchor', label: 'Anchor' },
  { value: 'calculator', label: 'Calculator' },
  { value: 'receipt', label: 'Receipt' },
  { value: 'credit-card', label: 'Card' },
  { value: 'banknote', label: 'Cash' },
  { value: 'piggy-bank', label: 'Savings' },
  { value: 'percent', label: 'Percent' },
  { value: 'trending-up', label: 'Trending up' },
  { value: 'trending-down', label: 'Trending down' },
  { value: 'coins', label: 'Coins' },
  { value: 'timer', label: 'Timer' },
  { value: 'hourglass', label: 'Hourglass' },
  { value: 'calendar-days', label: 'Dates' },
  { value: 'calendar-check', label: 'Event' },
  { value: 'alarm-clock', label: 'Alarm' },
  { value: 'history', label: 'History' },
  { value: 'watch', label: 'Watch' },
  { value: 'fingerprint', label: 'Fingerprint' },
  { value: 'unlock', label: 'Unlock' },
  { value: 'vault', label: 'Vault' },
  { value: 'scan', label: 'Scan' },
  { value: 'qr-code', label: 'QR' },
  { value: 'eye', label: 'View' },
  { value: 'eye-off', label: 'Hidden' },
  { value: 'scan-search', label: 'Inspect' },
  { value: 'hammer', label: 'Hammer' },
  { value: 'cog', label: 'Gear' },
  { value: 'sliders-horizontal', label: 'Sliders' },
  { value: 'paintbrush', label: 'Brush' },
  { value: 'palette', label: 'Palette' },
  { value: 'pipette', label: 'Sample' },
  { value: 'ruler', label: 'Ruler' },
  { value: 'scissors', label: 'Cut' },
  { value: 'magnet', label: 'Magnet' },
  { value: 'flashlight', label: 'Light' },
  { value: 'apple', label: 'Apple' },
  { value: 'cherry', label: 'Cherry' },
  { value: 'pizza', label: 'Pizza' },
  { value: 'wine', label: 'Wine' },
  { value: 'beer', label: 'Beer' },
  { value: 'cookie', label: 'Cookie' },
  { value: 'cake', label: 'Cake' },
  { value: 'ice-cream-cone', label: 'Ice cream' },
  { value: 'shopping-cart', label: 'Cart' },
  { value: 'shopping-bag', label: 'Bag' },
  { value: 'dumbbell', label: 'Fitness' },
  { value: 'gamepad-2', label: 'Games' },
  { value: 'dice-5', label: 'Dice' },
  { value: 'party-popper', label: 'Celebrate' },
  { value: 'ticket', label: 'Ticket' },
  { value: 'clapperboard', label: 'Scene' },
  { value: 'chart-line', label: 'Line chart' },
  { value: 'chart-pie', label: 'Pie chart' },
  { value: 'chart-area', label: 'Area chart' },
  { value: 'table', label: 'Table' },
  { value: 'table-2', label: 'Spreadsheet table' },
  { value: 'sigma', label: 'Sigma' },
  { value: 'function-square', label: 'Function' },
  { value: 'variable', label: 'Variable' },
  { value: 'regex', label: 'Regex' },
  { value: 'component', label: 'Component' },
  { value: 'blocks', label: 'Blocks' },
  { value: 'app-window', label: 'Window' },
  { value: 'network', label: 'Graph' },
  { value: 'ethernet-port', label: 'Ethernet' },
  { value: 'hard-hat', label: 'Hard hat' },
  { value: 'rainbow', label: 'Rainbow' },
  { value: 'pentagon', label: 'Pentagon' },
  { value: 'hexagon', label: 'Hexagon' },
  { value: 'triangle', label: 'Triangle' },
  { value: 'diamond', label: 'Diamond' },
  { value: 'asterisk', label: 'Asterisk' },
  { value: 'infinity', label: 'Infinity' },
  { value: 'equal', label: 'Equal' },
  { value: 'plus', label: 'Plus' },
  { value: 'minus', label: 'Minus' },
  { value: 'x', label: 'Close' },
  { value: 'check', label: 'Check' },
  { value: 'thumbs-up', label: 'Thumbs up' },
  { value: 'thumbs-down', label: 'Thumbs down' },
  { value: 'hand', label: 'Hand' },
  { value: 'pointer', label: 'Pointer' },
  { value: 'mouse-pointer-2', label: 'Cursor' },
  { value: 'volume-2', label: 'Volume' },
  { value: 'contrast', label: 'Contrast' },
  { value: 'sun-moon', label: 'Day night' },
  { value: 'eclipse', label: 'Eclipse' },
  { value: 'orbit', label: 'Orbit' },
  { value: 'earth', label: 'Earth' },
  { value: 'cuboid', label: 'Cube' },
  { value: 'file-pen', label: 'Edit file' },
  { value: 'file-search', label: 'Search file' },
  { value: 'book-copy', label: 'Copy book' },
  { value: 'wand-sparkles', label: 'Wand' },
  { value: 'sparkle', label: 'Sparkle' },
  { value: 'shield-check', label: 'Shield check' },
  { value: 'shield-alert', label: 'Shield alert' },
  { value: 'user-check', label: 'User check' },
  { value: 'user-plus', label: 'Add user' },
  { value: 'voicemail', label: 'Voicemail' },
  { value: 'brain-circuit', label: 'Neural' },
  { value: 'bot-message-square', label: 'Chat bot' },
  { value: 'messages-square', label: 'Threads' },
  { value: 'folder-git-2', label: 'Git folder' },
  { value: 'git-compare', label: 'Compare' },
  { value: 'ampersand', label: 'And' },
] as const;

export type PageLucideIconId = (typeof PAGE_LUCIDE_ICONS)[number]['value'];

export const PAGE_LUCIDE_ICON_IDS: readonly PageLucideIconId[] = PAGE_LUCIDE_ICONS.map(
  (icon) => icon.value,
);

const LUCIDE_ID_SET = new Set<string>(PAGE_LUCIDE_ICON_IDS);

export function isPageLucideIconId(value: string): value is PageLucideIconId {
  return LUCIDE_ID_SET.has(value);
}

/** One persisted page mark. `value` is the emoji, Lucide id, brand slug, or image sha. */
export const PageIconSchema = z.object({
  kind: PageIconKindEnum,
  value: z.string().min(1).max(128),
});
export type PageIcon = z.infer<typeof PageIconSchema>;
export type SettablePageIcon = { kind: 'emoji' | 'lucide' | 'brand'; value: string };

/** PATCH /pages/:id/icon — image marks go through POST /pages/:id/icon-image. */
export const UpdatePageIconSchema = z.object({
  icon: z
    .union([
      z.object({
        kind: z.literal('emoji'),
        value: z
          .string()
          .min(1)
          .max(32)
          .refine((value) => !/[\u0000-\u001f<>\\]/.test(value), 'Invalid emoji'),
      }),
      z.object({
        kind: z.literal('lucide'),
        value: z.string().refine(isPageLucideIconId, 'Unknown icon'),
      }),
      z.object({
        kind: z.literal('brand'),
        value: z.string().refine(isPageBrandIconId, 'Unknown logo'),
      }),
    ])
    .nullable(),
});
export type UpdatePageIconInput = z.infer<typeof UpdatePageIconSchema>;

export const PageIconResponseSchema = z.object({
  icon: PageIconSchema.nullable(),
});
export type PageIconResponse = z.infer<typeof PageIconResponseSchema>;
