#!/usr/bin/env bash
# AtlasMind One-Command Docker Installer
# Usage: curl -fsSL https://raw.githubusercontent.com/laboef1900/ai-kb-creator/main/scripts/install.sh | bash
# Custom install dir: INSTALL_DIR=~/mydir bash <(curl -fsSL ...)
# Custom version:     ATLASMIND_VERSION=1.0.0 bash <(curl -fsSL ...)
#
# Tested on Linux (GNU coreutils) and WSL2 (GNU sed required for port removal step).
# macOS: sed -i '' differs from GNU sed -i; this script targets Linux/WSL2.

set -euo pipefail

# ─── Colour helpers ───────────────────────────────────────────────────────────
if [ -t 1 ] && command -v tput >/dev/null 2>&1; then
  BOLD=$(tput bold 2>/dev/null || printf '')
  RED=$(tput setaf 1 2>/dev/null || printf '')
  GREEN=$(tput setaf 2 2>/dev/null || printf '')
  YELLOW=$(tput setaf 3 2>/dev/null || printf '')
  CYAN=$(tput setaf 6 2>/dev/null || printf '')
  RESET=$(tput sgr0 2>/dev/null || printf '')
else
  BOLD='' RED='' GREEN='' YELLOW='' CYAN='' RESET=''
fi

info()    { printf '%s  %s%s\n'    "${CYAN}ℹ${RESET}"  "$*" "${RESET}"; }
success() { printf '%s  %s%s\n'    "${GREEN}✓${RESET}" "$*" "${RESET}"; }
warn()    { printf '%s  %s%s\n'    "${YELLOW}⚠${RESET}" "$*" "${RESET}"; }
error()   { printf '%s  %s%s\n'    "${RED}✗${RESET}"  "$*" "${RESET}" >&2; }
step()    { printf '\n%s==>%s %s%s%s\n' "${BOLD}${CYAN}" "${RESET}" "${BOLD}" "$*" "${RESET}"; }

# ─── Configuration ────────────────────────────────────────────────────────────
ATLASMIND_VERSION="${ATLASMIND_VERSION:-latest}"
INSTALL_DIR="${INSTALL_DIR:-$HOME/atlasmind}"
HEALTH_URL="http://localhost:3051/api/health/ready"
FRONTEND_URL="http://localhost:8081"
MAX_RETRIES=36   # 36 × 5s = 3 minutes

# ─── Prerequisite checks ─────────────────────────────────────────────────────
step "Checking prerequisites"

if ! docker info >/dev/null 2>&1; then
  error "Docker is not running or not installed."
  error "Install Docker: https://docs.docker.com/engine/install/"
  exit 1
fi
success "Docker daemon is running"

if ! docker compose version >/dev/null 2>&1; then
  error "Docker Compose v2 is required (docker compose, not docker-compose)."
  error "Install: https://docs.docker.com/compose/install/"
  exit 1
fi
success "Docker Compose v2 found"

# Check port availability
for port in 8081 3051; do
  if ss -tlnp 2>/dev/null | grep -q ":${port} " || \
     netstat -tlnp 2>/dev/null | grep -q ":${port} "; then
    error "Port ${port} is already in use. Free it and re-run the installer."
    exit 1
  fi
done
success "Ports 8081 and 3051 are available"

# ─── Secret generation ────────────────────────────────────────────────────────
# Bug-1 fix: use openssl rand -hex to produce exactly N hex characters.
# openssl rand -hex 32 → 64 lowercase hex chars (no filtering, no truncation).
# openssl rand -hex 16 → 32 lowercase hex chars.
# od fallback produces the same deterministic hex output from /dev/urandom.

gen64() {
  openssl rand -hex 32 2>/dev/null \
    || dd if=/dev/urandom bs=32 count=1 2>/dev/null | od -An -tx1 | tr -d ' \n' | head -c 64
}

gen32() {
  openssl rand -hex 16 2>/dev/null \
    || dd if=/dev/urandom bs=16 count=1 2>/dev/null | od -An -tx1 | tr -d ' \n' | head -c 32
}

step "Generating cryptographic secrets"
JWT_SECRET=$(gen64)
PAT_ENCRYPTION_KEY=$(gen64)
POSTGRES_PASSWORD=$(gen32)
REDIS_PASSWORD=$(gen32)
OLLAMA_BASE_URL="${OLLAMA_BASE_URL:-http://host.docker.internal:11434}"

success "Secrets generated (64-char hex keys, not logged)"

# ─── Create install directory ─────────────────────────────────────────────────
step "Creating install directory: ${INSTALL_DIR}"
mkdir -p "${INSTALL_DIR}"

# ─── Write .env ───────────────────────────────────────────────────────────────
# Bug-2 fix: UNQUOTED heredoc delimiter (<< EOF, not << 'EOF') so all shell
# variables are expanded to their runtime values at write time.
step "Writing configuration"

cat > "${INSTALL_DIR}/.env" << EOF
# AtlasMind - generated by install.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Keep this file secret — it contains your encryption keys and passwords.
JWT_SECRET=$JWT_SECRET
PAT_ENCRYPTION_KEY=$PAT_ENCRYPTION_KEY
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
REDIS_PASSWORD=$REDIS_PASSWORD
ATLASMIND_VERSION=$ATLASMIND_VERSION
OLLAMA_BASE_URL=$OLLAMA_BASE_URL
EOF

success ".env written to ${INSTALL_DIR}/.env"

# ─── Write docker-compose.yml ─────────────────────────────────────────────────
# All secrets and version tags are embedded as literal values (not \${VAR}
# references) so docker-compose itself needs no variable substitution at runtime.
# SECURITY NOTE (port 3051): the backend port is exposed here only so the host
# health poll can reach it. After health is confirmed the port mapping is removed
# via sed and the container is force-recreated (see health-poll section below).

cat > "${INSTALL_DIR}/docker-compose.yml" << EOF
# AtlasMind - generated by install.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Do not edit the secrets directly; re-run install.sh to regenerate.

services:
  frontend:
    image: diinlu/atlasmind-frontend:$ATLASMIND_VERSION
    ports:
      - "8081:8081"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

  backend:
    image: diinlu/atlasmind-backend:$ATLASMIND_VERSION
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      NODE_ENV: production
      BACKEND_PORT: "3051"
      POSTGRES_URL: postgresql://kb_user:$POSTGRES_PASSWORD@postgres:5432/kb_creator
      REDIS_URL: redis://:$REDIS_PASSWORD@redis:6379
      JWT_SECRET: $JWT_SECRET
      PAT_ENCRYPTION_KEY: $PAT_ENCRYPTION_KEY
      OLLAMA_BASE_URL: $OLLAMA_BASE_URL
      LLM_PROVIDER: ollama
      LLM_AUTH_TYPE: none
      LLM_VERIFY_SSL: "true"
      EMBEDDING_MODEL: nomic-embed-text
      FRONTEND_URL: http://localhost:8081
      ATTACHMENTS_DIR: /app/data/attachments
    # TEMPORARY: port 3051 is exposed only during the health poll in install.sh.
    # install.sh removes this mapping via sed after health is confirmed and
    # force-recreates the backend container to close the host port binding.
    ports:
      - "3051:3051"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - attachments:/app/data
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://127.0.0.1:3051/api/health/ready').then(r=>{if(!r.ok)process.exit(1)}).catch(()=>process.exit(1))"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  postgres:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: kb_user
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: kb_creator
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kb_user -d kb_creator"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:8-alpine
    command: >
      redis-server
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
      --requirepass $REDIS_PASSWORD
    healthcheck:
      test: ["CMD-SHELL", "REDISCLI_AUTH=$REDIS_PASSWORD redis-cli ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres-data:
  attachments:
EOF

success "docker-compose.yml written to ${INSTALL_DIR}/docker-compose.yml"

# ─── Pull images ──────────────────────────────────────────────────────────────
step "Pulling Docker images (this may take a few minutes on first run)"
docker compose -f "${INSTALL_DIR}/docker-compose.yml" pull
success "Images pulled"

# ─── Start containers ─────────────────────────────────────────────────────────
step "Starting AtlasMind containers"
docker compose -f "${INSTALL_DIR}/docker-compose.yml" up -d
success "Containers started"

# ─── Health poll ──────────────────────────────────────────────────────────────
# Bug-3 fix: wrap every curl call in an if-conditional so non-zero exit codes
# are consumed and do not trigger 'set -e'.
# 'sleep 5 || true' prevents SIGINT from killing the script mid-sleep.
step "Waiting for AtlasMind to be ready (up to 3 minutes)"
HEALTHY=0
RETRIES=0

while [ "$RETRIES" -lt "$MAX_RETRIES" ]; do
  if curl -sf "${HEALTH_URL}" 2>/dev/null; then
    HEALTHY=1
    break
  fi
  RETRIES=$((RETRIES + 1))
  printf '.'
  sleep 5 || true
done
printf '\n'

if [ "$HEALTHY" -eq 0 ]; then
  error "AtlasMind did not become healthy within 3 minutes."
  error "Check container logs: docker compose -f ${INSTALL_DIR}/docker-compose.yml logs --tail=50"
  exit 1
fi
success "AtlasMind is healthy"

# ─── Remove port 3051 (Security fix — Option A) ──────────────────────────────
# The backend port was exposed only for the health poll above.
# Now we remove the host port binding and force-recreate the backend container
# so port 3051 is no longer accessible from the host.
# NOTE: GNU sed (Linux/WSL2) uses 'sed -i' without a suffix argument.
#       macOS requires 'sed -i ""' — this installer targets Linux/WSL2 only.
step "Removing temporary backend port exposure (port 3051)"
sed -i '/- "3051:3051"/d' "${INSTALL_DIR}/docker-compose.yml"
docker compose -f "${INSTALL_DIR}/docker-compose.yml" up -d --no-deps --force-recreate backend
success "Port 3051 removed from host and container restarted"

# ─── Print success ────────────────────────────────────────────────────────────
printf '\n'
printf '%s╔══════════════════════════════════════════════════════╗%s\n' "${GREEN}${BOLD}" "${RESET}"
printf '%s║  AtlasMind installed successfully!                   ║%s\n' "${GREEN}${BOLD}" "${RESET}"
printf '%s╚══════════════════════════════════════════════════════╝%s\n' "${GREEN}${BOLD}" "${RESET}"
printf '\n'
info "Setup wizard: ${BOLD}${FRONTEND_URL}${RESET}"
info "Install dir:  ${BOLD}${INSTALL_DIR}${RESET}"
info "Logs:         docker compose -f ${INSTALL_DIR}/docker-compose.yml logs -f"
info "Stop:         docker compose -f ${INSTALL_DIR}/docker-compose.yml down"
info "Uninstall:    bash ${INSTALL_DIR}/uninstall.sh"
printf '\n'
warn "Ollama must be running on your host at port 11434."
warn "Pull models:  ollama pull nomic-embed-text && ollama pull qwen3:4b"
printf '\n'

# ─── Open browser ────────────────────────────────────────────────────────────
# Bug-7 fix: guard the entire browser-launch block with || true so its exit
# code cannot propagate under set -e.
BROWSER_CMD=''
if command -v open >/dev/null 2>&1; then
  BROWSER_CMD='open'
elif command -v xdg-open >/dev/null 2>&1; then
  BROWSER_CMD='xdg-open'
fi
if [ -n "$BROWSER_CMD" ]; then
  $BROWSER_CMD "$FRONTEND_URL" 2>/dev/null || true
fi
