import type { ReferenceAction } from '../services/ai-safety-service.js';

// ─── Types ────────────────────────────────────────────────────────────────────

export interface OutputSanitizeResult {
  content: string;
  wasModified: boolean;
  strippedSections: string[];
  disclaimer: string | null;
}

export interface OutputRules {
  stripReferences: boolean;
  referenceAction: ReferenceAction;
  verifiedSources?: string[];
  /**
   * Issue #705 — Swiss spelling. When true, every `ß` is replaced with `ss`
   * and capital `ẞ` (U+1E9E) with `SS`. Switzerland abolished the eszett, so
   * for Swiss teams every `ß` the model produces is wrong. This is a blanket
   * replace (including fenced/inline code) — CH uses `ss` everywhere.
   */
  swissSpelling?: boolean;
}

// ─── Default disclaimer ───────────────────────────────────────────────────────

const DEFAULT_DISCLAIMER =
  '> **Note**: The following references were generated by AI and have not been verified. They may not correspond to real sources.';

// ─── Heading detection patterns (critic fix #5 — broadened) ───────────────────

const REFERENCE_HEADING_NAMES = [
  'References',
  'Sources',
  'Bibliography',
  'Works Cited',
  'Further Reading',
];

// Escape for regex
const namesPattern = REFERENCE_HEADING_NAMES.map((n) => n.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')).join('|');

// ATX-style: # References, ## References, ### References, #### References
const ATX_PATTERN = new RegExp(`^#{1,4}\\s+(${namesPattern})\\s*$`, 'im');

// Setext-style: References\n========= or References\n---------
const SETEXT_PATTERN = new RegExp(`^(${namesPattern})\\s*\\n[=-]{3,}\\s*$`, 'im');

// Bold-colon: **References:** or **Sources:** or **References**:
const BOLD_COLON_PATTERN = new RegExp(`^\\*\\*(${namesPattern}):?\\*\\*:?\\s*$`, 'im');

/**
 * Find the start index of a reference-like section in LLM output.
 * Returns the index of the heading line, or -1 if not found.
 */
function findReferenceSectionStart(content: string): { index: number; headingName: string } {
  for (const pattern of [ATX_PATTERN, SETEXT_PATTERN, BOLD_COLON_PATTERN]) {
    const match = pattern.exec(content);
    if (match) {
      return { index: match.index, headingName: match[1] ?? '' };
    }
  }
  return { index: -1, headingName: '' };
}

/**
 * Extract URLs from a text block (simple regex for http/https URLs).
 */
function extractUrls(text: string): string[] {
  const urlPattern = /https?:\/\/[^\s)>\]"'`]+/g;
  return Array.from(text.matchAll(urlPattern), (m) => m[0]);
}

/**
 * Check if all URLs in a section are verified (exist in verifiedSources).
 */
function allUrlsVerified(urls: string[], verifiedSources: string[]): boolean {
  if (urls.length === 0) return false; // no URLs = can't verify
  const verified = new Set(verifiedSources.map((u) => u.toLowerCase()));
  return urls.every((url) => verified.has(url.toLowerCase()));
}

/**
 * Issue #705 — enforce Swiss orthography by replacing the eszett.
 *
 * Swiss Standard German uses `ss` in every position where German Standard
 * German uses `ß`, so a blanket replace is exactly correct (there are no
 * positional exceptions). `ß` → `ss`, capital `ẞ` (U+1E9E) → `SS`.
 */
function applySwissSpelling(content: string): string {
  return content.replace(/ß/g, 'ss').replace(/ẞ/g, 'SS');
}

// ─── Main sanitizer ───────────────────────────────────────────────────────────

export function sanitizeLlmOutput(output: string, rules: OutputRules): OutputSanitizeResult {
  // Run the reference-handling pass, then the Swiss-spelling pass. The two are
  // independent rules — Swiss spelling must apply even when reference detection
  // is disabled — so the result of the first feeds the second.
  const referenceResult = sanitizeReferences(output, rules);

  if (!rules.swissSpelling) {
    return referenceResult;
  }

  const swissContent = applySwissSpelling(referenceResult.content);
  return {
    ...referenceResult,
    content: swissContent,
    wasModified: referenceResult.wasModified || swissContent !== referenceResult.content,
  };
}

/**
 * Reference-section handling (strip / flag / verified-source preservation).
 * Returns the unmodified output when reference detection is disabled or no
 * reference section is found.
 */
function sanitizeReferences(output: string, rules: OutputRules): OutputSanitizeResult {
  // Pass through if disabled
  if (!rules.stripReferences || rules.referenceAction === 'off') {
    return { content: output, wasModified: false, strippedSections: [], disclaimer: null };
  }

  const { index, headingName } = findReferenceSectionStart(output);
  if (index === -1) {
    return { content: output, wasModified: false, strippedSections: [], disclaimer: null };
  }

  // Extract the reference section (from heading to end of content)
  const referenceSection = output.slice(index);

  // Check if all URLs in the section are verified
  const urls = extractUrls(referenceSection);
  if (urls.length > 0 && allUrlsVerified(urls, rules.verifiedSources ?? [])) {
    // All references are real — preserve the section
    return { content: output, wasModified: false, strippedSections: [], disclaimer: null };
  }

  // Apply the configured action
  const contentBeforeRefs = output.slice(0, index).trimEnd();

  if (rules.referenceAction === 'strip') {
    return {
      content: contentBeforeRefs,
      wasModified: true,
      strippedSections: [headingName],
      disclaimer: null,
    };
  }

  // 'flag' — keep section but prepend disclaimer
  const flaggedContent = `${contentBeforeRefs}\n\n${DEFAULT_DISCLAIMER}\n\n${referenceSection}`;
  return {
    content: flaggedContent,
    wasModified: true,
    strippedSections: [],
    disclaimer: DEFAULT_DISCLAIMER,
  };
}
