/**
 * Shared confirmation dialog — replaces the browser-native confirm() prompt so
 * confirmations match the neumorphic design system (ADR-010) instead of
 * the OS-styled browser dialog.
 *
 * Built on @radix-ui/react-dialog (same primitive as UserBulkActionDialog
 * et al.), which provides focus trapping, initial focus, Escape-to-dismiss
 * and overlay-click-to-dismiss for free. Both dismissal paths route
 * through `onCancel` via `onOpenChange(false)` — unless `onDismiss` is
 * provided, which they route to instead. Pass `onDismiss` whenever the
 * Cancel button carries a real action (not just "close"), so Escape and
 * overlay-click stay neutral.
 *
 * The confirm button uses the design-system `nm-button-destructive`
 * utility when `destructive` (same box metrics as `nm-button-primary` /
 * `nm-button-ghost`, destructive palette), otherwise `nm-button-primary`.
 *
 * **Focus returns to whatever invoked it** (#1531). Radix's own restore does
 * not fire here: `DialogContentModal` composes an `onCloseAutoFocus` that
 * `preventDefault()`s FocusScope's `focus(previouslyFocusedElement)` and
 * focuses `context.triggerRef` instead — and this component is fully
 * controlled through the `open` prop and renders no `Dialog.Trigger`, so that
 * ref is permanently `null`. The suppression stood, the replacement focused
 * nothing, and Cancel, Escape and Confirm each dropped the keyboard to
 * `<body>` at the top of a ~30-stop settings panel (WCAG 2.4.3). So the pair
 * of Radix hooks below saves the element that was focused when the dialog
 * opened and returns focus to it on close.
 *
 * Saving the NODE is not enough, which the browser pass proved on two shapes
 * where the invoker does not survive the dialog (fixer, external round):
 *
 * 1. The confirmed action takes its own trigger out from under the restore —
 *    `SyncTab`'s Force re-sync all is `disabled` 7 ms after the click and
 *    focusable again by 48 ms, i.e. unfocusable across exactly Radix's
 *    `setTimeout(…, 0)`; other callsites re-mount the trigger as a NEW node in
 *    the same commit. A one-shot `focus()` fires into that window and does
 *    nothing. Hence `restoreFocus`: the invoker is re-resolved by identity
 *    (`data-testid`, else `id`) rather than held as a node, and the attempt is
 *    re-made on every DOM mutation that could hand the control its focusability
 *    back. That wait is event-driven and not a clock: three ConfirmDialog
 *    triggers hold themselves natively `disabled` for exactly as long as their
 *    POST takes (`WorkersTab` Rescan All, `SpacesTab` Remove space,
 *    `BulkActionBar` Move to Trash), so a fixed wall-clock window restored
 *    focus on a fast server and silently gave up on a slow one (review r1).
 * 2. A dialog opened from a menu item captures the closing menu's portalled
 *    content, never the kebab the admin pressed (`ConversationRowMenu` Delete,
 *    `UserMenu` Sign out). Radix names the owner — menu content carries
 *    `aria-labelledby={triggerId}` and the trigger carries that `id` — so
 *    `menuOwner` resolves the real invoker at capture time. That is Radix's
 *    own aria contract, not an ancestor guess.
 *
 * Both paths keep the one rule that makes this safe to put in a shared
 * component: nothing is ever taken from a keyboard that is somewhere else, and
 * nothing is taken from an admin who has moved on. The restore — first attempt
 * and every re-attempt — acts only while `document.activeElement` is `<body>`,
 * ends at the first pointer press anywhere, and cannot start at all once this
 * component has been unmounted (Radix dispatches close-auto-focus one
 * macrotask AFTER the unmount commit, so the cleanup alone cannot stop it).
 */

import { useEffect, useRef } from 'react';
import * as Dialog from '@radix-ui/react-dialog';

/**
 * The invoking control, plus a way to find it again if the confirmed action
 * replaced the node. `data-testid` first: an `id` on a Radix control is
 * `useId()` output and is regenerated by a re-mount, so it only ever resolves
 * the node that is still there.
 */
interface Invoker {
  node: HTMLElement;
  selector: string | null;
}

/**
 * When a restore the invoker never satisfied is abandoned. Not a latency
 * budget: the wait is driven by the DOM mutations that make a control
 * focusable again, so a POST answering in 5 s restores as surely as one
 * answering in 5 ms. This is only the point past which a trigger that never
 * came back stops being watched, so no dialog leaves an observer on the
 * document for a settings panel's lifetime.
 */
const RESTORE_CEILING_MS = 10_000;

/**
 * The attributes that decide whether a control can take focus. A trigger its
 * own mutation held `disabled` becomes focusable again through one of these; a
 * trigger the commit re-mounted arrives as a `childList` mutation instead.
 * `class`/`style` are here because a callsite may hold a control out of the
 * tab order through CSS rather than through an attribute.
 */
const FOCUSABILITY_ATTRS = ['disabled', 'hidden', 'inert', 'tabindex', 'class', 'style'];

const cssString = (value: string) => `"${value.replace(/["\\]/g, '\\$&')}"`;

function identitySelector(node: HTMLElement): string | null {
  const testid = node.dataset.testid;
  if (testid) return `[data-testid=${cssString(testid)}]`;
  if (node.id) return `[id=${cssString(node.id)}]`;
  return null;
}

/** See (2) in the header: the menu the captured node belongs to names its trigger. */
function menuOwner(active: HTMLElement): HTMLElement | null {
  const menu = active.closest('[role="menu"],[role="menubar"]');
  const ownerId = menu?.getAttribute('aria-labelledby');
  const owner = ownerId ? document.getElementById(ownerId) : null;
  return owner instanceof HTMLElement ? owner : null;
}

function captureInvoker(active: Element | null): Invoker | null {
  if (!(active instanceof HTMLElement)) return null;
  const node = menuOwner(active) ?? active;
  return { node, selector: identitySelector(node) };
}

function resolveInvoker({ node, selector }: Invoker): HTMLElement | null {
  if (document.contains(node)) return node;
  const replacement = selector ? document.querySelector(selector) : null;
  return replacement instanceof HTMLElement ? replacement : null;
}

export interface ConfirmDialogProps {
  open: boolean;
  title: string;
  description: string;
  confirmLabel: string;
  /** Cancel-button text. Defaults to "Cancel". */
  cancelLabel?: string;
  destructive?: boolean;
  onConfirm: () => void;
  onCancel: () => void;
  /**
   * Escape / overlay-click handler. Defaults to `onCancel`. Provide it when
   * the Cancel button performs a real action, so dismissing the dialog means
   * "close without choosing" rather than silently picking the cancel path.
   */
  onDismiss?: () => void;
}

export function ConfirmDialog({
  open,
  title,
  description,
  confirmLabel,
  cancelLabel = 'Cancel',
  destructive = false,
  onConfirm,
  onCancel,
  onDismiss,
}: ConfirmDialogProps) {
  /**
   * The control that had focus when this dialog opened. Captured in
   * `onOpenAutoFocus` rather than in an effect: FocusScope reads
   * `document.activeElement`, dispatches that event, and only THEN moves focus
   * into the content, so the event is the last moment the invoking element is
   * still `activeElement` — and a `useEffect` here would run after the child's
   * mount effect, i.e. after focus has already moved.
   */
  const invokerRef = useRef<Invoker | null>(null);
  /** The live restore, or `null` when none is waiting. */
  const pendingRef = useRef<{
    observer: MutationObserver;
    listeners: AbortController;
    ceiling: number;
  } | null>(null);
  /**
   * False from the unmount commit onwards. Radix's FocusScope dispatches
   * close-auto-focus from a `setTimeout(…, 0)` in its own effect cleanup, so an
   * owner that unmounts a still-OPEN dialog (a 401 redirect to the login page,
   * a parent switching to an error branch) reaches `onCloseAutoFocus` a
   * macrotask after every cleanup here has already run: cancelling a pending
   * restore cannot cancel one that has not started yet. Without this flag the
   * orphaned restore re-resolves the invoker by `data-testid` against whatever
   * surface replaced the dialog's own, and a fresh screen looks exactly like
   * the state the restore waits for — `<body>` holding the keyboard (review
   * r1, proved by a probe that focused a control on the next route).
   */
  const aliveRef = useRef(true);

  const cancelRestore = () => {
    const pending = pendingRef.current;
    if (!pending) return;
    pendingRef.current = null;
    pending.observer.disconnect();
    // Removal by signal, not by handler identity: `cancelRestore` is a fresh
    // closure on every render, so a later render could not remove the listener
    // an earlier one added.
    pending.listeners.abort();
    window.clearTimeout(pending.ceiling);
  };

  /**
   * One attempt; if the invoker cannot take focus yet, re-attempt on every DOM
   * mutation that could give it its focusability back, until it takes focus,
   * something else claims the keyboard, the admin presses somewhere, or the
   * ceiling passes. Anything but `<body>` holding the keyboard ends the
   * restore: the admin who tabbed on, and the callsite that rehomed focus
   * during its own commit (`EmbeddingShadowMigrationCard`'s
   * `rehomeAfterDismiss`), have both already put focus somewhere deliberate.
   * A pointer press ends it too — that admin moved on without moving focus off
   * `<body>`, which is the one "moved on" the guard above cannot see.
   */
  const restoreFocus = (invoker: Invoker) => {
    const attempt = () => {
      if (!aliveRef.current) return true;
      if (document.activeElement !== document.body) return true;
      resolveInvoker(invoker)?.focus();
      return document.activeElement !== document.body;
    };
    if (attempt()) return;
    const observer = new MutationObserver(() => {
      if (attempt()) cancelRestore();
    });
    observer.observe(document.body, {
      childList: true,
      subtree: true,
      attributes: true,
      attributeFilter: FOCUSABILITY_ATTRS,
    });
    const listeners = new AbortController();
    window.addEventListener('pointerdown', cancelRestore, {
      capture: true,
      signal: listeners.signal,
    });
    pendingRef.current = {
      observer,
      listeners,
      ceiling: window.setTimeout(cancelRestore, RESTORE_CEILING_MS),
    };
  };

  // A pending restore outlives this component otherwise, and would fire
  // against a torn-down document (the `@radix-ui/react-focus-scope` leak
  // `test-setup` already works around, #799). `aliveRef` covers the other
  // order — the restore that starts after this cleanup ran.
  useEffect(() => {
    aliveRef.current = true;
    return () => {
      aliveRef.current = false;
      cancelRestore();
    };
  }, []);

  return (
    <Dialog.Root
      open={open}
      onOpenChange={(nextOpen) => {
        if (!nextOpen) (onDismiss ?? onCancel)();
      }}
    >
      <Dialog.Portal>
        <Dialog.Overlay
          className="fixed inset-0 z-50 bg-black/50 backdrop-blur-sm"
          data-testid="confirm-dialog-overlay"
        />
        <Dialog.Content
          className="nm-card fixed left-1/2 top-1/2 z-50 w-full max-w-md -translate-x-1/2 -translate-y-1/2 p-6 outline-none"
          data-testid="confirm-dialog"
          onOpenAutoFocus={() => {
            cancelRestore();
            invokerRef.current = captureInvoker(document.activeElement);
            // Deliberately no `preventDefault()`: Radix's initial focus into
            // the content is the focus-trap entry this dialog wants.
          }}
          onCloseAutoFocus={(event) => {
            const invoker = invokerRef.current;
            invokerRef.current = null;
            cancelRestore();
            if (!invoker) return;
            // Suppresses `DialogContentModal`'s composed handler, which would
            // otherwise `preventDefault()` FocusScope's restore and focus a
            // `triggerRef` this trigger-less dialog never populates. Safe to
            // do unconditionally: that handler focuses a permanently-`null`
            // ref, so suppressing it changes nothing even on the paths where
            // `restoreFocus` declines to act (proved by deleting the
            // `<body>` guard in `restoreFocus` — with it gone the rehome cell
            // reds, and nothing reds for this line).
            event.preventDefault();
            restoreFocus(invoker);
          }}
        >
          <Dialog.Title className="text-base font-semibold text-foreground">
            {title}
          </Dialog.Title>
          <Dialog.Description className="mt-2 text-sm text-muted-foreground">
            {description}
          </Dialog.Description>
          <div className="mt-6 flex justify-end gap-2">
            <button
              type="button"
              onClick={onCancel}
              className="nm-button-ghost"
              data-testid="confirm-dialog-cancel"
            >
              {cancelLabel}
            </button>
            <button
              type="button"
              onClick={onConfirm}
              className={destructive ? 'nm-button-destructive' : 'nm-button-primary'}
              data-testid="confirm-dialog-confirm"
            >
              {confirmLabel}
            </button>
          </div>
        </Dialog.Content>
      </Dialog.Portal>
    </Dialog.Root>
  );
}
